### ISSUE TITLE
display of <quote>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#101]
- example of code:

```
<div type="commentary">
<p>Regarding the nature of this document and the translation recorded in it, J. Wisseman Christie has offered the following summary:
<cit><quote rend="block">
The Kurungan inscription of 885 A.D. (Appendix A.2) is not principally a debt-clearance document. It records the purchase of wet rice land for 1 <foreign>kati</foreign> or 768 grams of silver by a religious personage, <hi rend="bold">for the purpose of presentation as a meritorious gift to a religious community</hi>. Part of the statutory gifts presented to the community from which the land was purchased took the form of the writing off of 7 <foreign>dhāraṇa</foreign> or 268.8 grams of silver, the sum of the interest on the community's debt. This apparently completed the repayment ot that debt, the sale of the land presumably having furnished the community with the funds needed to repay the principal, and perhaps a portion of the interest as weII. Although the document states that the aim of the transaction was the repayment of the community's debt, no hint is given as to how the debt was incurred, the exact amounts owed as principal and interest, and the person or institution to whom the debt was owed.</quote><bibl><ptr target="bib:WissemanChristie2009_01"/><citedRange>44</citedRange></bibl></cit>
The words I have quoted in bold require further consideration, as the text does not actually mention any religious community nor any meritorious gift, although both notions may be implied.</p>
<p n="2">The status expressed by the compound <foreign>savaḥ karamān</foreign> clearly stands in opposition to the new status expressed, in line 9, by the compound <foreign>savaḥ śīma</foreign>.</p>
</div>
```

- current display:
<img width="1006" alt="Capture d’écran 2020-11-22 à 13 19 38" src="https://user-images.githubusercontent.com/835603/99903548-66371f00-2cc5-11eb-91c2-c41d8de24842.png">

- the transformation does not yet yield the block quote I was hoping to get, in line with EGD §10.4.4
- `<hi rend="bold">` does not seem to implemented yet either

@danbalogh : could you formulate what display we expect here so that @ajaniak can implement it?

**Comment by danbalogh** [comment]
I have no set views on how block quotes should be displayed. I think that they should be shown as a separate HTML paragraph, set in at some distance from the left margin. I have not looked into the intricacies of how that display can be implemented given that a block quote in our system is part of a `<p>` element and will often have text belonging to that `<p>` both before and after the block quote. (This concern is why the I initially said in the EGD that a block quote should be on the same level as a `<p>` rather than inside one. Back then, I was told - I don't remember by whom - that it would be preferable to have them as part of a `<p>` and display would not be a problem.) So anyway, display as a block indented in every line. The contents of the `<bibl>` element should, I think be displayed in this case in parentheses, at the end of the citation. But again, whatever you decide on is acceptable to me.

**Comment by arlogriffiths** [comment]
OK, let me then make the following basic suggestion.

- current display

<img width="998" alt="Capture d’écran 2020-11-23 à 16 19 58" src="https://user-images.githubusercontent.com/835603/99980088-2301ac80-2da8-11eb-9355-6992e1e6f816.png">

- desired type of display

<img width="477" alt="Capture d’écran 2020-11-23 à 16 22 03" src="https://user-images.githubusercontent.com/835603/99980111-27c66080-2da8-11eb-958d-51cb9c6dfe3b.png">

@ajaniak : is that enough for you to work with?

**Comment by manufrancis** [comment]
Fine with me!

**Comment by ajaniak** [comment]
done, close the issue if you are satisfied. Nota that I had to change the CSS, so it can take until 2 hours for the current addition to work.

**Comment by arlogriffiths** [comment]
Yes, it looks good now. See screenshot attached. Thanks. Closing this issue.

<img width="1011" alt="Capture d’écran 2020-11-24 à 06 08 12" src="https://user-images.githubusercontent.com/835603/100051169-8547c500-2e1b-11eb-93a1-dfa06faff907.png">
