### ISSUE TITLE
generate error message is "bib:" is missing from <bibl><ptr target="bib:shortTitle"/></bibl>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#102]
@ajaniak : is it possible to set our schema in such a way as to make the file invalid if the encoder types `<bibl><ptr target="shortTitle"/></bibl>`, forgetting the crucial prefix `bib:`?

**Comment by ajaniak** [comment]
no it is not possible since the project doesn't have a schema

**Comment by arlogriffiths** [comment]
Can you explain to us why we don’t have a schema? Whether we could have one? What are the pros and cons?

I was under the impression that we did or at least that we could have one, and that we all agreed that we wanted one.

Your messages suggest that you have a different impression.

This should be clarified.


Le 23 nov. 2020 à 10:05, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



no it is not possible since the project doesn't have a schema

**Comment by ajaniak** [comment]
When I started working on a schema for DHARMA, I understood that the project would keep the Epidoc schema as reference and that a DHARMA schema wasn't needed. This is why the development has been suspended since this summer.
Manu added this topic for the next brainstorming session (December 17th), so that we can discuss it and make a decision.

#99 also related to schema

**Comment by manufrancis** [comment]
will be dealt with the implementation of the DHARMA schema

**Comment by ajaniak** [comment]
It has been already implemented in the DHARMA Schema this summer. I am still working on the new features that must be implemented before being able to use it.
