### ISSUE TITLE
<note> in Translation

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#105]
- example of code

```
<div type="translation" xml:lang="ndl" source="bib:Stutterheim1940_02">
<p n="1-2">Eere aan Çiwa! Heil! Çaka-jaren voorbijgegaan 807 (885 A.D.); Mei-Juni; de tiende dag van de lichte maandhelft; (dag van de zesdaagsche week:) Tunglai; (dag van de vijfdaagsche week:) Wagai; Donderdag.</p>
<p n="2-3">Dit is het tijdstip, waarop de Eerwaarde Leeraar Munīndra een ambts-<foreign>sawah</foreign> koopt te Parhyangan, ressorteerende onder Wurutunggal, welke <foreign>sawah</foreign> geheeten is <q>De Kooi</q>, tot een vrijgebied voor de Heilige Padewāharān<note>De juiste vertaling van deze uitdrukking is niet gemakkelijk te geven. Sanskrit <foreign>dewāhāra</foreign> beteekent zooveel als ambrozijn, goddelijke spijs. De Javaansche afleiding hiervan, <foreign>padewāharān</foreign>, zou dus kunnen beteekenen: plaats, waar de goddelijke spijzen (offers ?) worden aangeboden, neergelegd enz. Bedoeld is dan een gebouw, dat met de vereering der goden samenhing; of de geheele tempel bedoeld is, dan wel een afzonderlijke <foreign>balé</foreign>, is, bij gebrek aan verdere gegevens, niet uit te maken. Misschien is hier een huistempel bedoeld, wat de Baliërs <foreign>pamradjan</foreign> noemen.</note>.</p>
<p n="3-4">De koopsom is 1 <foreign>kāṭi</foreign> zilver, de geschenken aan de dorpsautoriteiten bedragen 3 <foreign>dhāraṇa</foreign> zilver. Er is echter een vordering der dorpsautoriteiten op een schuld van hem (tot een bedrag van) 7 <foreign>dhāraṇa</foreign>, welke mede als geschenk dient, alsmede 1 geit, 1 <foreign>pada</foreign> (rijst ?) (en) 4 <foreign>māṣa</foreign> zilver. Het totaal der werkelijke betaling in zilver is 1 <foreign>kāṭi</foreign>, 10 <foreign>dhāraṇa</foreign>, 4 <foreign>māṣa</foreign>; het doel van dit zilver is kwijting van de schuld aan het dorp Parhyangan.</p>
</div>
```

- NB, `<note>` is found at the end of the second `<p>`. Current display is:

<img width="997" alt="Capture d’écran 2020-11-22 à 17 30 56" src="https://user-images.githubusercontent.com/835603/99909384-80cebf80-2ce8-11eb-922a-297996b0b3da.png">

- we definitely need something more sophisticated than inserting the contents of `<note>` in parentheses at the location where the `<note>` is inserted

- suggestions for display?

**Comment by danbalogh** [comment]
Ideally, notes should in my opinion be displayed in the way they appear e.g. on Wikipedia: with a clickable note reference (not necessarily a numbered one, but if auto-numbering these is feasible then why not) that can take you to a point at the end of the HTML page where all notes appear sequentially, and with a clickable item at the beginning of the text of each note that links back to an anchor at the point where the note reference is shown.
I have assumed so far that implementing such a system has been left for later, so that Axelle can prioritise more urgent and less complex issues. If the time to implement fancy notes has come, I suggest the above. If it has not, I'm content to live with text in parentheses at the point where the note appears in the XML.

**Comment by arlogriffiths** [comment]
I endorse the proposal to adopt a layout for notes as on Wikipedia.

I hope it will be relatively easy for Axelle to implement.


Le 23 nov. 2020 à 09:20, Dániel Balogh <notifications@github.com<mailto:notifications@github.com>> a écrit :



Ideally, notes should in my opinion be displayed in the way they appear e.g. on Wikipedia: with a clickable note reference (not necessarily a numbered one, but if auto-numbering these is feasible then why not) that can take you to a point at the end of the HTML page where all notes appear sequentially, and with a clickable item at the beginning of the text of each note that links back to an anchor at the point where the note reference is shown.
I have assumed so far that implementing such a system has been left for later, so that Axelle can prioritise more urgent and less complex issues. If the time to implement fancy notes has come, I suggest the above. If it has not, I'm content to live with text in parentheses at the point where the note appears in the XML.

**Comment by arlogriffiths** [comment]
This seems to have been implemented and my first test results are satisfactory. Thanks! Shall we close this or keep it open to leave time for testing display of `<note>` in various contexts?

**Comment by danbalogh** [comment]
I find the implementation great, including the fact that the notes are grouped at the end of each div of the file rather than bunched together at the very end. I have two suggestions though.
One is, I assume, simple to implement and should definitely be done unless someone objects: the text of each note should appear in a separate paragraph if possible, not run together into a single long paragraph.
The second is just icing on the cake: it would be very nice if it would be also possible to display a floating tooltip with the text of the note when one points the mouse at the note anchor in the text. I believe this would need JavaScript to implement nicely and in a browser-independent way, so there is no need to bother with it at this stage, but if possible, it should eventually be done for the website.

**Comment by manufrancis** [comment]
Thanks, Axelle! Looks fine to me.
As for your suggestions, Dan, I would say, at first sight, that I favour the second one (floating tooltip), which renders, to my mind the first one then undesirable.

**Comment by danbalogh** [comment]
Just to be clear: Manu, I would definitely want to retain the endnote-style display of the notes. My suggestion of a floating tooltip was meant to augment that, not to replace it. Have a look at the notes on a Wikipedia page for an illustration of what I think is desirable.

**Comment by danbalogh** [comment]
@ajaniak : thanks, I now see that you've already implemented a `<br/>`  between each note item. I think they look great now.

**Comment by ajaniak** [comment]
@danbalogh , you are welcome. 
I used `<span>`element rather than a `<p>`. I can change it of course; but it will imply for me to redo all the CSS with several types of p to handle line spacing. Honestly, for such a display, I don't think it was worth it, especially with <span> doing the job. 

I am done adding the tooltip features as well. Please note that it requires the update of CSS code, it might take a few hours for the server to update the link and so for you to have the final result. I made a screenshot so you can have a preview until then. 

<img width="1075" alt="Capture d’écran 2020-12-01 à 15 53 46" src="https://user-images.githubusercontent.com/33328906/100756972-19062c00-33ee-11eb-9614-efdd5028c4c4.png">

Do you have other request regarding the matter?

**Comment by danbalogh** [comment]
Beautiful. As you say, I do not yet see this in a transformation of my own. If this works in all major browsers, then I am fully happy with it and I guess the PIs will be too.
