### ISSUE TITLE
<note> in <div type="bibliography">

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#108]
Dear all, 

Unlike stated in the EGD 10.4.1: "notes may be used in the apparatus, the translation and the commentary", I have around 100 files using `<note>` with the bibliography. This practice can be found in each task force and can't be qualified as minor. The subject has been started in the commentaries of the EGD and been moved here to have the possibility to have a better usage context. 

The scientific content of the `<note>` seems rather consistent and is mostly related to : 
- a change of numbering of the inscription by one author ( found in the lemma or in the bibliography)
- surrogates 
- if the bibliography reference has been read or traced by the encoder
- what is discussed or what is missing in the book

But encoding practices varie greatly. `<note>` can be found at as child element of `<p>`, `<bibl>`, `<citedRange>`, `<quote>` and sometimes as free text form such as the following code example, which of course lead to display issue.   
```<bibl>
 <ptr target="bib:Parmentier1912_01"/><citedRange unit="page">6</citedRange> Thap Muoi (Phong-nam, Sadec, Cochinchine). Conservée antérieure dans le Jardin du Gouvernement Général à Saigon. 10 linges. Cette pierre porte une inscription khmère relatant un don d’esclaves au dieu Śrī Amrātakeśvara (forme de Śiva).
 </bibl>
```
So we need to decide in which part we  allow it : in the lemma, in the `<listBibl>` or in both. 
How it should interact with other tags such as `<citedRange>`: 
- from within ```<citedRange unit="item">39 <note>Renamed 39-A, when edited by <bibl><ptr target="bib:SubrahmanyaAiyer1932_01"/></bibl> as he realized that more than one inscription was registered under number 39.</note></citedRange>```
- after ```<bibl n="BLR2">
            <ptr target="bib:Rice1905_02"/>
            <citedRange unit="part">Inscriptions in the Kolar district <supplied reason="subaudible">Kannaḍa script</supplied></citedRange>
            <citedRange unit="part">49</citedRange>
            <note>I.e. EC 10, Mulbāgal Taluk, n° 211</note>
</bibl>```

or if the `<note>` is only accept on its own in the lemma like ```<p>[...]<note>Scans of these impressions were obtained by Emmanuel Francis from the Edinburgh University Library, the Bibliothèque nationale de France and the British Museum.</note></p>```

Finally, if the `<note>` is used the same encoding as in other parts of the edition such as `<foreign>` or bibliographical reference ```<note>Kielhorn (<bibl rend="omitname"><ptr target="bib:Kielhorn1900-1901_01"/><citedRange>1</citedRange></bibl>) says Fleet’s revised edition was also published in ASWI III p129ff. Not traced. Not in ASWI Reports 3 or Memoranda 3, and I could not find vol 3 of the main ASWI series, nor even any further information about it such as full title or publication year.</note>```

Let me know if you need the full examples to have a better understanding of the encoding context.

Best,

**Comment by danbalogh** [comment]
As usual, I would like to keep things simple. Easier to encode properly and easier to display that way. How about this:

1. permit note at any point in the epigraphic lemma, including within child elements of the `<p>` containing the lemma, where necessary (e.g. a `<quote>` within that paragraph).
2. in the structured bibliography, permit `<note>` only as the last child element of `<bibl>` and nowhere else, i.e. not as a child of `<citedRange>`, nor followed by another `<citedRange>`. The text of notes may need some disambiguation in this case, so that if a note applies to a certain detail of the citation, as in the examples quoted above by Axelle, then the note will need to say what detail it applies to, instead of being attached directly to that detail.
3. outside the bibliography division, I think using `<note>` inside a `<bibl>` should be prohibited altogether; if one needs to add a note concerning a citation, then that note can go outside, right after the `</bibl>` tag. (This point has not been raised before, but I think we should settle it while discussing this issue.)
4. I'm not sure I understand Axelle's last question/point above, but I think all kinds of markup should be permitted within a `<note>`, including edition markup such as `<supplied>` and `<unclear>` as well as generic markup covered in EGD §10, with the sole exception that `<note>` within `<note>` should be prohibited. And all of these should be displayed in a `<note>` in the same way as outside a `<note>`.

**Comment by arlogriffiths** [comment]
I agree with Dan's proposal on all points, and think my encoding practice so far is generally in line with what he proposes.

Here's an example I have just found back, from an entry in a `<listBibl type="secondary">`:

`<bibl><ptr target="bib:Eade+Gislen2000_01"/><citedRange unit="page">133</citedRange><note>The book does not seem to contain a discussion of this inscription's date.</note></bibl>`

The point being that the book pretends to discuss all dates in the given corpus, but actually often does no more than reference a given dated inscription.

**Comment by ajaniak** [comment]
I am fine with this approach as well.

**Comment by manufrancis** [comment]
So do I.

Emmanuel FRANCIS <http://ceias.ehess.fr/index.php?1725>
Chargé de recherche CNRS, Centre d'études de l'Inde et de l'Asie du Sud
<http://ceias.ehess.fr/> (UMR 8564, EHESS-CNRS, Paris)
Online CV HAL <https://cv.archives-ouvertes.fr/emmanuel-francis>
DHARMA <https://dharma.hypotheses.org/> Project
<https://dharma.hypotheses.org/> (ERC synergy grant 2018)
TST Project <https://tst.hypotheses.org/> (FRAL 2018, ANR & DFG)
Regionalism & Cosmopolitism: South India <http://rcsi.hypotheses.org/>
Associate member, Centre for the Study of Manuscript Culture
<http://www.manuscript-cultures.uni-hamburg.de/index_e.html>

**Comment by danbalogh** [comment]
Thanks, everyone. In that case I'll go ahead with specifying this in the EGD. If it turns out we need more clarification/specificity, I'll put that back here. Axelle, please do the same, i.e. if while setting this up in the schema you find that we need to settle on some more detail, let us know here.

**Comment by danbalogh** [comment]
I've written this up under §10.4.1 of the EGD; feel free to have a look and propose alterations where needed. Please do not approve any edit suggestions I made there (or that you or others make) - I'll approve them when I have made the same changes in the master DOCX version of the guide, but I need them highlighted until then.
I'll also add some of this detail and a cross-reference to the section on bibliography; this has not yet been done.

While writing this up, I've made explicit something that has been implicitly present in the EGD and my mind all the time: in the apparatus, `<note>` may only appear as the last child of `<app`, i.e. not at a point where it is followed by a `<lem>`. I hope you all agree to that; it makes our apparatuses neater and easier to comprehend, and it is analogous to how we are allowing notes in the structured bibliography only as the last child of `<bibl>`.

**Comment by arlogriffiths** [comment]
All clear from my side, but in EGD 10.4.1 I suggest removing the newly added line "– when adding notes" because it seems to hang in mid air without adding anything useful.

**Comment by manufrancis** [comment]
Fine with me too!
Thanks Axelle and Dan for haveing sorted this issue out.

**Comment by danbalogh** [comment]
@arlogriffiths please clarify. I can't find what you refer to. The only line beginning with "when adding notes" that I can see is in §9.2.4 and is not newly added, nor is it redundant.

**Comment by arlogriffiths** [comment]
<img width="584" alt="Capture d’écran 2021-01-21 à 13 30 15" src="https://user-images.githubusercontent.com/835603/105351475-ed811000-5bec-11eb-8b88-d5fb6c32024e.png">

**Comment by danbalogh** [comment]
Strange. Are you sure you are not looking at an earlier snapshot? This may be some error in Google Docs. What I see is:
![image](https://user-images.githubusercontent.com/31253927/105351926-84e66300-5bed-11eb-93d0-36b8d3b0d77e.png)

**Comment by arlogriffiths** [comment]
problem solved.

@ajaniak : I think you can close this when you're ready on your side.

**Comment by ajaniak** [comment]
I have added necessary parts in the schema. Closing this issue. Thanks
