### ISSUE TITLE
<hi> within <choice>

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#110]
In 
https://github.com/erc-dharma/tfa-pallava-epigraphy/blob/master/texts/xml/DHARMA_INSPallava00020.xml
line 166, I have been compelled to use `<hi>` within `<choice>` against Epidoc.
Shall we allow, against Epidoc, `<hi>` within `<choice>`?

**Comment by danbalogh** [comment]
Tough one. One thing I am quite sure of is that the `<hi>` should be inside the `<unclear>` element in this case, not the other way round. But that of course does not solve the problem. I see two ways to go ahead:
1. allow `<hi>`  inside `<unclear>` , preferably not against EpiDoc, but proposing this rule change to the EpiDoc community; or
2. change our encoding method and instead of `<hi rend="grantha">` , henceforth use `<g type="grantha">` to wrap each grantha character separately. For longer stretches of grantha text, we may need to continue permitting `<hi rend="grantha">` , since one `<g>` tag should not, in my opinion, contain more than the transliteration of a single akṣara. So transition to this system may not be possible to automate on the already encoded files.

@ajaniak : do you have any other suggestions? What is your opinion of the above alternatives?
@manufrancis : is this encoding really necessary? Would you consider it an inferior solution to put your vote down on one reading or the other, and mention in an apparatus note that what you read in the edition as a grantha śa could also be read as a Tamil ca?

**Comment by ajaniak** [comment]
@danbalogh, you could ask for the Epidoc to change their guidelines to allow `<hi>` inside `<unclear>`. Such a solution would be the easier to implement, even though it will be a nightmare to add in DHARMA tree model and codes. 

I am not sure regarding `<g>` element. It will be bothersome to encode each character, but I am not sure it really matches the use if this element as describe by Epidoc which uses it for symbols and non-standard characters regarding unicode. Grantha is rather as a second script (at least to my understanding) so I wouldn't say it is non-standard. 

As shortcut, we could use the attribute `@rend="grantha"` on `<unclear>`, allowing it only if the grantha and unclear are a strict match.

**Comment by danbalogh** [comment]
Adding `@rend="grantha"` to `<unclear>` sounds good to me because it involves a minimum of fuss, but I guess it's not very good practice. I'll ask about `<hi>` in `<unclear>` on MARKUP, just in case.

**Comment by manufrancis** [comment]
Thanks, Dan, for asking MARKUP!

As for your suggestion:

> "@manufrancis : is this encoding really necessary? Would you consider it an inferior solution to put your vote down on one reading or the other, and mention in an apparatus note that what you read in the edition as a grantha śa could also be read as a Tamil ca?"

Yes, indeed, I was thinking about such a solution here. But I foresee that in other instances, having the encoding option could be useful.

**Comment by danbalogh** [comment]
As both of you may have seen on Markup, I've received some input, mainly from Gabby Bodard, on this issue. Here are the main points from my perspective.

1. It seems to me that the EpiDoc community is dead set on prohibiting anything but `<g>` inside `<unclear>`. Their reasoning is that by the EpiDoc definition of `<unclear>` (which is narrower than the TEI definition), this element may only contain character data, and anything beyond characters and `<g>` is not "character data" but "editorial interpretation". I don't really agree with that and remain convinced that EpiDoc's own (not fully TEI-compliant) use of `<hi>` in fact concerns character data, not editorial interpretation, in at least some cases. However, even if I could convince the EpiDoc folks about that, there remains the matter that for anyone who may try to utilise our files five or fifteen years into the future may not be as familiar with our EGD as we all are, and find it hard to figure out what some of our idiosyncratic encoding solutions stand for. So, in a nutshell, I propose that we go with the mainstream and forget about permitting `<hi>` in unclear.
2. For dealing with the immediate problem of this thread, Gabby has suggested using `<app type="alternative">, an encoding method that does not seem to be documented at all, but that nonetheless seems to have gained some acceptance in the EpiDoc community, since it has been used by at least two different projects. Both examples of its use that I know of are inline, i.e. not in a separate apparatus division but right there in the text. I'm not sure we should complicate our already complex encoding with adding an option for inline apparatus entries, but if we agree to use this only for ambiguities pertaining to the script, then it may be possible to implement its display without increasing the complexity of the transformation too much. The display I am thinking of would be exactly identical to that of choice with unclear, so that e.g. an inline `<app type="alt"><lem>ABC</lem><rdg>DEF</rdg></app>` would appear just like `<choice><unclear>ABC</unclear><unclear>DEF</unclear></choice>`, with the only difference that ABC and DEF can contain tags such as `<hi>` in the former even though they cannot in the latter. If that is too complex to implement, then I think it should also be possible for us to introduce a new type of `<rdg>` into our external apparatuses, such as `@type="alternative"` - which would then be displayed in the external apparatus, not as a reading by a different editor but as an alternative reading. @manufrancis and @ajaniak , can you think about, and perhaps discuss, which of these would be more desirable and more practicable to implement in order to create a solution for Manu's problem?
3. Finally, regardless of what decision we make about number 2 above, perhaps we should reconsider our use of `<hi>` for script. EpiDoc folks seem to agree we ought to use `@xml:lang` for script changes even when a language change is not involved. Thus, according to Gabby, `<seg xml:lang="Gran">śa</seg>` would be "more conventional EpiDoc" than `<hi rend="Grantha">śa</hi>`. (Or `@xml:lang="tam-Gran"`, but according to his line of thought the language part is inherited from the rest of the text, so encoding the script suffix here would be sufficient.) I'm willing to accept this line of thinking, mainly for the same reason as above, namely that our code may be more intuitively intelligible to others this way. However, it raises again a basic problem that we discussed once in the early days, but I don't have clear memories of the discussion. That is, since all our editions are transliterated, we either use no script suffix or use "-Latn" to indicate that our texts are transliterated. In other words, our suffixes specify the script of the edition, not the script of the original. A second associated problem is that we use ISO-compliant language and script codes, whereas I suppose "-Gran" is not such. If we want to change our method of encoding script changes to xml:lang on seg (or a pre-existing container where available), then we would have to stipulate that any script suffixes would also indicate the script of the original. That is to say, we would then not use -Latn anywhere, and simply declare that a language code without a script code means "a language written in the default script appropriate to the location of the inscription in space and time **and presented here in Romanised transliteration**" - where only the bit in bold is new, and the rest we already have. We should discuss at some time, not urgently, this issue number 3, also involving @arlogriffiths . If we don't want to reconsider our usage of `@xml:lang`, then it may still be possible for us to use `@rend` on `<seg>` (instead of on `<hi>`) to make our code more EpiDoc compliant.

**Comment by manufrancis** [comment]
Thanks, Dan! Will discuss these issues with Axelle when she we will back from vacation in early March.

**Comment by danbalogh** [comment]
Prompted to rethink script encoding by this thread, @ajaniak and @arlogriffiths have proposed a new method for encoding the original script. I agree with the proposal in most details. The method is outlined in EGD 7.5.5, with some ongoing discussion in comments. (The section number may change in the future.)

But this does not yet solve the original problem. @manufrancis and @ajaniak , have you come to any decision about how you would like to handle cases like this?
If not, I have a proposal. I'm not very eager to introduce it, since I am not aware of anything similar being in use, but it seems to be correct TEI. It would involve two `<seg>` elements within a `<choice>`, e.g. like this

`<choice><seg corresp="class:36768 maturity:83213">ś</seg><seg corresp="class:38776 maturity:83213">c</seg></choice>`

Where the funny numbers refer to our OpenTheso vocabulary items as outlined in the revised EGD section 7.5.5 (the first one meaning mediaeval Grantha, the second meaning mediaeval Tamil), and where I am proposing to use `@rendition` instead of `@corresp` (which is a detail irrelevant to the subject of this thread).

This method is not sanctioned by EpiDoc, but nor is it prevented by the EpiDoc or DHARMA schema (except that the DHARMA schema permits only “pun” as a value of `@rend` on `<seg>`, but that can be changed). TEI explicitly permits `<seg>` in `<choice>`, but probably not exactly for this purpose. Nonetheless, we could perhaps co-opt this, only for the cases where there is a script uncertainty regarding a character or string of characters
This would also avoid the use of unclear for something that is clearly readable (Gabby on MARKUP: [unclear], in EpiDoc, uniquely records incomplete, damaged, or illegibly executed characters, not per se the editor's uncertainty in interpretation of them).

Everyone is welcome to give their opinions on this suggestion. Most especially, I need opinions from @manufrancis and @ajaniak .

**Comment by danbalogh** [comment]
This too has never been brought to a close, although I'm happy to forget about it if @manufrancis and others can live with the lack of an encoding solution.

**Comment by manufrancis** [comment]
Thanks Dan, yes, let us forget about about this.
