### ISSUE TITLE
tooltip for bibliogfraphy

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#115]
Sorry, this is probably in whole or partial overlap with other open issues...

In scenario 1 (screenshot)

<img width="1006" alt="Capture d’écran 2021-02-09 à 08 59 40" src="https://user-images.githubusercontent.com/835603/107333221-746f2d00-6ab5-11eb-8ebe-fd6d1c94bd3c.png">

I think no tooltip is needed at all, as all and more of the same bibliographic information is shown in the html display itself.

In scenario 2 (screenshot)

<img width="1010" alt="Capture d’écran 2021-02-09 à 08 59 51" src="https://user-images.githubusercontent.com/835603/107333363-aa141600-6ab5-11eb-8904-d4516f91ae34.png">

I would like the tooltip to appear only if the mouse is moved over the journal abbreviation, here _BB_, to appear at _BB_ and not in the left margin, and to display the full tile of the journal in question. In any case, at the moment the tooltip seems to be affected by a bug, as it isn't displaying anything.

Both examples are taken from the html of DHARMA_INSIDENKHampran.xml.

**Comment by manufrancis** [comment]
This implementation of the tooltip is what Axelle has been able to develop so far.
The problem is that there is no possibility to have the tooltip only on the journal abbreviation in the div bibliography.

Considering the time spent by Axelle on trying to solve this issue whereas she has other more vital tasks, maybe we should reconsider our consensus, that is, not having the journals' names abbreviated in the bibliography (I was not in favour of this, nor was Daniel, if I remember well) and reconsidering the use of @rend="journal" where an abbreviation is needed.

**Comment by arlogriffiths** [comment]
so no abbreviations of any journal titles and hence no tooltip at all in bibliography: that is also fine with me

an alternative could still be to let the abbreviations appear as hyperlinks to a table of correspondence between abberviated and full titles.




Le 10 févr. 2021 à 17:18, manufrancis <notifications@github.com<mailto:notifications@github.com>> a écrit :



This implementation of the tooltip is what Axelle has been able to develop so far.
The problem is that there is no possibility to have the tooltip only on the journal abbreviation in the div bibliography.

Considering the time spent by Axelle on trying to solve this issue whereas she has other more vital tasks, maybe we should reconsider our consensus, that is, not having the journals' names abbreviated in the bibliography (I was not in favour of this, nor was Daniel, if I remember well) and reconsidering the use of @rend<https://github.com/rend>="journal" where an abbreviation is needed.

**Comment by ajaniak** [comment]
The current system doesn't allow me to have such a level of control regarding the bibliography. If I change it, we won't be able the use the CSL and I would probably have to handle manually the output, so it will take time and less perfect than the CSL. 
However, note that the situation inside the DB itself won't match the current system since we won't use the API Zotero, but data inside the DB itself.
