### ISSUE TITLE
"document as been marked unavailable"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#121]
Dear @ajaniak — I have this problem again:

<img width="1410" alt="Capture d’écran 2021-03-11 à 08 21 19" src="https://user-images.githubusercontent.com/835603/110752313-67289800-8245-11eb-923c-99899327459e.png">

Yesterday I noticed that @salomepichon had it too.

Can the root cause of the problem be determined and resolved?

**Comment by ajaniak** [comment]
Does it happen always in the same context? This issue seems to be connected with an internet connexion and happens only with people form the EFEO.

**Comment by danbalogh** [comment]
It has happened to me too, I think on last Thursday (i.e. probably on the same day when Arlo made the above comment). I assumed it was temporary and did not pay attention to the details. It has not occurred when I was working from home. I'll check if it recurs when I'm next in my office.

**Comment by arlogriffiths** [comment]
Is the following error connected to the problem reported above?

<img width="1476" alt="Capture d’écran 2021-03-30 à 14 29 08" src="https://user-images.githubusercontent.com/835603/112988672-61e3ac80-9164-11eb-9b43-4a05736ba73c.png">

**Comment by ajaniak** [comment]
We don't use gitcdn for validation purposes

**Comment by arlogriffiths** [comment]
Dear Axelle — I didn't really understand your response. If you mean to imply that I and the other team members who are getting this error message should not try to "use gitcdn for validation purposes", then please understand that we haven't (consciously) tried to do any such thing. I don't even know what gitcdn is. **Could you please help resolve the issue?**

**Comment by ajaniak** [comment]
Can you check you are up-to-date for all your project-documentation files? We have migrate to another serveur service several weeks ago. From gitcdn.link then to gitcnd.xyz and we are now using cdn.jsdelivr.net because of security features with cloudflare.

Otherwise, the `I/O error reported by XML parser processing` is a Saxon issue regarding an import statement. If you have checked your java and the host access of your Oxygen, it is probably an issue with your internet connexion or your proxy configuration since it seems to indicate that your computer isn't able to retrieve validation or transformation parts stored on third-service.

**Comment by arlogriffiths** [comment]
As for me, we have together ensured that Java is properly installed and that Oxygen has the proper settings for host access. But does it need to be checked again after the recent change of service? I don't see what problem there coulkd be with my internet connectio. So should we check the issue of "proxy configuration"? How to check this?

**Comment by ajaniak** [comment]
Nope, if java is installed and Oxygen has the proper settings for host access, no need to check again. Changing services don't required any new set up. 
Go to preferences, Network, then advanced button at the bottom. Proxies tab. In hteory, the by default settting on Mac is the "Use Passive FTP mode" at the botton rather than http or https in the list and the bypasse is "*.local, 169.254/16". 

I guess you could check your internet connexion. Option on your keyboard, then go to the wifi symbol in the toolbar and launch a network diagnostic. 

Anyway, like I said previously I can't debug with so few information. Maybe check the Window > Show View > Information and see if an error is provided in the pane.
