### ISSUE TITLE
Cheatsheet/Transformation scenario

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#13]
Propositions of display (reflecting exchanges with Arlo):

`<orig>abc</>`  --->  ¡abc!
`<sic>abc</>`    --->  ¿abc?   (NB: Arlo, you suggested ¡¿abc!?. I find ¿abc? lighter)

`<reg>abc</>`    --->  ⟨abc⟩
`<corr>abc</>`  --->  ⟨abc⟩  

`<supplied reason="omitted">abc</>`   --->   ⟨abc⟩
`<surplus>abc</>`                                  --->   ⟨⟨abc⟩⟩

Thus:
`<choice><sic>X</sic><corr>Y</corr></choice>`     --->   ¿X?⟨Y⟩
`<choice><orig>X</orig><reg>Y</reg></choice>`   --->   ¡X!⟨Y⟩
((The idea behind ¿X?⟨Y⟩ and  ¡X!⟨Y⟩ is that the brackets for `<corr>` and `<reg>` should be the same as those we would use for `<gap reason="omitted">`))

**Comment by ajaniak** [comment]
What about pattern such as `<reg><orig>u</orig><corr>i</corr></reg>`?

**Comment by danbalogh** [comment]
All of the above looks fine to me, except that {abc} would be better for `<surplus>`. Are we planning to use {} for a different purpose? If not, then using it for suppression would be conformant with the Leiden conventions and in my opinion simpler to read than ⟨⟨abc⟩⟩.

Axelle: the combination `<reg><orig>u</orig><corr>i</corr></reg`>cannot occur, since neither `<reg>` nor `<corr>`  will ever be used outside a `<choice>`  that includes the original text, and neither `<orig>` nor `<corr>` will ever be used inside a `<reg>`.

Did your question concern cases where a normalisation is added on top of a correction, as in
`<orig>mahār<choice><sic>a</sic><corr>ā</corr></choice>jñaḥ</orig>` ?
I see no problem with displaying these by the above rules as
¿mahār¡a!⟨ā⟩jñaḥ?
or, with full normalisation instead of just flagging:
`<choice><orig>mahār<choice><sic>a</sic><corr>ā</corr></choice>jñaḥ</orig><reg>mahārājasya</reg></choice>` ?
displayable as
¿mahār¡a!⟨ā⟩jñaḥ?⟨mahārājasya⟩
The latter may be a bit ambiguous, with two different uses of ⟨⟩, but I think we can live with that given that correction within a normalised bit will be very rare.
Manu, Arlo?

**Comment by AnneSchmiedchen** [comment]
I fully agree with Dániel's comment:
"All of the above looks fine to me, except that {abc} would be better for <surplus>. Are we planning to use {} for a different purpose? If not, then using it for suppression would be conformant with the Leiden conventions and in my opinion simpler to read than ⟨⟨abc⟩⟩."

I am also very much in favour of the use of {}.

**Comment by ajaniak** [comment]
`<reg><orig>u</orig><corr>i</corr></reg` happens in several files...

**Comment by manufrancis** [comment]
To summarise:

`<orig>abc</>`     ---> ¡abc!
`<sic>abc</>`       ---> ¿abc? 

`<reg>abc</>`      ---> ⟨abc⟩
`<corr>abc</>`     ---> ⟨abc⟩

`<supplied reason="omitted">abc</>`    ---> ⟨abc⟩
`<surplus>abc</>`                                    ---> {abc}

I was thinking of {...} for `<g type="symbol" subtype="finalGomutra"/>` ---> {finalGomutra}
Let thus duplicate it, thus
`<g type="symbol" subtype="finalGomutra"/>` ---> {{finalGomutra}}

As for
`<orig>mahār<choice><sic>a</sic><corr>ā</corr></choice>jñaḥ</orig>`
as per the rules above, it should be
¡mahār¿a?⟨ā⟩jñaḥ!
Not
¿mahār¡a!⟨ā⟩jñaḥ?
(I prefer this to full normalisation, which however we can allow)
(and in any case, using `<orig>` in this case seems to me redundant)

As for
`<reg><orig>u</orig><corr>i</corr></reg>`
could you, Axelle, identify the culprit and inform his/her PI?

**Comment by arlogriffiths** [comment]
The advantage of Manu's/my first proposal 
`<supplied reason="omitted">abc</>` ---> ⟨abc⟩
`<surplus>abc</>` ---> ⟨⟨abc⟩⟩
would have been consistency with the conventions used in EIAD, which in turn were rather heavily influence by the (German) buddhologists/gandharologists who were initially involved in EIAD.

But I can live with Manu's summary and use of
`<surplus>abc</>` ---> {abc}

Instead of Manu's proposal
`<g type="symbol" subtype="finalGomutra"/>` ---> {{finalGomutra}}
I suggest something evocative of the fact that finalGomutra represents a symbol (σύμβολον), so I can imagine solutions like these:
`<g type="symbol" subtype="finalGomutra"/>` ---> «finalGomutra»
`<g type="symbol" subtype="finalGomutra"/>` ---> σfinalGomutraς
Or no enclosing signs at all, and simply a special color, or underlining, or other such special formating on the @subtype.

**Comment by arlogriffiths** [comment]
sorry, one more thing, we will also need conventions for `<del>abc</del>` and `<add>abc</add>`. this is what I would propose to displayed with {abc}.

So summary of my suggestions:

`<unclear>abc</unclear>` ---> (abc)
`<supplied reason="lost">abc</unclear>` ---> [abc]
`<supplied reason="omitted">abc</unclear>` ---> ⟨abc⟩
`<add>abc</add>` ---> ⟨⟨abc⟩⟩
`<surplus>abc</surplus>` ---> {abc}
`<del>abc</del>` ---> {{abc}}

The logic of the last two choices is that scribal invertention is marked doubly, while the corresponding editorial intervention is marked singly.

What brackets will we place around `<gap>`?

**Comment by danbalogh** [comment]
Axelle: let me know if I can help figure out what the encoder(s) intended by `<reg><orig>u</orig><corr>i</corr></reg>` but of course it's also fine if it stays between you, them and their PIs. My guess is they meant `<choice><orig>u</orig><reg>i</reg></choice>`.
Manu, indeed, I mixed up question marks and exclamation marks in my example; thanks for the correction.
Arlo: for symbol, I would propose either ((finalGomutra)) [following Krummrey-Panciera] or *finalGomutra*  [following Leiden+], but I'm also OK with «finalGomutra». I think using sigmas as markup is confusing.
I endorse your suggestions for displaying scribal alteration.
I very strongly suggest using [] for lacunae, which would be in perfect harmony with using the same for restoration.

**Comment by arlogriffiths** [comment]
So I summarize my proposals after the day's discussion so far:

- `<g type="symbol" subtype="abc"/>` ---> _abc_
- `<unclear>abc</unclear>` ---> (abc)
- `<supplied reason="lost">abc</supplied>` ---> [abc]
- `<gap reason="lost"/>` ---> [...] 
      **(we still need to discuss what comes inside [...] depending on the case)**
- `<supplied reason="omitted">abc</supplied>` ---> ⟨abc⟩
- `<add>abc</add>` ---> ⟨⟨abc⟩⟩
- `<surplus>abc</surplus>` ---> {abc}
- `<del>abc</del>` ---> {{abc}}
The logic of the last pair of choices is that scribal intervention is marked doubly, while the corresponding editorial intervention is marked singly.

- `<orig>abc<orig/>` ---> ¡abc!
- `<sic>abc<orig/>` ---> ¿abc?
- `<reg>abc<orig/>` ---> ⟨abc⟩
- `<corr>abc<orig/>` ---> ⟨abc⟩
- `<choice><sic>X</sic><corr>Y</corr></choice>` ---> ¿X?⟨Y⟩
- `<choice><orig>X</orig><reg>Y</reg></choice>` ---> ¡X!⟨Y⟩
The idea behind ¿X?⟨Y⟩ and ¡X!⟨Y⟩ is that the brackets for `<corr>` and `<reg>` should be the same as those we would use for `<gap reason="omitted">`.

@manufrancis : could you add your points about use of colors?

**Comment by arlogriffiths** [comment]
I see now that it was @danbalogh who proposed:

`<orig>` magenta
`<sic>` red
`<reg>` blue
`<corr>` green

Maybe @danbalogh or @manufrancis can propose a new (final?) summary that integrates the colors?

**Comment by danbalogh** [comment]
Would it not be better to revert to using the cheatsheet Gdoc for instead of creating ever new, longer and longer summaries? We can still do the discussion here if comments in the gdoc don't do the job well enough.
Nonetheless, here is Arlo's summary with colours.

- `<g type="symbol" subtype="abc"/>` ---> _abc_ (plus colour? maroon? teal?)
      **DB: are you sure italics are sufficient? what if someone copies and pastes from our display and loses the formatting? I urge adding something around the symbol subtype**
- `<unclear>abc</unclear>` ---> (abc) (how about adding colour? grey?)
- `<supplied reason="lost">abc</supplied>` ---> [abc] (how about adding colour? grey too?)
- `<gap reason="lost"/>` ---> [...] (add colour grey?)
      **we still need to discuss what comes inside [...] depending on the case**
- `<supplied reason="omitted">abc</supplied>` ---> ⟨abc⟩ (add colour green?)
- `<add>abc</add>` ---> ⟨⟨abc⟩⟩ (no colour)
- `<surplus>abc</surplus>` ---> {abc} (add colour red?)
- `<del>abc</del>` ---> {{abc}} (no colour)
The logic of the last pair of choices is that scribal intervention is marked doubly, while the corresponding editorial intervention is marked singly.

- `<orig>abc<orig/>` ---> ¡abc! (colour magenta)
- `<sic>abc<orig/>` ---> ¿abc? (colour red)
- `<reg>abc<orig/>` ---> ⟨abc⟩ (colour blue)
- `<corr>abc<orig/>` ---> ⟨abc⟩ (colour green)
- `<choice><sic>X</sic><corr>Y</corr></choice>` ---> ¿X?⟨Y⟩ (colours as above)
- `<choice><orig>X</orig><reg>Y</reg></choice>` ---> ¡X!⟨Y⟩ (colours as above)
The idea behind ¿X?⟨Y⟩ and ¡X!⟨Y⟩ is that the brackets for `<corr>` and `<reg>` should be the same as those we would use for `<gap reason="omitted">`.

**Comment by manufrancis** [comment]
I close this issue, will update the cheatsheet googledoc with what is now stable in our transformation and will create further github issues with the points still to be discussed (which will, once settled, be added in cheatsheet googledoc).
