### ISSUE TITLE
availability of <list>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#150]
@ajaniak — is there any particular reason why "List can only be used inside the edition or the translation part of your file" (quoted from an indication that Oxygen is giving me)?

Why not in `<handDesc>`,`<div type="commentary">`, etc.?

**Comment by ajaniak** [comment]
I have forgotten to write the commentary in the error message, anyway the code allows the use of `list` in the commentary. I have corrected it. 
About the use of `list`, it is the rules stated in the EGD in §10.2.2 : "should you need to format some text as a structured list, the following markup  may be used in a commentary or in a translation (but not in any other section of your document)". The possibility to make it available in the edition was a request made at a later stage, I think.

**Comment by arlogriffiths** [comment]
Thanks. 

So this becomes a question for you and @danbalogh : are there any strong reasons not to permit use of `<list>` elsewhere in our files? For instance in writing up a list of palaeographic features of an inscription, in `<handDesc>`, having access to `<list>` would seem quite convenient to me.

@ajaniak — I am wondering, now that I think about it, why `<list>` should be allowed in the edition. Do we have any files where this option has actually been used?

**Comment by danbalogh** [comment]
I do not recall why we decided to permit lists only in the commentary or translation. I have some vague recollection of discussing lists in the edition with you (Arlo and probably but not certainly also Axelle) and, probably at some point after that discussion, I have in fact used `<list>` in an edition (tfb-vengicalukya-epigraphy\xml-provisional\DHARMA_INSVengiCalukya00069.xml) for a long list of donees. I also remember wanting to go back to other, previously encoded long lists of donees and format them likewise. But I must have forgotten to update the EGD with that.

Is it your current opinion that lists should be permitted at any place where free text is permitted? I am happy to agree with that, with the minor constraing that it should be permitted anywhere a `<p>` is permitted. Since we're already asking for `<list>` to be wrapped in `<p>`, this is quite straightforward, and it would exclude the use of lists e.g. in `<note>` elements (including the apparatus), where it might wreak havoc with display rendering, but it would permit it in e.g. `<handNote>`.
Or if you, Arlo, now think that lists should not be used in an edition, I'm also OK with that and can remove the markup from that one file.

Let me know what the verdict is, and I'll update the EGD.

**Comment by arlogriffiths** [comment]
Yes, I would like `<list>` to be made available anywhere free-text is permitted, notably in `<handNote>`.

I am not very enthusiastic about use of this element in editions. At least I would myself probably tend to apply the list structure in a translation and leave the edition less structured. But I can live with allowing use of `<list>` in the edition by anybody who finds it necessary.

**Comment by danbalogh** [comment]
@arlogriffiths , lists in the edition would be sort of akin to stanzas and could always be suppressed in display.

That said, I am also not very enthusiastic about permitting them; in spite of their utility in particular cases (e.g. donee lists), they disrupt the neat setup we now have with prose containers and verse containers and no nested containers anywhere.

So all in all, I suggest we forget about lists in the edition, for the time being at least. I've remove the list from the single edition where I have used it.

That still leaves your original question. It now seems to me that I was inattentive back then and wrote about `<handNote>` where you were concerned with `<handDesc>`.

I suggest we keep the constraint that `<list>` must always be within a `<p>`, but relax the constraint that it can only be used in the translation or commentary by adding that it can also be used in the TEI header where a `<p>` element is permitted, in particular, the Hand Description.

Do you, @arlogriffiths , agree with that?
@ajaniak , does this sound OK to you? Are there any reasons, technical or conventional, why we should not do this?

If all OK, then we'll need the following actions:
@ajaniak to modify the schema (and the error message associated with using a list element in other contexts)
@danbalogh to modify the EGD §10.2.2

**Comment by ajaniak** [comment]
I am ok with this solution. I don't foresee any issue with it. I have just pushed the new version of the schema.

**Comment by arlogriffiths** [comment]
I also agree!

**Comment by danbalogh** [comment]
Thanks. I'll close this when I've updated the guide.
