### ISSUE TITLE
xml comments becoming spaces in display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#151]
@ajaniak : is it possible to change our transformation code so as to avoid xml comments showing up as spaces in display?

example:
- source: `Iṁ sovaṁ<!-- this really looks more like sovi -->-sovaṁ<g type="ddandaHooked">.</g>`
- display: 
<img width="141" alt="Capture d’écran 2021-10-28 à 07 30 21" src="https://user-images.githubusercontent.com/835603/139192863-1063f626-e631-4189-9794-9273a0e469ef.png">

or is it more efficient to change the placement of comments in my file?

**Comment by ajaniak** [comment]
You have added a node comment inside a textual node. So a space is added to avoid linking the two nodes together. The code won't be stable enough to deal it such cases consistently: you will nearly always have a space in such circonstances. 
I would recommend moving your commentary at the end of a string a avoid breaking its node.

**Comment by arlogriffiths** [comment]
thanks. could you explain what "node" means?

would `Iṁ sovaṁ-sovaṁ<!-- the first one really looks more like sovi --><g type="ddandaHooked">.</g>` be sufficient to avoid the problem, or must I move the comment further away from the relevant string of text?

**Comment by ajaniak** [comment]
A node is the primary data for XML document object model. The main node in this context is `<p>` which contains a succession of textual node and elements node. The structure in Poh isn't enough to overcome the basic parsing rules that will add a space with mixed content inside a node.  

No, it will also add a space. I would add it before the full string `Iṁ <!-- the first one really looks more like sovi -->sovaṁ-sovaṁ<g type="ddandaHooked">.</g>` or totally after it `Iṁ sovaṁ-sovaṁ<g type="ddandaHooked">.</g><!-- the first one really looks more like sovi -->` since adding it before the `<g>` will produce a space as well.
