### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#157]
@ajaniak : I only get the following error messages in Atom, not in Oxygen:

<img width="1470" alt="Capture d’écran 2021-12-20 à 11 14 59" src="https://user-images.githubusercontent.com/835603/146751917-3bd7323c-06ec-40c2-bba8-ae199a198587.png">

should I ignore them?

**Comment by ajaniak** [comment]
Yes, the issue being in the Epidoc schema, I can't do anything about it.

**Comment by arlogriffiths** [comment]
please clarify: 
- is this a glitch that should be reported to MARKUP? 
- why is it that Atom protests while Oxygen doesn't?

**Comment by ajaniak** [comment]
No it shouldn't be reported because it is not a mistake in their schema per say, but in the interpretator for the jing parser for Atom. For DHARMA schema, I have rewritten content to avoid the message, easier since we don't have such a generic approach to content.

The difference between Oxygen and Atom is a tech one. The don't validate the way same with the jing parser. 
In Atom, it is looking to connect to TEI Schema through Epidoc and can't exactly success without a specific declaration of a catalog of paths. So theoretically, it could be overcome by  feeding manually parameters to Atom.
