### ISSUE TITLE
added aśvalalita

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#164]
I've added this to prosodicPatterns as kaw-Latn. according to Zoetmulder, the name is also attested in Indian sources but I don't find it in Apte. anyhow, I suppose the san-Latn equivalent would need to end in -ā. please check and add to EGD.

**Comment by danbalogh** [comment]
I've tidied it in prosodicPatterns and added it to the EGD. The Sanskrit name ends in -a (there are many that do). I've added caesurae to the conventional and XML prosodic patterns. The caesura marker in combination with your bars separating the gaṇas looks really unwieldy - I'm really hoping I can persuade you to get rid of those bars.
The metre is not in Part I of Apte's appendix, the one with the detailed description of relatively common metres, but it is there in the "classified list" which is Part II of the appendix. He drew the definition from the Mandāramaranda.
To be able to refer to this, I've put the following in the file:
`<bibl><ptr target="bib:Apte1890_01"/><citedRange unit="appendix">A: Sanskrit Prosody</citedRange><citedRange unit="section">II.23</citedRange></bibl>`
I did not use item because the individual metres are not numbered in this part; to find aśvalalita, one has to go to section II.23 and go to na-ja-bha-ja-bha-ja-bha-la-ga in the alphabetical list there.
Please let me know if you would prefer a different way of referring to metres in Apte's Classified List.
Furthermore, in accordance with the above "section II.23", I've changed the existing references as follows:
`<bibl><ptr target="bib:Apte1890_01"/><citedRange unit="appendix">A: Sanskrit Prosody</citedRange><citedRange unit="page">4</citedRange><citedRange unit="item">I.A.11.5</citedRange></bibl>`
that is to say, I've made the item numbers "I.A.whatever" instead of the previous "A.whatever".
Again, please let me know if you disagree.
Otherwise, please close this thread when you've seen this.

As of this moment I have not yet pushed my edits back to GitHub; will do shortly after I've had a look at your abhikṛti.

**Comment by arlogriffiths** [comment]
thanks a lot. I endorse all your changes.

sorry, I am inserting vertical bars only because they help me in the data entry process. I was intending to ask you to watch out for any sjch bars that I forget to remove again after I am done noting the patterns. I have now removed those bars from the `<seg type="prosody">` of aśvalalita and pushed the file back to GitHub. I'll try to be less forgetful from now on, but please watch over my shoulders. please also feel free to remove any such bars that you find anywhere else.

closing this thread.

**Comment by danbalogh** [comment]
It's OK if you leave it to me to remove the bars. I just wanted to be sure you are OK with me removing them before doing so.
