### ISSUE TITLE
added a member of the abhikrti class without known name

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#165]
please check this new prosodicPatterns entry too and consider whether we want to add it to EGD as well

**Comment by arlogriffiths** [comment]
@ajaniak : do you understand why the generic label and the pattern are not displayed?

<img width="681" alt="Capture d’écran 2022-03-30 à 07 51 25" src="https://user-images.githubusercontent.com/835603/160760700-278acf81-b5c0-476a-803c-53b9e320ac23.png">

**Comment by ajaniak** [comment]
I can't fond any abhikrti in the file. Have you pushed it?

**Comment by arlogriffiths** [comment]
oops! I'd forgotten...

**Comment by danbalogh** [comment]
I've checked and found it in good order. Added a comment confirming that it is not in Apte's appendix. I don't think there's a point in adding nameless metres to the EGD appendix. In fact, now that we have the authority file, we should indeed consider discarding that part of the EGD appendix altogether, since it's redundant.
