### ISSUE TITLE
can we introduce @rend="check" in EGD?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#184]
Can we introduce @rend="check" in EGD in the same way that it is offered in EGC?

**Comment by danbalogh** [comment]
To be honest, I'm not happy with the choice of `@rend`, since the TEI definition of that attribute is "indicates how the element in question was rendered or presented **in the source text**" (emphasis mine). It would seem better to me to use e.g. `@cert="unknown"` or `@precision="unknown"`, but I have not checked in detail whether this is feasible.
Since you have surely discussed options and decided that `@rend` was good enough TEI, and at any rate, it seems that this is intended for a behihd-the-scenes solution only, I am fine with it if you are set on retaining this use of rend.
Let me know if that is what you want. And if it is, I need some details on the circumstances in which you would want to use this in an epigraphic/diplomatic edition. E.g. "just about anywhere" - in which case it could perhaps go in section 7 "additional information". Or "in emendations", in which case perhaps section 6 "editorial intervention" is a better place for it. Etc.

**Comment by ajaniak** [comment]
We have chosen `@rend` to keep the consistency on other decision taken in the EGD. 
It is  the possibility to underline visually than some works still need to be done by adding some highlight in the display. On the long run, it will be deleted once the work is finished. We have allowed its use everywhere in EGC without any discrimination since it is to help the team identifying the work still need to be done or discussed. But we don't have the same structure, so reducing its application doesn't make sense in EGC files, maybe it does in EGD.

**Comment by danbalogh** [comment]
I've added this to the EGD as §7.6 (not visible in the document outline, since it's shown as a suggestion - I'll approve it when I next edit the master version in Word).
On a side note, when you say "to keep the consistency on other decision taken in the EGD", I hope you mean EGC. For the record, using `@rend` for such a purpose is not consistent with any previous decision taken in the EGD, where `@rend` in the edition is only ever used for features of the original text. (Unlike divisions other than the edition, where there is no "original text", and so `@rend` is used for presentation format.)

@arlogriffiths , please close this thread if you are satisfied with the EGD section.
