### ISSUE TITLE
display of <space>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#185]
Dear Axelle,

It seems that the display conventions for `<space>` are not yet listed on https://erc-dharma.github.io/editorial.

I notice that the display of `<space>` is not consistent depending on whether @quantity is encoded. See screenshot. 

<img width="332" alt="Capture d’écran 2022-09-30 à 14 45 02" src="https://user-images.githubusercontent.com/835603/193218627-ecfadeb9-564c-4a97-9ef8-f20095853b70.png">

I suppose it will be better to display  `<space type="descender">` consistently.

@danbalogh : any suggestion?

**Comment by danbalogh** [comment]
Dear Arlo,
I'm not sure I understand the problem correctly, but I believe you are saying that the code behind your screenshot involves `<space type="descender" quantity="2" unit="character"/>` If so, then this is a problem with your encoding, not with the display.
The EGD §4.3.5 says, "imposed spaces must always be encoded without further attributes, i.e. never use @quantity and @unit to encode their size".
We agreed on this long ago and I'd like to keep it that way. The reason we're encoding imposed spaces is that they interrupt the flow of text - but their size in number of characters is not relevant, since they are not space left vacant for subsequent inscribing. The size and shape of imposed spaces is a layout detail that can be described in human-readable terms in the metadata.

**Comment by arlogriffiths** [comment]
thanks Dan! it was en encoding error in Chloé's file.
