### ISSUE TITLE
<rs>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#186]
Dear Axelle,

I realize that the discussion on semantic markup of persons has not yet been finished.

But may I ask for the schema to be modified so as to allow the attribute values I wish to use in the example below (for my lecture tomorrow)?

Thanks!

Arlo
<img width="470" alt="Capture d’écran 2022-11-09 à 16 01 12" src="https://user-images.githubusercontent.com/835603/200865035-5bc1199d-15ee-468e-8c80-46ed234a386c.png">

**Comment by ajaniak** [comment]
I have pushed a schema. It should work for `@role='ruling'` without change. However, you will need to change you encoding for `@type` since this attribute has a datatype set on enumerate, so its content can't use space. So I have creating values combining the value individual and gender for now. So in your case, you should use `@type='individual-masc'`. Once change your file should be good.

**Comment by arlogriffiths** [comment]
thanks Axelle.

@salomepichon : if I am not mistaken, this means that almost all examples of @type on `<rs>` in the file Semantic_Markup_Persons are invalid TEI. I am not sure how this this problem of validation could have escaped our collective attention...
