### ISSUE TITLE
question about license

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#191]
At the moment, our editions contains these two phrases under `<availability>` in the teiHeader:

"This work is licensed under the Creative Commons Attribution 4.0 Unported Licence. To view a copy of the licence, visit https://creativecommons.org/licenses/by/4.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA."

I don't see the letters BY in the first phrase? Should it be mentioned? 
Meanwhile, I am not sure what "Unported Licence" means but I don't see these words when I visit https://creativecommons.org/licenses/by/4.0/. Should we keep them?

**Comment by ajaniak** [comment]
The unported licence is important since it is related to the fact this CC-By licence is not  associated with any specific jurisdiction. I don't know where we are on the subject, but I was waiting on the feedback from the CNRS's juridical department to update the licence with the correct wording. Maybe @manufrancis has more information on the matter?
