### ISSUE TITLE
EGD: space left blank by scribe who could not read the prototype

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#196]
This issue originally came up in personal discussion with @AnneSchmiedchen. In one of her plates, the scribe must have been unable to read the character he was supposed to engrave, and he left a blank space for it. She and I feel that this is similar to vacat (EGD §4.3.3), but not quite the same.

The instance is in INSMaitraka00053,
the expected text is diṅmaṇḍalaḥ,
the marked-up text is `di<choice><sic><space type="other"/></sic><corr>ṅma</corr></choice>ṇḍalaḥ`

In a comment thread in the EGD (now archived), @arlogriffiths has suggested that this case is not different enough from vacat to get separate treatment. The current definition of vacat in EGD §4.3.3 is "areas that were left blank when the rest of the inscription was engraved, with the intent to be filled later on, e.g. with a name or a date". The case of the scribe being unable to interpret and reconstruct a complex character is quite different to me, but now that I think about it, I am not sure if we gain anything by differentiating it from vacat and pushing it into the catch-all category of "other". So I am of two minds about this and would like to ask @AnneSchmiedchen and @arlogriffiths to discuss the matter. If Annette is also undecided, then I have no objection to going the way suggested by Arlo.

Possibly relevant: in parallel, Arlo and I have decided to broaden the category of "other" (and to change its name) so that it includes cases where a space cannot be classified because we lack information (e.g. no surrogate), and not just spaces that we know do not fit into any of the other categories. See issue #195 about that.

**Comment by arlogriffiths** [comment]
I haven't seen the locus in INSMaitraka00053 so it's hard for me to understand why you are sure as to the reason why the scribe left the blank, and why it would not be an instance of "areas that were left blank when the rest of the inscription was engraved, with the intent to be filled later on". How can we be sure that it is a "case of the scribe being unable to interpret and reconstruct a complex character"? Whatever be the mental process on the part of the scribe, do we actually disagree on it being **a space left blank to be filled in**? If we don't disagree there, it seems to me that we agree it's a vacat, and the words chosen to define vacat can easily be changed a bit in order for you to feel comfortable about including this case under that label.

**Comment by danbalogh** [comment]
You've worked a lot more with manuscripts than I have, but my impression is that this is often done by copyists: when they cannot interpret a character in the specimen they are copying (either because of damage or because they don't recognise the character), then they leave a blank corresponding to that character (or write an editorial symbol for each character they could not read). I do not think that this is done with the intent of being filled later, so indeed, I do disagree that it meets the letter of our definition of vacat. More strongly, I feel that it does not meet the spirit of our definition of vacat, which is typically for cases where the name of a donee or a place or such case-specific information was to be engraved later (as indicated by the examples in our definition). From a different aspect, one very clear difference between this and what I would call a vacat is that here, the editor can restore the missing character with perfect confidence, whereas this would not normally be possible in a vacat, the intended contents of which are impossible to deduce from the context.
As to how we can be sure that it's a case of the scribe being unable to interpret (etc.), well, of course we can't be sure about anything, but given that it's a gap of a single character where Annette is certain that the rather complex and rare conjunct ṅma ought to be present, I don't think anybody can come up with any explanation of the space that is half so plausible as this.
But let's wait for what Annette thinks.

**Comment by AnneSchmiedchen** [comment]
To begin with, yes, it is not a big, but just a small space. And what is missing or what we would expect is ṅma as in some 60 other inscriptions (or gma as in some 20 other inscriptions). So I am with Dániel's explanation, because this was also my impression and seems to be the most plausible to me. I think that the scribe left it out, because it was perhaps not readable for him on the prototype, and this relatively difficult conjunct also does not appear anywhere else in the text. Of course, he might have hoped to fill this in later after asking someone, etc. But this is really not the same like leaving a blank for a name to be filled in later.

**Comment by arlogriffiths** [comment]
I find that your appreciation of the case is strongly, too strongly, colored by the literal definition of vacat as "areas that were left blank when the rest of the inscription was engraved, with the intent to be filled later on, e.g. with a name or a date". Looking around on the internet, I find that classical epigraphists are not as precise in their definition of vacat. See:

- http://www.saxa-loquuntur.nl/tools/epigraphic-sigla.html
- https://www.mom.fr/sites/mom.fr/files/img/Publications/normes_epigraphiques_publimom.pdf

So, Annette, please try to evaluatie the example and my proposal without sticking to the letter of what the EGD currently says.

I do not find one part of Daniel's reasoning persuasive: "one very clear difference between this and what I would call a vacat is that here, the editor can restore the missing character with perfect confidence, whereas this would not normally be possible in a vacat [_as presently defined_, AG], the intended contents of which are impossible to deduce from the context." — This is only true in Annette's case because it falls in the middle of a well known passage from a highly formulaic corpus. But an aksara difficult to read by scribe could just as well have fallen, and is presumably more likely to occur, in an hapax such as personal name, in which case the editor would be unable to supply the missing character(s).

Since we can only very rarely make a good guess as to why a scribe did precisely what he did, I ask you 
- what is gained from distinghuishing cases where a scribe left some space blank for it "to be filled later on, e.g. with a name or a date" from other cases where he left a blank corresponding to some missing characters? 
- would it not be more efficient for our encoding rules, and less speculative, to seize on the commonality between the cases, namely that there are missing characters and that the scribe showed awareness of this by leaving some blank space?

I maintain my proposal to encode Annette's instance as `<space type="vacat"/>` and to modifiy the EGD's definition of vacat accordingly.

**Comment by danbalogh** [comment]
Two, perhaps futile, points that I feel I have to make.

1. By the logic of defining vacat as nothing more than space left blank, as in your links, we should then use "vacat" for all the spaces that we now distinguish in the EGD, including imposed spaces and those for semantic segmentation. But we have decided to make these distinctions, and hence defined vacat more narrowly as space left blank for subsequent filling. If we do not stick to the letter of what the EGD currently says, then what is to prevent us encoding all spaces as type="vacat"? (I believe that is not what you want us to do.)
2. You are of course right that there may be cases where a space of this kind cannot be confidently restored by the editor. But I am sure you agree there is still an essential difference between A) space left blank because something indeterminate (kimapi) was to go there in the future, but nobody at the time of engraving knew what; the information that was to go there simply did not exist at the time of engraving (vacat), and B) space left blank because something determinate (kiṁcid) was meant to go there but due to a glitch the engraver did not get what it was, though that information did exist at the time.

That said, your points about gain and efficiency are perfectly valid. Annette and I have also emailed about this separately and neither of us insists strongly on keeping this case distinct. Since spaces of this kind are expected to be quite rare, there is indeed little gained by encoding them differently. (I find this a somewhat ironic reversal: it is usually you who argue for coming up with differentiated encoding for various details and I who argue for just lumping those cases with existing similar ones in order not to complicate our encoding scheme...)

**So, all in all, we are fine with changing the encoding** in Annette's text to `<space type="vacat" quantity="1" unit="character"/>` (@AnneSchmiedchen : please note that for type=vacat, you'll have to add the unit and quantity), and **also fine with changing the definition of vacat** in the EGD.
@arlogriffiths , do you have any specific suggestion _how_ that definition should be changed? Surely we want to keep it distinct from imposed and semantic spaces, so the broad definitions in your sources cannot be used. I'm thinking of changing the subsection's title to "Space representing information not available to the engraver" and explicitly mentioning both the intent of filling in particulars at a later time, and the case of something the engraver could not read/interpret.

Finally, @arlogriffiths , do you agree that when the editor does restore the contents of a vacat, this should be implemented as we have done for Annette's text, using a choice with sic around the space and corr around the restoration? The best alternative would be to put `<surplus>` around the space and `<supplied reason="omitted">` around the restoration. This latter seems semantically less appropriate, since the one-character space in this case, we are sure, is a sort of scribal error(ish thingy) that we are correcting.
I expect such cases to be very rare, but there is no harm in explicitly stating the preferred encoding somewhere in the EGD.

**Comment by arlogriffiths** [comment]
Thanks Dan! 

As might have become clear from my words attempting to capture what is common between Annette's case and our definition of vacat so far ("that there are missing characters and that the scribe showed awareness of this by leaving some blank space"), I was not suggesting to lump vacat with any old blank space. 

I suggest rephrasing: "Space left blank for information the engraver was unable to furnish or to reproduce".

I found that solution (using a choice with sic around the space and corr around the restoration) ingenious and can propose nothing better.

**Comment by danbalogh** [comment]
EGD updated accordingly. Closing this issue.
