### ISSUE TITLE
mandatoriness of @n in <bibl> items in primary bibliography

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#200]
I propose to remove the constraint "Attribute name "n" associated with an element type "bibl" must be followed by the ' = ' character." It happens often that early editions must be cited in primary bibliography but are superseded philologically by subsequent publications so that they need not be cited in any apparatus items, and hence no siglum is ever needed. So it makes no sense to declare a siglum for such a `<bibl>` item.

@danbalogh : agreed?

**Comment by danbalogh** [comment]
The message "Attribute name "n" associated with an element type "bibl" must be followed by the ' = ' character." concerns a generic XML rule: if an attribute is present, it must be followed by the '=' character. From your reasoning, I assume that you mean the error message "Description: @n mandatory in the primary bibliography to declare sigla". To be honest, I do not know why we have this constraint to begin with; what the EGD (§9.4.3) says on the matter is that **if** your apparatus cites lemmas or readings from previous editors using `@source` , then and only then, the full citations of those editions in your bibliography division must include a manually encoded siglum; and moreover, this applies regardless of whether the full citation is in your primary bibliography or the secondary one.
The mandatory use of a siglum in items of the primary bibliography may have been there in a very early version of the EGD that I no longer recall; the release version 1 already says what I cite above.

So I do agree that we should not make the use of `@n` mandatory on items of the primary bibliography.

What we need to work out, involving @ajaniak, is this: once we remove the constraint from the schema that `@n` is mandatory on items of the primary bibliography, will there be a feasible way the schema could check whether a siglum is present _somewhere_ to for all `@source` attributes in the apparatus?
Moreover, do we want to continue to allow putting the siglum in the secondary bibliography, or shall we restrict it to the primary? The idea behind allowing sigla in the secondary bib was that variants may need to be cited from works that are not complete editions of the text (e.g. the first ARIE report, or an article proposing a correction to a specific locus, or re-editing just part of a text). But I think what I have been doing in actual practice was to mention such variants in an apparatus note instead of adding them as variant readings; this may be adopted instead of citing variants with sigla. But, if it is not too much of a problem technically, I think we should, after all, retain the ability to put a siglum in the secondary bibliography.

**Comment by ajaniak** [comment]
The schema has been changed accordingly.

**Comment by arlogriffiths** [comment]
Thanks @ajaniak. Please do answer Dan's question: "will there be a feasible way the schema could check whether a siglum is present somewhere to for all @source attributes in the apparatus?"

I'd like to maintain the option for sigla to be defined in sec. bibl.

@danbalogh  — please make the necessary changes to EGD and close this issue.

**Comment by danbalogh** [comment]
The EGD needs no revision if we retain the possibility of putting sigla in the secondary bibliography. I have made some clarificatory changes. I'm not closing the thread just yet; let's wait and see what @ajaniak says about the schema check.

**Comment by ajaniak** [comment]
Yes, I have added a rule yesterday in the schematron to check this.

**Comment by danbalogh** [comment]
Great, thank you. In that case, I think we can close this one.

**Comment by danbalogh** [comment]
I now get an error message saying that "n is mandatory in thr primary bibliography" when there is a `@source` on a translation div, `<div type="translation" xml:lang="fra" source="bib:Estienne-Monod2008_01">`.
The error message should appear only for `@source` is used on an `<rdg>`.
Note also that, according to the above discussion, the mandatory `@n` should be _either_ in the primary _or_ in the secondary bibliography, not necessarily the former.

**Comment by ajaniak** [comment]
done

**Comment by danbalogh** [comment]
Thanks.
