### ISSUE TITLE
encoding copper-plate from previous edition that does not indicate line numbers

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#207]
Dear @danbalogh and @ajaniak,

I am working on the file [https://github.com/erc-dharma/tfc-nusantara-epigraphy/blob/master/provisional/Java10Majapahit/DHARMA_INSIDENKPamintihan.xml](https://github.com/erc-dharma/tfc-nusantara-epigraphy/blob/master/provisional/Java10Majapahit/DHARMA_INSIDENKPamintihan.xml). This concerns a charter that originally consisted in 5 plates of which only 4 were ever found. Plate 2 was never recovered. Plate 4 was among the plates found but has been lost since the first transcription of the charter was published. This publication only specifies transitions between plates/faces (`<pb/>`) but no line beginnings (`<lb/>`) . I am forced to use this edition for representing the text of plate 4. 

@danbalogh — I am not sure if our EGD gives recommendations for precisely this kind of case. If it does, please remind me where. Could you check if you think I have correctly encoded? If I have, then I should note that the `<pb/>`s that do not contain `<lb/>`s are not shown in display.

Thanks!

cc to @ekobastiawan and @wayanjarrah who may encounter similar cases.

**Comment by danbalogh** [comment]
@arlogriffiths said in EGD comment:
to my mind, this value of @evidence should be used when a specific part of a surface is now gone but was still legible for a previous editor. I am not in favor treating my plate 4 as supplied simply because I have no surrogate and don't know where the original plate is.

@danbalogh replied in EGD comment
I can sympathise with not wanting to treat an entire plate as supplied. So don't do that then, but I still say you should estimate the position of the line breaks and encode an lb for each line on the (now) lost plate.

**Comment by danbalogh** [comment]
You are splitting this thread again. Let's keep the discussion in a single place, please. I'm copying your comments from the EGD over here again, and leaving just a reminder to self in the EGD that revision may be needed there.

@arlogriffiths said in EGD comment at §3.2.3. Placement of line beginnings: now that I have a concrete case (issue #207) I am not so happy with this. I would much prefer not to be forced to speculatively insert <lb>s into the published text of the given lost plate, only for reason of systemic pressure. can't we change our system instead?

@arlogriffiths said in EGD comment, same place: if we do keep this rule, then I think it should be belabored a bit more and furnished with an example, because I suspect I am not the only person who will need to be persuaded that speculative insertion of line numbering is better than no line numbering at all.

My thoughts on this follow.

The rule was, to be honest, originally devised for situations where there is a lacuna around a single lost line break (end of one line and beginning of next line damaged). In those situations, I am absolutely certain that the rule should be kept, and I hope you agree. I can try to find (or make up) an example of that to add to the EGD.

As for your case of multiple lines, I can see why you would want to avoid inserting several speculative line breaks. But the reason I would still prefer to do that is not EpiDoc itself, but rather our own guidelines and their already worrisome complexity. What you want to do here is, to my mind, the introduction of yet another subrule for one very particular case for which our already existing rules provide a decent enough (sure, not perfect, but decent enough) fit. Once that is done, we'll need encoders to be aware of this rule and to be able to decide if it applies to something they are trying to encode, and we'll need our schema to provide for it and our display transformation to be able to handle it. What is it that you hope to gain from all this added complication?

I'm not sure how far we should carry this discussion. If you absolutely insist, then your proposal with `<lb n="1-6"/>` seems like a good enough workaround for me. I don't like it, because it's a hack of the system and it may still cause some problems (e.g. if we one day want a display transformation to output a diplomatic edition, with a new screen line for every new epigraphic line). But I can live with it and can put it in the EGD.

**Comment by arlogriffiths** [comment]
It is not that I absolutely refuse to insert `<lb>`s into my edition at speculative locations, but that I haven't yet understood why my intuitive encoding is not compliant with the letter of our guidelines (which rules are you referring to?) and haven't yet been persuaded that there is no solution that could make my current encoding compliant without having to introduce a lot of new complexity into the EGD. 

My basic point is that when encoders are faced with an edition like the following, and the relevant 4th plate is lost, I think they will naturally do what I did unless they are instructed to do otherwise:

<img width="700" alt="Capture d’écran 2023-04-04 à 11 09 49" src="https://user-images.githubusercontent.com/835603/229685296-a44abf44-aa98-453a-823a-c4929993c452.png">

If that is a reasonable prediction, then either (a) we need instructions to prevent this behavior and get the encoders to do what you suggest is compliant with our own guidelines, or (b) we need to find a way to change the interpretation or formulation of our rules to make this behavior compliant — and find a way to display it.

It seems to me that we could avoid the complicated new preemptive instructions (i.e., subrules) required in scenario (a) if we can bring the machine understand that not only a new `<lb>` but also any new `<pb>` means the end of the current line, in which case the encoding I have chosen will no longer be problematic, will it? 

In EGD 3.2.2, we write "every physical line of text in your edition must have a number encoded in the @n attribute of the corresponding <lb/> element" but someone who chooses intuitively to encode as I did will not think to look in 3.2.2 and even if s/he does, s/he might reason that there is no `<lb>` encoded so the rule isn't relevant. I understand now how 3.2.2 was intended and what impact on display it has, but I don't think an average encoder may be expected to understand this unless we make the EGD more explicit by writing something like "any stretch of text will be considered to belong to the last encoded `<lb>`". I recommend we do so if we decide to stick to your interpretation of the meaning of the current guidelines. And in that case I will insert the missing `<lb>` tags into my edition.

**Comment by danbalogh** [comment]
I think it is not so much the letter, but more like the spirit of our guidelines that the idea is not compliant with. The EGD section §3.2.2 you cite is indeed, as you say, about the rule that every `<lb/>` must have a number, not that every line must have an `<lb/>`. The idea that all line beginnings must be encoded has been sort of taken for granted, as we did not foresee cases where we don't know where they are. By default, physical line breaks are encoded in every edition, and that's that. Still, if you want the letter of the guidelines, it's actually there right at the beginning of the big section on structure: §3.1, "line beginnings must be represented in all encoded inscriptions as set out in §3.2 below". In the same way, lines are rather taken for granted in the EpiDoc guidelines, which [do say](https://epidoc.stoa.org/gl/latest/trans-linebreak.html) that "it is our convention to place an `lb` at the beginning of every epigraphic line in the edition", but mention this only in the context of treating lines as quasi-containers.

What an encoder will "naturally" do is I think very much a moot point. Encoding is an absolutely unnatural behaviour even compared to philology. It involves rigorously, even algorithmically, following rules. In this particular case, I think not adding line breaks when working from a print edition that does not show them is about as natural as not changing the transliteration of that print edition to DHARMA standard would be. By default, you encode line breaks, and by default, you use DHARMA transliteration. If you are, say, working from an edition that does not explicitly indicate initial vowels and final consonants, you make your best guess as to where they were used in the original, and transliterate accordingly. Likewise, if that edition does not show line breaks, you make your best guess and mark them up accordingly. Actually, where you say "we could avoid the complicated new preemptive instructions (i.e., subrules) required in scenario (a)" - where your scenario (a) is preventing encoders from naturally seeing things your way - you have it exactly the wrong way round. Preventing encoders from doing that would not require any subrules or complications. At most, it may need to be made explicit that the universally applicable, simple general rule of encoding the beginnings of all physical lines is also applicable in this case. It is the option to _dispense with_ lb elements in special cases such as yours that would make for an exception and require subrules to handle it (a subrule in the Guide, a subrule in the schema, a subrule in the display transformation, and who knows where else). But whether you see that the same way or not, IF we can agree that line breaks are mandatory in all cases, then I fully agree that it would be useful to make this more explicit in the EGD and a specific point on cases such as this should also be added.

So, with those things out of the way, on to whether line breaks should be mandatory.

We in fact do very little machine-actioning on `<lb>` elements. Perhaps none, as of now; I don't know. We do not need to "teach the machine that the intervention of <pb> also means the end of the previous <lb>", since to the machine, an lb is an empty element. I'm sure that the display issue you pointed out at the top, with `<pb>`s not appearing in display when there is no following lb, can be solved pretty easily. (I suppose this may have been deliberately done by Axelle to prevent the first and last blank pages of copper plates showing up as page breaks in the display, in which case the rule could be altered.) I don't know if anybody anywhere in the corpus has used formatting (e.g. alignment or directionality) on an lb element, and if these have been used, whether they affect the display in any way at all. If the answer is yes to both, it should still be possible, as you say, to refine our display transformation and make such things affect text only up to the next pb if that comes sooner than the next lb. 

But things do not stop there, and machine actionability is not the whole party. For example, we refer to lines in our apparatus. How will you create an apparatus for those two pages? (You may say you will not have an apparatus if you are encoding without visual aid, but you definitely could, if you for example proposed an emendation that was not proposed by the original editor.) So how? Introduce yet another subrule that the `@loc` of an apparatus item can be a pb as well as an lb (or an fw number), accept the added complication to our processing codes and our guidelines, and tell users of the edition to live with the fact that if they browse the apparatus and want to find a lemma in the text, they'll have to peruse a whole page to find it? The apparatus, as of now, does not have a clickable link that will take you to the line in question, but we have considered making it so in the future (EGD §9.1.2, "we may wish to make it machine-actionable in the future and therefore adopt rigorous rules from the beginning"). We also generally use line numbers in referring to inscriptions in human-readable references, no clickability involved, but line numbers are still a great help.

Please do correct me if I miss something, but it seems to me that in all this discussion so far, you have made two arguments for omitting lb elements in such a case: one being an aversion to adding them speculatively, and the other being that it feels natural for you (or that you think it may feel natural for others) not to add line breaks when you are working only from a previous edition that does not show them. As will be evident from my rant above, I consider the second argument invalid. I can sympathise with the first, but do not fully agree with it. A lot of what we do involves interpretation and editorial decisions on things that are not black-and-white in the original. You don't want to say that a line break is at point A when it may in fact be at point B. But the machine that reads and transforms the code will not care, and for the humans who read the edition, you can mention that line breaks in that stretch of text are estimated. You probably feel that it is dishonest to claim something as true when you have not been able to ascertain it. Fair enough, but you are also claiming the reading is correct, and you take responsibility for it by refusing to mark it up as `<supplied evidence="previouseditor">`, so you could do the same for the line breaks. Or, if you are really concerned about potential harm done to future machine queries (e.g. research on sandhi across line breaks or whatever), then we could consider permitting (or requiring) a `<certainty>` element next to speculatively added line breaks, but our earlier stance on this was that "we deem that the benefit is not worth the effort" (EGD §3.2.4, footnote number 11 in the google version). Keep in mind also that such texts represent a small, perhaps vanishingly small fraction of our corpus, so even statistical data-mining is not likely to be affected by it strongly. And if the missing plate should miraculously turn up somewhere next April, it will be as easy to reposition the line breaks correctly as it will be to revise the readings.

So, as I see the scoreboard, there is one argument _for_ not encoding line breaks; that argument involves minor reservations that are easily addressed and anyway apply only to an extremely small number of cases where the problem may arise. Conversely, there are two arguments _against_ it, both of which seem pretty strong to me. One is that the present general rules require (or at least strongly imply) that it should not be done, so introducing it would require adding an exception to those rules for the sake of that small number of cases. The other is that _if_ that exception were added, it would generate ripples that would all need to be smoothed out, and it would definitely involve additional complications to deal with the foreseeable ripples (schema, display, apparatus), not to mention a fair probability of other ripples that neither of us foresee at the moment.

**Comment by arlogriffiths** [comment]
For the record, after separate discussion by zoom, I have been persuaded to accept that encoding line breaks will remain mandatory in all cases. I am grateful to Daniel for his careful analysis of the situation and for his willingness to make this rule more explicit in the EGD and add a specific point on cases such as this.

**Comment by danbalogh** [comment]
:)
