### ISSUE TITLE
encoding of omission on the part of a previous editor

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#211]
@danbalogh —

do we have explicit guidance on what to do in a case like this?

`<app loc="2v2">
                      <lem>kanaka-rajata-vastrādi</lem>
                     <rdg source="bib:Naerssen1941_01">kanakavastrādi</rdg>
                  </app>
                   <app loc="2v2">
                      <lem>-rajata-</lem>
                     <rdg source="bib:Naerssen1941_01"><gap reason="omitted"/></rdg>
                  </app>`

I give two ways of encoding the same and prefer the second as semantically more explicit. If yoiu agree, and if we haven't yet given such an example, then please include in EGD.

**Comment by danbalogh** [comment]
`<gap reason="omitted"/></rdg>` means that you are sure the scribe omitted something, but you cannot supply the omitted word(s) or character(s). Thus your second encoding `<app loc="2v2"> <lem>-rajata-</lem> <rdg source="bib:Naerssen1941_01"><gap reason="omitted"/></rdg> </app>` means that where you read rajata, Naerssen's edition shows a scribal omission which Naerssen was not able to supply. This is _very_ different from your first encoding `<app loc="2v2"> <lem>kanaka-rajata-vastrādi</lem> <rdg source="bib:Naerssen1941_01">kanakavastrādi</rdg> </app>` which indicates that Naerssen's edition accidentally omitted the word rajata.
The latter is clearly what you have in mind, so the first encoding is the only correct one of the two. To shorten it, you can go for `<app loc="2v2"><lem>kanaka-rajata-</lem><rdg source="bib:Naerssen1941_01">kanaka-</rdg></app>`.

This is what I would do; however, we do actually have explicit guidance in the EGD: §9.1.4, "if a printed edition shows nothing (i.e. not even a lacuna) at a locus where your edition has content (including a tentative reading or a lacuna), the reading of the edition in question may be represented by an empty element, e.g. `<rdg source="bib:VenkatasubbaAyyar1943_01"/>`"
In light of this, you could also choose to encode `<app loc="2v2"><lem>-rajata-</lem> <rdg source="bib:Naerssen1941_01"/></app>`.  But to be honest, I don't really like this latter; this EGD instruction was, I think, meant for cases where a previous editor could not read something and failed to show a lacuna in their edition.

**Comment by arlogriffiths** [comment]
My first suggestion was made under the influence of how I am used to encoding manuscript-based editions as per EGC:

5.5.9 Text of lemma absent from a witness due to scribal omission
When you wish to indicate that a given lemma has no corresponding reading in a given witness, because the scribe has omitted the string of characters in question, then you can use <gap> with the value "omitted" on @reason inside the <rdg> for the relevant witness.

The example we give there is

`<app>	<lem wit="#K">tinurunakən sakeṅ svarganya deniṅ devata kabeh</lem>	<note type="altLem">tinurunakən ... kabeh</note>	<rdg wit="#L" cause="eye-skip"><gap reason="omitted"/></rdg>	<note>This sentence seems to have been omitted in <ptr target="#L"/> due to eye-skip from <foreign>kavaḥ</foreign> to <foreign>kabeḥ</foreign>.</note></app>`

Are previous editions not the epigraphist's analogy to a manuscript witness? If they are, then why could `<app loc="2v2"> <lem>-rajata-</lem> <rdg source="bib:Naerssen1941_01"><gap reason="omitted"/></rdg></app>` not means that where I read _rajata_, Naerssen's edition shows nothing, i.e. that he has omitted the lemma?

**Comment by danbalogh** [comment]
Emphatically, no. This is not my idiosyncratic opinion on an ambiguous issue, but the only possible way to treat the issue, and there is no ambiguity whatsoever if you think about it. To explain:
Previous editions are indeed analogous to manuscript witnesses inasmuch as we use their readings in an apparatus. But they are not in fact manuscript witnesses, and we do not treat them as such as regards all other encoding. They are themselves editions which can and do alter the real witness, and it is crucial for us to show both what a previous editor read in the witness _and_ how he altered what he read there. Any and all markup within `<rdg>` is what would have been used by the cited editor, if their edition had been in DHARMA EpiDoc. (Cf. §9.1.4, "text within this element should be marked up with XML tags to clearly indicate what the cited editor deemed unclear, emended or supplied" etc.). I repeat: that markup is not _your_ editorial markup on the previous edition as witness, but the _previous editor's_ markup on the sole real witness, the inscription.

So, when Mr. X's edition emends abd to abc, you cite that as `<rdg source="X">ab<choice><sic>d</sic><corr>c</corr></choice></rdg>`. If Mr. X's edition restores an omission, you cite that as `<rdg source="X">ab<supplied reason="omitted">c</supplied></rdg>`. If that edition were a MS witness, then you would encode such interventions as _scribal_, not editorial (you would use choice with add and del in the first case, and add in the second case). But this is not what we do and not what you want to do.
Likewise, from the other side of the table, if Mr. X's edition has a typo or a misreading, and prints abd where you can see that the inscription has abc, your lemma will still be `<rdg source="X">abc</rdg>`. That is to say, in this case, you do not add your own markup `<rdg source="X">ab<choice><sic>d</sic><corr>c</corr></choice></rdg>` to say that X's edition wrongly has abd and you want to correct this to abc. The place where you show your opinion that abc is the correct reading, is your lemma (and your edition), not the reading you cite from X. If X's edition is smudged and you can't see the c clearly, you don't cite it as `<rdg source="X">ab<unclear>c</unclear></rdg>`, because that would mean that X showed the c as unclear in the original. If the c is unclear in X's edition, you make do as best you can (e.g. try and find another copy of X's edition, make your best guess as to whether he prints a c there, or add a note to your apparatus saying the c is not clear in the edition).  In exactly the same way, if X's edition has ab where you know the text is abc, the reading you cite from X must be ab: `<rdg source="X">ab</rdg>`. The fact that X has omitted the c from his reading is shown in your lemma, not in the reading.

Your first suggestion would thus make `<gap reason="omitted"/>` an exception from the universal rule that markup within an rdg shows the cited editor's markup (converted to XML where applicable). Moreover, as I already pointed out in my earlier reply, `<gap reason="omitted"/>` means a scribal omission which you are unable to restore (EGD §6.4). There may be cases where X's edition indicates a scribal omission that X could not restore; if we for some reason wanted to make an exception and use `<gap reason="omitted"/>` in an rdg to indicate an omission by the previous editor, then we would be left without a way to encode a scribal omission indicated by the previous editor.

**Comment by arlogriffiths** [comment]
Thanks for exposing this so clearly!
