### ISSUE TITLE
URI of epidoc schema

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#220]
Not urgent.
In our templates and existing files, the link to the EpiDoc schema is given as http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng, which has for some time been causing errors, as nothing can be found at this URI. I know that some of us have commented out the instruction to invoke the EpiDoc schema to get rid of the error messages.
But actually, it seems that the new location of the schema is https://epidoc.stoa.org/schema/latest/tei-epidoc.rng and the errors were not because the epidoc server was down, but because the old address is deprecated.
So I suggest changing the URI in the templates and in all existing files. (I have done this in the VengiCalukya, BadamiCalukya and Siddham subcorpora)

**Comment by ajaniak** [comment]
I have updated the uri

**Comment by michaelnmmeyer** [comment]
It would be useful to set up a URL that redirects to the EpiDoc schema and to use this new URL instead of https://epidoc.stoa.org/schema/latest/tei-epidoc.rng. The extra indirection makes it possible to change the schema to be validated against by editing a single record instead of ~2000 files.

We don't have a server for now, but I can use the services from archive.org and create URLs of the form https://purl.archive.org/foo/bar.

**Comment by danbalogh** [comment]
Thanks, Axelle.

Michaël, I don't think the EpiDoc team is going to make a habit of changing the URI. To be honest, I'm not even sure they changed it this time; my impression (which may be wrong) is that  https://epidoc.stoa.org/schema/latest/tei-epidoc.rng has always, or for a very long time, been the URI, and http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng was rather an alias that is now discontinued. But even if that's not so, I think for the sake of posterity it's better (more transparent) if we use the address at stoa.org.
