### ISSUE TITLE
reliability of https://dharman.in/texts

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#223]
@michaelnmmeyer —

Please check whether your routine for identifying validation errors is set up correctly, because I suspect problems. E.g., the page https://dharman.in/texts/DHARMA_CritEdSiksaGuru indicates dozens of problems, but the file should be clean (it was recently used for generating Aditia's PhD thesis) and indeed validates flawlessly in Oxygen on my end. I will wait with asking team members to clean up their files until you have looked into this matter and explained what's going on.

**Comment by michaelnmmeyer** [comment]
@arlogriffiths

Indeed, there were stale files from another validation pass that used the bare epidoc schema. I just deleted them, it should be OK now.

That said, some validation problems seem to stem from the schema being incomplete rather than the file not being encoded properly, in particular within critical editions. And the files that are validated are not the original ones, but normalized transformations of them I use for convenience. And (finally) there is no auto-update mechanism on "git push" yet, thus some files are not at their latest version.
