### ISSUE TITLE
Appearance of Zotero item type "thesis" in output-html

### ISSUE THREAD

**Issue by wayanjarrah** [erc-dharma/project-documentation#229]
Hi Michaël,

I believe there is a bug with rendering of bibliographic items of type "Thesis" in the output-html. Please see the TF-C item Sarungga: https://erc-dharma.github.io/tfc-nusantara-epigraphy/workflow-output/html/DHARMA_INSIDENKSarungga.html

Here, we include in the apparatus the edition published in the thesis of Nurul Fadilla Budiana with siglum N:

`<bibl n="N">
     <ptr target="bib:NurulFadillaBudiana2021_01"/>
     <citedRange unit="page">47-50</citedRange>                  
  </bibl>`

The short title NurulFadillaBudiana2021_01 is already present in the Zotero Web Library. However, the reference does not render properly in the output, but only the page numbers appear:

<img width="887" alt="Screenshot 2023-09-30 at 3 40 42 pm" src="https://github.com/erc-dharma/project-documentation/assets/40281167/42f98a94-5001-4072-80c6-87447840ebb1">

By contrast, the journal article by Goenawan Sambodo _et al._ appears fine. Is this indeed a problem with the output transformation, and if so, can it be fixed?

Thanks,
Jarrah

**Comment by michaelnmmeyer** [comment]
Dear Jarrah,

This is due to the way bibliographic entries are currently pulled from Zotero. Entries are looked up by tags, not by short name. Thus, for your reference to work, you need to assign it a tag `NurulFadillaBudiana2021_01` in Zotero.

That said, you are right to expect entries to be referenced by their short name. I will address that eventually, but this requires some care.

Best,
Michaël

**Comment by arlogriffiths** [comment]
Thanks Michaël. I have gone ahead and made the change in Zotero. ***@***.***: I have also addded the thesis type, though I haven’t seen this item so please expand/correct as needed, and corrected capitalization of the title.)



Le 30 sept. 2023 à 05:31, Michaël Meyer ***@***.******@***.***>> a écrit :



Dear Jarrah,

This is due to the way bibliographic entries are currently pulled from Zotero. Entries are looked up by tags, not by short name. Thus, for your reference to work, you need to assign it a tag NurulFadillaBudiana2021_01 in Zotero.

That said, you are right to expect entries to be referenced by their short name. I will address that eventually, but this requires some care.

Best,
Michaël

**Comment by wayanjarrah** [comment]
Dear @michaelnmmeyer, thank you for this! I will double check the item @arlogriffiths
