### ISSUE TITLE
Naming a single plate coming from a set

### ISSUE THREAD

**Issue by amandinebricout** [erc-dharma/project-documentation#231]
Dear all, I'm facing an issue : I'm wondering how to name a single plate coming from a set of several plates (the other plates being lost or not yet discovered). I haven't find an answer in the Appendix E of the EGD, so I ask you all. I regularly encounter the designation "a stray plate". @danbalogh tells me that he designates this kind of object by "loose plate". Thanks @michaelnmmeyer's catalog, I found that Natasha also uses "stray plate". What is your opinion on this topic? Thanks in advance for your help, Amandine

**Comment by danbalogh** [comment]
Hello, in the meantime I've also seen Natasja's use of stray plate and have in fact started using the term myself (in internal monologue, not yet in writing).
In titling, I've actually used "single plate" in the one case presently in the VC corpus (00076 Single Bhimavaram plate of a late Eastern Cālukya king). The assumption here is that "single" would not need to be specified in the title if the original inscription was all on one plate, so "single" implies that it's just one piece of a set. Looking back into the Siddham corpus, I've used "loose" once and "single" several times to describe such items; I had probably just followed whatever term the respective earlier editors had used.
I certainly have no objection to your use of "stray plate".
I'm not sure we need a projectwide rule for the term to denote such plates, but if we do, I'm happy to follow the majority decision. If in your experience stray is widely used, then my vote is on that, because my term "loose plate" might also imply one or more plates that form a set (or are thought to form one), but are not (or no longer) bound together by a ring.

**Comment by arlogriffiths** [comment]
I agree with Daniel that we do not need a project-wide convention for this scenario and so I don't think we need a vote.

It may happen that we have 2 or even more plates that have become separated from the main group and that the ones we do have notably no longer include the beginning and end of the text. So "single" will be difficult.

"Stray" also has its downsides because in fact it is the plate(s) that we don't have that would have to be considered most guilty of being "stray". Nevertheless, I am happy for Amandine and anyone else to use "stray" in cases such as these and I think it works also if we have to write "stray plates" in the plural.

**Comment by AnneSchmiedchen** [comment]
I am also in favour of not setting a project-wide convention. I had noticed earlier that Amandine and Natasja were using the term "stray plate". I just would like to add that I have so far used terms like "first plate" or "second plate" when I am sure that this was actually the first or second plate of a charter.

**Comment by amandinebricout** [comment]
Dear all, thanks for your reply. I hadn't opened an issue in order to obtain a project-wide convention, only to know what were your naming practices and if there were any instructions on this topic that I wouldn't be aware of (maybe next time, I will send an informal email instead of creating an issue, I'm never when to use this option). I'm happy to read that "stray plate(s)"  works. I also keep the suggestion to number if possible in mind. As everybody seems to be more or less in agreement, I'll close this issue. Thanks again for sharing your points of view.
