### ISSUE TITLE
allowing use of <supplied reason="subaudible"> in more contexts that EGD so far foresees?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#235]
Dear @danbalogh ,

In Old Javanese, mas or mās means 'gold' while pirak means 'silver'. Amounts of gold or silver are often specified using currency denominations, most often in abbreviated form, e.g. su(varṇa), mā(ṣa), dhā(raṇa), ka(ṭi), ku(paṅ).

A very frequently occurring situation involves a given number (#) of suvarṇas (here a currency unit) of gold, which should be mās su # but is very often written māsu #. That we are dealing with a degeminated spelling (rather than a normal abbreviation of mās) is suggested by the fact that we never find mā meaning 'gold' before abbreviations that don't start with letter s. For instance, we often find mās ku # but never mā ku #.

I am not happy with encoding `<abbr>mā</abbr> <abbr>su</abbr>` because, as stated, this mā is not properly an abbreviation, differently from the abbreviation mā standing for māṣa. And I am not happy with encoding via `<choice>`, whether normalization or correction, because māsu # is very regularly found (while mās· su # does exist, but more rarely): it is neither an error nor anything abnormal. 

I am not sure now how I have encoded other cases of degeminated spelling at word boundary (e.g. -t t- being spelled as a single t), and I don't see any guidance in TG or EGD, but I now feel a preference for using `<supplied>`. If you share that preference, than the question becomes which value to choose for @reason, neither "lost" not "omitted" being adequate. In the current version of EGD, we only foresee the use of "subaudible" in relation to punctuation signs and avagrahas. Do you think it might be suitable for this set of cases?

Arlo

**Comment by arlogriffiths** [comment]
Now I see at the very end of EGD 6.3.4 that we have this example from Old Javanese:

`umula<choice><orig>t</orig><reg>t t</reg></choice>a`

Maybe it's best to just stick to that manner of encoding.

**Comment by danbalogh** [comment]
Hello, several thoughts on this.

1. I very strongly feel that `@reason="subaudible"` should _not_ be used for such a purpose, nor for any purpose beyond what we already do (and even in the case of avagrahas, I'm not really happy with it). It is, after all, a hack of TEI, and the token was clearly meant to be used in transcriptions from audio.
2. From what you say about this case, I would rather classify it as a specific kind of abbreviation, and not as a case of degemination. That is to say, I don't think it should be seen as two abbreviations, one of mās and another of suvarṇa, but rather as a single abbreviation of mās suvarṇa. So I would without hesitation encode `<abbr>mā su</abbr>` or `<abbr>māsu</abbr>`. I gather from your post that you are only flagging, not resolving abbreviations. If I wanted to resolve this, then it would have to be `<expan><abbr>mā</abbr><ex>s</ex> <abbr>su</abbr><ex>varṇa</ex></expan>`, and you may object to this because you say that you don't see mā as an abbreviation of mās. To me that is not a problem, even if in other circumstances mā is an abbreviation of māṣa; what we are encoding in this resolution is that māsu (as a unit) is an abbreviation of mās suvarṇa, and the most economical way of encoding that is to add an s after mā, splitting the unit up. (Sort of like how "i.e." is an abbreviation of "id est" even though "i." on its own can mean other things and does not normally mean "id".)
3. If you are certain that you want to treat this as degemination and encode it as such (with all the added complexity of encoding, displaying and reader-side interpreting normalisation markup within abbreviation markup), then I don't have a strong objection except to note, as above, that this is not what I would choose to do.
4. In that case, both orig/reg and supplied reason omitted are acceptable. The issue of `reason="omitted"` was discussed back in the early days, and the opinion on the Markup list was that omission can be any kind, without any implication of scribal error. We wanted to restrict this markup to restoration of scribal omission, but it is not implicit in TEI. At any rate, as you say, orig/reg is preferable in order to keep our conventions cleaner. And in that case, indeed, the single consonant in orig and the double in reg.
5. So, sticking to orig/reg, encoding an `<abbr>` only within the `<reg>` part does not seem like a good idea to me. Depending on how we (or others in the future) process the text, the reg reading might be ignored. I would, instead, treat it (as I suggest above) as a single abbreviation and nest the choice within the abbr element, e.g. `<abbr><choice><orig>mā</orig><reg>mās</reg></choice>su</abbr>`. 
6. Or, alternatively, I would treat only su as an abbreviation and encode the choice outside it: `<choice><orig>mā</orig><reg>mās</reg></choice><abbr>su</abbr>`

Having thought this through, my recommendation is still 2, and if you have good reason to reject that, then I think 6 is best because it is closest to what you have in mind and does not involve very complicated code.
Let me know how you have chosen and, depending on that, where you think this should be included in the EGD (under abbreviations or under normalisation?)

**Comment by arlogriffiths** [comment]
Thanks a lot Dan. 
Indeed, to keep things manageable, and also because we are dealing with a relatively small number of relatively well understood abbreviations, we have not so far tried to encode expansions.
I have decided to opt for `<abbr>māsu</abbr>`. I do think it would be useful to record this choice in the next edition of EGD.

@wayanjarrah and @ekobastiawan : please implement this choice in files you are (or will be) working on.

**Comment by danbalogh** [comment]
OK, I've put it in the new draft (which is now on the back burner, assuming that Michaël will find the time at some point to give at least a couple of his thoughts on what needs to be revised). I've made it a generic case of using a single wrapper for complex abbreviations such as `<abbr>badi</abbr>` for bahula-divase.
