### ISSUE TITLE
question about use of <milestone unit="fragment" n="..."/>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#236]
Deat @danbalogh !

At the very beginning of the project, @ekobastiawan  had started encoding the rather complicated Kusambyan charter, but he never got far and what he did in 2019 was entirely outdated, so I have just started again from scratch. See [https://github.com/erc-dharma/tfc-nusantara-epigraphy/blob/master/xml/DHARMA_INSIDENKKusambyan.xml](https://github.com/erc-dharma/tfc-nusantara-epigraphy/blob/master/xml/DHARMA_INSIDENKKusambyan.xml). I am sending you the publication by email (as it is still under embargo).

In our published edition, we have numbered all consitutive fragments and numbered also the lines on the given fragment, to aid the reader in matching fragment-lines with our dozens of images.

Our schema does not protest when I represent our published edition quite literally, with tags like this `<milestone unit="fragment" n="10.1"/>`. But no such encoding practice is explicitly allowed in EGD and I suspect there might be objections to it.

What do you think?

**Comment by danbalogh** [comment]
OK, I think I have managed to grasp the situation. So the basic procedure envisioned in the EGD for such a case would be simply to use `<milestone unit="fragment" n="10"/>` at every time where a line (of the inscription as a whole) enters the territory of fragment 10. But I see why in this complicated scenario you would want to indicate the specific line numbers per fragment, and agree that the best way to do that is what you propose (rather than to add more `<lb/>` tags).
If you'd like the Guide to cater explicitly for such a possibility, I think it could well be inserted into §3.6.3 after the point that says "the number referring to every zone of text should be unique, but, as noted above, gridlike milestones with a given combination of @unit and @n will normally be iterated several times in a document, namely once in every line that touches the zone to which that combination pertains".
Let me know if you'd like me to make that addition.

**Comment by arlogriffiths** [comment]
Thanks. Yes, please make that addition. You may want to adjust the example to make it comply withg the recommendation that lower case Latin letters be used to number fragments.

By the way, a bit further down in EGD 3.6.3, we write "in addition to the generation of titles, this attribute [@n] may be utilised for internal references that can be processed by a computer". Is that actually possible, if multiple instance of the same value may occur in a document?

**Comment by danbalogh** [comment]
Done (in the v3 draft only).
For the other question: certainly possible in some way; I'm not sure how feasible or efficient it would be. I guess the output would be a list of milestones with a certain combination of unit and n, rather than a single locus in the text; and the querying method to get this may be different from how one might query a unique item. I notice that we or I were mindful, when writing the first EGD that this may or may not be feasible. The corresponding line under 3.5.4 (on pagelike milestone IDs) says "will be utilised" while this one says "may be utilised", which seems to be deliberate. [But actually, there's also some sloppiness here, as there is a second iteration of the same thing within 3.5.4 with "may be utilised". I have now cleaned this up in the v3 draft, and also changed "will" to "may".]
So anyway, using gridlike milestones for automated reference may or may not be a good idea, and if you prefer not to say this in the guide, I don't mind taking that line out.
