### ISSUE TITLE
encoding of <milestone unit="fragment" n="..."/>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#237]
@danbalogh —

I am now encoding a stone inscription which is fairly neatly broken into two, with a crack from top to bottom. Every line hence is interrupted by the crack, and so I encode `<milestone>` in every line. However, the crack often falls precisely on or in an akṣara.

examples:

1. `piṅul· <milestone unit="fragment" n="2"/> <unclear>hu</unclear>ler·`

<img width="536" alt="Capture d’écran 2023-12-17 à 08 19 32" src="https://github.com/erc-dharma/project-documentation/assets/835603/e00bbe22-c823-4276-8220-163045816f9c">

2. `Ika<unclear>na</unclear><milestone unit="fragment" n="2"/><unclear>ṁ</unclear> patiḥ`

<img width="376" alt="Capture d’écran 2023-12-17 à 08 22 31" src="https://github.com/erc-dharma/project-documentation/assets/835603/6ad0302c-c10f-4b2f-b149-f83507769c7e">

You see that in the case of naṁ (ex. 2), I have inserted the milestone inside the transliteration in a way that seemed meaningful. But this is not possible in the case of hu.

Do you think in our EGD we could furnish any guidance on where to position `<milestone>` in relation to the strings of transliteration letters, or at least show the problem with a few such examples and say the encoder must choose a solution even if a perfect one is often not going to be available?

**Comment by danbalogh** [comment]
Hmm, interesting question.
Reading this, I had a vague memory that we did have some guidance for such cases, but this is apparently not the case. My recollection may be of something I encoded for Siddham, and not of something written in the guidelines.
So please bear with me for some thinking aloud.
First off, I am pretty strongly of the opinion that we should not attempt to place the break inside what is a single akṣara in the original, not even in naṁ. I would only do that with visargas and with anusvāras that are placed cleanly between akṣaras rather than on top of one. Otherwise, I think it is best to leave the akṣara alone. No hard reasons why, but my overall feeling is that there is no real advantage to splitting things off.

I think the best thing to do would be to make an arbitrary decision for each such line and encode the entire akṣara on the side of the break where it makes better sense, based on the factors of relative size, relative distinctiveness (for recognising the damaged character), and even convenience (e.g. put the whole word on one side of the break if the alternative is to break off the first or last character of a word).

If we really wanted some way of encoding what is going on in such cases, we could perhaps tweak our use of ⌈ left ceiling and ⌉ right ceiling (EGD §4.1.4), since the phenomenon does match "Complex characters split by an intervening feature" pretty well. So one of these markers could be added on the other side of the break with the sense that "part of the character after the break is on this size" However, I think the spirit in which that section was conceived was different: it is meant to cater for deliberately split characters and the encoding was meant to highlight (make searchable) scribal quirks around defects and line breaks. Also, I see those placeholder characters as a stopgap solution for something that should ideally be handled through XML markup, and I'm not happy to increase the scope of their use. But I am not dead set on this if you think it's a good idea to expand the use of those characters.

So, if you agree with my proposal to just arbitrarily assign the akṣara to either side of the break, then I'll write that up in EGD §3.6.4 "Gridlike partitions interrupting words". Depending on your opinion on the left and right ceiling placeholders, I'll also make an addition to §4.1.4, either to make it explicit that they are not to be used in such cases, or to explain how they are to be used in conjunction with a milestone inside a character.

Another note: gridlike milestones should take `break="no"` just like other elements of the milestone class when they are inside a word.

**Comment by arlogriffiths** [comment]
@danbalogh —

Sorry for having fogotten to respond earlier. I completely agree with your proposal to just arbitrarily assign the akṣara to either side of the break, and I also agree that we should not expand the scope of our usage of left and right ceiling placeholders.

Please make the necessary changes to EGD and close this issue.

**Comment by danbalogh** [comment]
Done.

**Comment by danbalogh** [comment]
@arlogriffiths , one thing I missed back when this issue came up was that you are supposed to add `@break="no"` on your milestone when it's inside a word (§3.6.4 in the old EGD). So please go back and do that.
I'm now in the process of revising this section of the Guide and had one more idea: when a milestone is inside a character, we could introduce `@break="character"` or suchlike for cases like this. TEI does not seem to forbid values other than yes and no for `@break` (though our current schema allows only these). We would still need to arbitrarily assign the text to one side or another, and I don't think we want any special display for breaks of this kind, so I'm more inclined to stick to `@break="no"` - I just wanted to mention this option. What do you think?

**Comment by danbalogh** [comment]
Or, instead of introducing a new value for break, we could adopt the solution I now recommend for deliberately split akṣaras in #336 .
