### ISSUE TITLE
Cheetsheat: <g>

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#24]
Dear all, 

To finish a debugging: 
- Could you let me know if you expect something for `<g type="numeral">` or it's association with `<num>`? 
- Can you also let me know if you want oto display and how the `<g type="filler"/>`? 

Thanks,

**Comment by arlogriffiths** [comment]
I think that we don’t expect any particular display. If we have <g type="numeral">abc</g>, then display abc, except if it is possible that fraction such as 1/8 should be displayed as ⅛. A test on presence of / inside <g> should help identify the cases.

Please display <g type="filler"/> as §.

Arlo

**Comment by danbalogh** [comment]
I second Arlo: for the time being, there is no need for anything fancy for these elements. One thing that would be good to have is to add a space before and after `<g type="numeral>` if there isn't already a space there in the XML file, so that if the encoder forgets to type a space, e.g.
`<g type="numeral">100</g><g type="numeral">20</g>3`
we still get 100 20 3 in display and not 100203.
Also, we need no display in our HTML transformation for `<num>`, but in the long run, for the website, we might want e.g. a shaded background for the contents of that element, with a tooltip displaying the @value.

**Comment by manufrancis** [comment]
Fine with me.
