### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by michaelnmmeyer** [erc-dharma/project-documentation#246]
Only about 1/4 of texts use `@rendition` to specify scripts. I suspect it is
because scripts are represented with unreadable identifiers from OpenTheso, as
in `rendition="class:83225 maturity:83213"`. The relevant page on OpenTheso is
https://opentheso.huma-num.fr/opentheso/?idt=th347 (links in the EGD are no
longer valid).

People apparently do not know what they should choose for `maturity`, and there
are scripts for which the available values of `maturity` make no sense (e.g.
"Chinese script"), so we could make it optional.

For script classes, we currently have a hierarchy e.g. `/Brāhmī and
derivatives/southern class Brāhmī/Tamil script/Tamil with Grantha`. This
hierarchy is not apparent in the encoding used in inscriptions, and people can
choose either a class that has children (e.g. "Tamil script") or a class that
does not (e.g. "Tamil with Grantha"). I do not think they see the difference,
if only because the contextual help generated from our schemas does not make it
explicit. Things would probably be clearer if the hierarchy was flattened a bit.

To simplify the encoding, I suggest we allow script names (or ISO 15924 script codes,
when available) in place of integers. For instance, we could have
`rendition="class:Sundanese"` or `rendition="class:Sund"` or even
`rendition="Sund"`, which would then be mapped to the internal id `class:57470` that is
used in OpenTheso.

**Comment by danbalogh** [comment]
Thanks for noticing that the links in the EGD are no longer valid. I've noted this for the next version.

Script maturity is for use only with the class "Brahmi and derivatives" (and its subcategories); for any other script classes it is not optional but "forbidden". For Brahmi, it is mandatory.

For the hierarchy of script classes (and for all other hierarchies in our controlled vocabularies), the idea is precisely that people ought to use tokens from varying levels. In some cases, it is possible to be specific (e.g. Nāgarī), while in others one must be satisfied with a more generic category (e.g. northern class Brāhmī). But there remain many things to improve in these hierarchies, and guidance on their use is sorely lacking. The only guidance is the draft [Memo on controlled vocabularies](https://docs.google.com/document/d/12HypwZj4ym6-SX6T7o8Qwl51gl5k1gvux_iOyJfM2zs) which I sketched up more than three years ago, but some of it is now dated, and it has received only very cursory input from PIs and none at all from metadata experts.

The class "Tamil with Grantha" is in my opinion misleading and should be eliminated, because our metadata sheets now allow recording multiple scripts and grantha characters in a Tamil inscription are, as far as I know, encoded specifically as such. I have pointed this out before (#197), but there hasn't been a response in almost a year.

I also find the need to encode these weird code numbers in our files; fortunately for me, all the inscriptions I work with are in the same script class and almost all of them in the same maturity category, so I just reuse the numbers from texts I encoded earlier. Others have a more difficult time, so if it is feasible to implement a canonical list (or whatever) that would be mapped to our OpenTheso definitions, then this may be helpful. But I don't think doing so is high-priority; I'm sure there are more urgent things to do. I'm also worried about adding yet another layer of complexity to the encoding, and about the difficulty of adding new script classes in the future, which would then have to be done both in OpenTheso and in that canonical list.

ISO script codes have been rejected early on in favour of a vocabulary of our own, primarily because the ISO system, as far as I know, is unaware that history exists, so the code for e.g. Tamil script means the Tamil script used right now for writing modern Tamil, while the code for Brahmi means basically Ashokan Brahmi. So even where an ISO code seems to be available for a script in our texts, the definition does not correspond to what we have.

One question that arises as I think about your suggestion of using a canonical list: if we have one, what then is the advantage of also having a vocabulary in OpenTheso? Is it more interoperable with potential future applications of our texts? Or more easily accessible? Or could we simply get rid of it and use just that list, which would then include definitions and hierarchical relations instead of references to the OpenTheso numbers? It was never really explained to me why we need OpenTheso in the first place.

**Comment by michaelnmmeyer** [comment]
Noted for the use of `maturity`, I will amend the schema accordingly.

The class "Tamil with Grantha" is not used anywhere, so I just deleted it.

Concerning OpenTheso, I would rather not use it at all and have instead a few XML files that describe the same data. OpenTheso has some nice features that make it appealing to librarians in particular (you can borrow a taxonomy from another library's catalog and adapt it instead of creating a new one from scratch, for instance), but this adds a lot of complexity, implementation-wise. In fact, we are not interfacing with it at all for now; language and script names are manually replicated in our schema, and from there into our database.

That said, Adeline seems familiar with it and is in charge of the metadata vocabulary, so it is really up to her. I can write a filter to export the data from OpenTheso into a few files that would then become the "real" authority and that would be tracked by git in `project-documentation`. In any case, the whole thesaurus will need to be imported into our own database at some point, to enable filtering by text type, material, etc.

**Comment by alevivier** [comment]
Opentheso is a software created to manage the concepts and terms that we use to describe a specific domain (in our case, epigraphy). It isn’t used only by librarians, but also by the research community (mainly the French community of course, but very active) in the fields of antiquity and medieval studies to have specific and homogeneous vocubularies to publish digital editions and databases of scientific data.
Using a thesaurus, instead of a simple list of terms, can be appropriate to create standardized reference sources (with URIs, interoperability, etc.) that can be reused by a wider community of researchers, not only to work on our corpora.
In order to create such thing, it would be interesting to gather a large work group to discuss these questions. As Opentheso is a collaborative software, it would have been interesting to use it in this way. So far, after several presentations on thesauri and Opentheso, I haven’t been able to provoke some interests.

If you think that there is no point to use it, I don’t mind to stop giving up this solution. But if we choose to continue as it is, I suggest for the xml edition to change the use of @rendition, according to Michaël’s proposal (e.g. class:sundanese), and maybe using a script to replace the explicit terms by the URIs.
The actual thesaurus can be exported in SKOS or CSV.

**Comment by danbalogh** [comment]
Thanks, @alevivier , for the added information. Deciding whether we stick with OpenTheso should not be up to me but mainly to you in discussion with the PIs and probably Michaël. My amateurish impression is that if we conceive of the life cycle of a vocabulary in the following stages, then the usefulness of OpenTheso varies from stage to stage:

1. Brainstorming, initial planning: OK, but less convenient for collaboration than freeform tools such as Google sheets and docs
2. Finalisation, rigorous design: probably useful
3. Use, allowing for ongoing expansion and revision: potentially useful, but at the cost of greatly increased complexity of processing and integration
4. Dissemination and adaptation to other projects: useful

**Comment by arlogriffiths** [comment]
I am in favor of sticking with OpenTheso. But of course we do need finally to produce some documentation on our vocabularies and on how to use OpenTheso. I don't feel that replacing number codes for concepts by actual words is really necessary, but I am not against it either.

It occurs to me that the batch import of Campā inscription may again be to blame for a percentage of the offending files: they have never been updated to reflect changes in encoding rules after being imported according to an early DHARMA template. Besides that, since we never really finished the discussions about controlled vocabularies, I think we may have forgotten to disseminate to all encoders what decisions we made on encoding things like script class and maturity.

**Comment by arlogriffiths** [comment]
Can we try to come to a conclusion on this matter?

@michaelnmmeyer: 
1. I am not sure you grasped, through Dan's and my responses, that the low rate of actual suage of @rendition in our xml files is due to the fact (if I err not) that the EGD has never made it to its v2, while consequently the template that people are using for encoding new items has never moved to it v4, so that the template simpkly does not contain @rendition in the relevant place and it has not been possible to instruct encoders to revise their files that have been encoded as per v1. 
2. **I think is it urgent to make available v4 of the template and this probably requires lifting the break on Dan finalizing v2 of EGD.**
3. I notice that the system does not record any error at https://dharmalekha.info/errors for files that lack @rendition, e.g. a file I have just committed that still only shows `<div type="edition" xml:lang="kaw-Latn">`. Wouldn't it be helpful if such lacunae were flagged as (non-fatal) errors?

Depending on Michaël's responses to the above, a team will need to be formed to push our documentation on script maturity and classification to released state, and Dan will (with my help) need to reserve time for finalizing the release of EGD v2.

**Comment by michaelnmmeyer** [comment]
@arlogriffiths 

For now, nothing is done to verify that `@xml:lang` and `@rendition` are used properly in `<div type="edition">`. I will add checks for this, but this will only work on the website, because the logic is impossible to express in XML schemas.

**Comment by danbalogh** [comment]
I think most people use the google doc version of the EGD for daily reference, though I may be wrong. At any rate, I too have been wondering recently whether I should return to working on the next EGD release. I think starting soon would make it possible to finish it by summer. I'm planning to take a longer leave from mid/late July and would not mind being done by then. (I'll also be on leave from tomorrow till the end of next week, so if this discussion continues, I will not be a very active participant.)

@michaelnmmeyer : I think Arlo's suggestion was for the schema simply to check whether `@rendition` is present on the edition div, not whether it has an approved (combination of) value(s).
