### ISSUE TITLE
Language codes (table in the appendix of the EGD)

### ISSUE THREAD

**Issue by michaelnmmeyer** [erc-dharma/project-documentation#247]
In ISO 639-3, the proper code for "Undetermined Language" is "und", not
"unknown".

For "x-oldbalinese", we should submit a change request (here:
https://iso639-3.sil.org/code_changes/submitting_change_requests). Apparently,
the language codes "oba" and "obn" are free.

Language codes enumerated in the table belong to ISO 639-3, but "pra" (Prakrit
languages) belongs to ISO 639-5, it designates a family of languages. There are
also individual language codes in ISO 639-3, namely:

	pka	Ardhamāgadhī Prākrit
	pmh	Māhārāṣṭri Prākrit
	psu	Sauraseni Prākrit

Indicate in the table to use "pra" instead of these?

**Comment by danbalogh** [comment]
Practically anything is fine by me as regards language codes. I would also be very happy if this appendix could be removed altogether from the EGD, since it is no more relevant to diplomatic editions than to several other areas of work. It could be replicated in a txt or html file added separately to Project Documentation and linked to from the EGD as well as from anywhere else where these codes are referred to.

For "und", I'm perfectly happy to make the change.

For Old Balinese, it seems to me from the note at the top of the language list in the EGD appendix that the request to ISO was submitted back in 2019. I don't know if there has been any result; perhaps @arlogriffiths does.

The problem with the ISO639-3 Prakrits is that these are specific and relatively clearly defined literary languages. None of these occur with any frequency in inscriptions (though I guess there may be some instances that qualify as one of them). The epigraphic "prakrits", more properly called Middle Indo-Aryan, are indeed a family designation, since it is not possible to assign a more specific name to most of these languages. Is it a problem that some of the codes we want to use are ISO639-3 and others (or one other) is ISO639-5? I don't see the point of indicating that "pra" should be used _instead of_ pka/pmh/psu because the list is supposed to include all language codes that we use. "Prakrit" is on the list while "Ardhamāgadhī" etc. are not. It could, however, be noted for explanation (next to the explanatory notes already at the top of the appendix) that this is what we do about "Prakrit" and this is why.

**Comment by michaelnmmeyer** [comment]
OK for the external table. I will produce one and send you the link.

About the conjoint use of ISO639-3 and ISO639-5, it is fine as long as people do not use overlapping categories like `pra` and `pka`.

**Comment by danbalogh** [comment]
Perfect, thanks. Please add at the beginning of the external table something similar to the notes at the beginning of the EGD appendix, noting also that the individual Prakrits from ISO639-3 should be avoided. If you'd prefer me to write this up, send me a draft of the table when you have it, and I'll add the notes.

**Comment by arlogriffiths** [comment]
@michaelnmmeyer  — I indeed submitted several ISO 693-3 requests in 2019 and again in 2021. I am sending them to you by email. The record of the last accepted change can be viewed here https://iso639-3.sil.org/request/2021-017. Alas, Old Balinese for some reason escaped my attention. I suppose I failed to submit a request for Old Balinese because at that time (and until this moment, I suppose) none of our inscriptions is in Old Balinese. But this could change fairly soon, or occur after DHARMA is over but when we will still be husing the DHARMA infrastructure. So indeed let's submit such a request.

Frustratingly, the name "Old Javanese" does not even appear in the accompanying data for code "kaw" in ISO 693-3. One is apparently just supposed to know that Kawi is a (less scholarly, less standard) name for the same language as Old Javanese. Maybe we can get them to add "Old Javanese" under "Langua Name(s)" here https://iso639-3.sil.org/code/kaw.

For the rest, I agree with everything Dan has said. I recommend formatting the authority file for language codes in a manner analogous to the ones for project participants and prosodic codes, i.e. in XML, and storing them in the same location, so everything can edit it is needed.

**Comment by michaelnmmeyer** [comment]
Noted for the ISO change requests.

I will create an XML file and make it visualisable.

**Comment by michaelnmmeyer** [comment]
I added a languages table in ac12435eef47b8ed72a7df5eb680d730811355af.

**Comment by danbalogh** [comment]
Thanks. Will there be a static HTML page to display this? Or should I simply link to https://github.com/erc-dharma/project-documentation/blob/ac12435eef47b8ed72a7df5eb680d730811355af/DHARMA_languages.tsv where language codes are mentioned in the EGD?

**Comment by michaelnmmeyer** [comment]
I think we can just link to Github, through https://purl.org/dharma/languages-list (I will modify the link target later on if need be). This way, people know which file they need to edit. But I can generate an HTML page if you prefer.

**Comment by michaelnmmeyer** [comment]
I reserved a PURL domain for us because we do not have yet a "final" domain set up and because Arlo needed something to work right now. There are only a few allocated URLs, see: https://purl.archive.org/domain/dharma.

I am not sure it is worth it to keep allocating PURLs in the future. What matters ultimately is that we own the domain name we are using, so that we can set up a redirection whenever needed (if we decide to move files around or if Github, Zotero, etc. decide to change their addressing scheme).

**Comment by danbalogh** [comment]
I see. In this case the EGD might as well link directly to GitHub. Or what would you suggest?

**Comment by michaelnmmeyer** [comment]
For the guide itself and documents of this kind, I think using Github URLs is fine (at least until the end of the project). Doing that in a research paper is more problematic.

**Comment by danbalogh** [comment]
Thanks. I'll stick to the github URL in the EGD then.

**Comment by danbalogh** [comment]
I think this issue can be closed now, but I'll leave it to @michaelnmmeyer to check once again if there's anything unresolved here.
