### ISSUE TITLE
Reference to ARIE

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#26]
Dear all, I have been thinking about the way to refer to the Annual Report on Indian Epigraphy.
I have first looked at the way it was done in EIAD, that is:
```
<bibl>
  <ptr target="eiad-bibl:zoteroItem_G9CH6AGA"/>
  <citedRange>1962-63: no. B.147</citedRange>
</bibl>
```
Display = ARIE 1962-63: no. B.147

For DHARMA, I see 2 options:

**Option 1**
```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange unit="year">1904-1905</citedRange>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B. Stone inscriptions copied in 1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```
**Option 2**

```
<bibl>
  <ptr target="bib:ARIE1904-05"/>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B. Stone inscriptions copied in 1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```

Even though option 1 is more straighforward (one zotero entry only for ARIE), I favour option 2, which allows us to record the orginal title of the different issues or ARIE (which is a name retrofitted for the early ARIEs), but implies one zotero entry per ARIE.
I am ready to zoterised the approx. 130 zotero entries for ARIE.
See already repository "E-ARIE" on zotero.

Any opinion on the choice between option 1 and 2?
Any suggestion for other options?

@danbalogh: option 2 requires a new value for @unit, that is "appendix", while option 1 implies further the value "year".

@arlogriffiths: what would be the item Type for ARIEs in zotero? "Book", I guess, rather than "Report" (ZG says about Report: "for various kinds of grey literature not easily classifiable otherwise").

**Comment by danbalogh** [comment]
Dear Manu, a similar issue has been discussed recently, and the outcome was that publications of this type would be encoded as a single Zotero item, and the reference would include the year. See Zotero Guide §4.4, and the example of the _Notulen van de Algemeene en Bestuurs-vergaderingen van het Bataviaasch Genootschap van Kunsten en Wetenschappen_ there; see also EG §10.4/Bibliographic citations, under "serial publications recorded as a single Zotero entry", and examples 4 and 5 below that.
That said, my personal preference is also to have such publications recorded in Zotero as separate book-type entries for each item, and if you are willing to undertake the work of creating those entries, then I don't think anyone is going to veto that. Let's see what Arlo says.
I don't think any addition or change to the EG is required. If you decide to go with option 1, then instead of citedRange unit="year", use the method described in the EG (reference above). I don't recall why we decided to do it like that, but I think it follows Axelle's recommendation. And if you prefer to go with option 2, "appendix" is already available as a @unit in the EG. (However, I would prefer not to include "Stone inscriptions copied in 1905" in the citation, just "B".)

**Comment by manufrancis** [comment]
Thanks, Dan.

My mistake. I consulted the ZG V01.1.1, not the googledoc.

As for including "Stone inscriptions copied in 1905" in the citation for appendix, not just "B", my reasons are that upto ARIE 1926–27, ARIEs (which are on two calendar years) generally contain:
* an appendix A for copper plates copied in 1926-27 (i.e. 2nd semester of 1926 to 1st semester of 1927)
* an appendix B for stone inscriptions copied in 1926 (2nd semester) (continuing the individual numbering from appendix C of previous ARIE, thus starting for example at inscription 256)
* an appendix C for stone inscriptions copied in 1926 (1st semester) (continued in appendix B of next ARIE).

Another example: in ARIE 1962-63, there is an appendix C "Pre-1945-46 collections"

In secondary literature for Tamil epigraphy it is usual to refer to an inscription (a stone inscription implicitly) as, e.g. "n° 256 of 1921".
This is not very precise, as with such a reference, the reader does not know if this inscription is in appendix C of ARIE 1920-21 or in appendix B of ARIE 1921-22.

Conversely, if you refer to an inscription as "ARIE 1920-21, p. 47, appendix B, n° 235", the reader does not know at once when the inscription was copied.

**Comment by ajaniak** [comment]
Dear All, 

@manufrancis, sorry several points are still under revision, that's why a new version for Zotero guide hasn't been published yet. 

Option 1 or 2, it is the same for me regarding codes and routines. 
The choice for option 1 was made mostly because it seems to require less work on Zotero data. You should discuss that with @arlogriffiths , but I am ok about changing it. 

Regarding added "Stone inscriptions copied in 1905", I understand the need, but it still can't be encoded inside the `<citedRange>`.  I guess the `<title>` tag could do with an `@level` attribute. Or it would require adding the appendix itself inside Zotero so I can retrieve the title, but it means changing the single Zotero item system and declaring ARIE as book to be able to declare the appendix as a simple book chapter to be consistent.

**Comment by danbalogh** [comment]
This question is primarily to +axelle: if Manu needs to include the text in the citation, is there anything wrong with 
```
<bibl>
  <ptr target="bib:ARIE1904-05"/>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B</citedRange>. Stone inscriptions copied in 1905
  <citedRange unit="item">50</citedRange>
</bibl>
```
i.e. not using `<title>` but simply mixing text with `<citedRange>` elements?

**Comment by manufrancis** [comment]
In the meanwhile, if you want to know more about the ARIEs, see
https://dharma.hypotheses.org/arie

**Comment by arlogriffiths** [comment]
Dear Manu: nice item on the Blog!

Regarding the issue at hand:

1. the main thing I would like to ensure is consistency across the DHARMA-base. In other words, our decision should not only be taken with ARIE in mind, but with all other publications that need to be references in similar manner, and hence with consideration of the amount of work will be required to create volume-level zotero items not only for all ARIE volumes, but for all 'journals' in question. (Re. TF-C, I think there would be 2 or 3 journals to be zoterised a volume-level.)

2. I am certainly not going to vote against any solution that satisfies Manu's desire for bibliographic accuracy, and am happy to follow majority opinion, although I want us to at least consider alternatives. 

3. Since we will be offering all ARIE's in digitized form via DHARMA-base, anyone who has a reference of the type "ARIE 1962-63: no. B.147", or, better with page-specification, "1962-63: 68, no. B.147" will be able to locate the relevant item in a .pdf or .txt/xml representation of the contents of ARIEn 1962-63, using the value for "year", "page", "appendix" and "item" that are implicit in this human-readable representation. So a minimalist solution could be

```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange>1962-63: 68, no. B.147</citedRange>
</bibl>
```

This would follow the example of EIAD very closely, merely adding the page specification in human-readable form.

4. I think the reader who needs to know in which year "ARIE 1920-21: 47, B.235" was copied can look up the page and item to find out. Do we need to do the work for that reader? If we do, then that too could be done in human-readable form:

```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange>1920-21: 47, no. B.235/1920</citedRange>
</bibl>
```

(I haven't checked the year, I am just filling in 1920 by way of example.)

5. Do we need machine-actionability at a greater level of detail? If yes, of course we can go as far as Manu proposes or decide to settle for the level of detail assumed in the current drafts of EG and ZG. Assuming that Axelle confirms the acceptability of Dan's variant, proposed yesterday, of Manu's Option 2, then I can offer an analogous variant of Manu's Option 1:

```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange unit="year">1904-1905</citedRange>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B</citedRange>. Stone inscriptions copied in 1905
  <citedRange unit="item">50</citedRange>
</bibl>
```

6. To sum up my questions:
- is the level of detail that Manu proposes worth the effort (and can we expect our encoders to follow Manu's model consistently)?
- if yes, then do we need all this detail in machine-actionable form, or can we be content with the human-readable representation that I have proposed under 3?

7. If we opt for the human-readable solution, then some rewriting of EG will be required to introduce more tolerance for exclusively human-readable representation. (Daniel has urged for this a few times in our discussions, so far I have resisted, although you see that I am now opening myself up to less insistence on machine actionability.)

**Comment by ajaniak** [comment]
The solution 5 is acceptable, but a little weird because of exception in a very structured data model.

**Comment by arlogriffiths** [comment]
Then I can propose these four choices:

1. Variant of Manu's Option 1:
```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange unit="year">1904-05</citedRange>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B-1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```

2. Variant of Manu's Option 2:

```
<bibl>
  <ptr target="bib:ARIE1904-05"/>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B-1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```
3. Exclusively human-readable variant of Manu's Option 1:
```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange>1904-05: 32, B-1905, 50</citedRange>
</bibl>
```
4. Exclusively human-readable variant of Manu's Option 2:
```
<bibl>
  <ptr target="bib:ARIE1904-05"/>
  <citedRange>32, B-1905, 50</citedRange>
</bibl>
```

**Comment by danbalogh** [comment]
I think option 1 does not work, because as per the current EG, instead of year as the @unit of citedRange, we need a `<date>` element. I don't want to waste time trying to look up our previous discussion on that, but there was a discussion, and the proposal to use <date> was not mine. I am not repeating it here because I want it, but because I have accepted it and it is in the EG. At any rate, option 1, if you need it, should look like this:
```
<bibl>
  <ptr target="bib:ARIE"/>
  <date>1904-05</date>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B-1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```
compare Example 5 in EG §10.4/Bibliographic citations.

As Arlo has mentioned above, I am in favour of less rigorous encoding and believe that we don't need machine-actionability on the details. So my preference is for 3 or 4 (in Arlo's latest list above). And the choice between 3 or 4 (i.e. Manu's options 1 and 2) should be made by the PIs on the basis of the considerations mentioned above by Arlo.

**Comment by manufrancis** [comment]
Would this be OK for all?

```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange>1904-1905: 32, Appendix B/1905/50</citedRange>
</bibl>
```

**Comment by manufrancis** [comment]
Would this be OK for all?

```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange>1904-1905: 32, Appendix B/1905/50</citedRange>
</bibl>
```

To displayed as:
ARIE 1904-1905: 32, Appendix B/1905/50

**Comment by arlogriffiths** [comment]
We have to take this decision as part of a more general decision on how to encode `<bibl>`.

In our discussions about the EG, I have been resisting @danbalogh 's arguments in favor of less structured use of `<bibl>`, because I fear that less structure will mean more inconsistency between encoders or even on the part of a single encoder.

Therefore, I would still favor my suggestion 1 of 4 days ago ("variant of Manu's Option 1"):

 ```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange unit="year">1904-05</citedRange>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B-1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```
It could be displayed like this

ARIE 1904-05: 32, Appendix B-1905, no. 50

Of course instead of the hyphen in the value of @unit="appendix", we could also use Manu's slash, so B-1905, to get the following display:

ARIE 1904-05: 32, Appendix B/1905, no. 50

**Comment by AnneSchmiedchen** [comment]
Dear Manu,
In the light of this discussion, what should be the default then for ARIE after 1926-27, where we apparently do not have this separation in Appendix B anymore, and what about Appendix A (copper plates), where I also do not recall this separation right from the beginning? Can we have the short version (more EIAD-like) there?

**Comment by manufrancis** [comment]
**Answering to Arlo's last comment:**

Let us go then with a very structured option, that is:

```
<bibl>
 <ptr target="bib:ARIE"/>
 <citedRange unit="year">1904-1905</citedRange>
 <citedRange unit="page">32</citedRange>
 <citedRange unit="appendix">B/1905</citedRange>
 <citedRange unit="item">50</citedRange>
</bibl>
```
I prefer "B/1905" rather than "B-1905".
I prefer "1904-1905" rather than "1904-05".
Would not "1904-1905" be preferable to "1904-05"?

Display:

> ARIE 1904-1905: 32, Appendix B/1905, no. 50

And I suggest we **add this in the XML template**. Very easy then to update the `<bibl>` or simply delete it, when creating the XML file of a particular inscription.
If not in DHARMA template, it will be in TFA template, as most Tamil inscriptions are referred to in ARIE.

**Answering to Annette's last comment:**

* default then for ARIE after 1926-27, where we apparently do not have this separation in Appendix B anymore?

```
<bibl>
 <ptr target="bib:ARIE"/>
 <citedRange unit="year">1935-1936</citedRange>
 <citedRange unit="page">8</citedRange>
 <citedRange unit="appendix">B/1935-1936</citedRange>
 <citedRange unit="item">1</citedRange>
</bibl>
```
Display:

> ARIE 1935-1936: 8, Appendix B/1935-1936, no. 1

We could be satisfied too with 
`<citedRange unit="appendix">B</citedRange>`
But I would advise to be explicit OR to make optional, only in case the year of the ARIE exactly corresponds to the dates of the appendix, the encoding of  "B/1935-1936".

* and what about Appendix A (copper plates)?

```
<bibl>
 <ptr target="bib:ARIE"/>
 <citedRange unit="year">1935-1936</citedRange>
 <citedRange unit="page">5</citedRange>
 <citedRange unit="appendix">A/1935-1936</citedRange>
 <citedRange unit="item">1</citedRange>
</bibl>
```
Display:

> ARIE 1935-1936: 85, Appendix A/1935-1936, no. 1

Again we could be satisfied too with 
`<citedRange unit="appendix">A</citedRange>`
But I would advise to be explicit here too OR to make optional, only in case the year of the ARIE exactly corresponds to the dates of the appendix, the encoding of "B/1935-1936".

Finally, as the letters do not indicate explicitly the content of the appendix (e.g. appendix A in ARIE 1902-1903 = stone inscriptions copied in 1902 [second semester], while from ARIE 1905-1906, appendix A is regularly (always, I guess) copper-plates), I suggest we add, **as optional**, a specification of the content of the appendix.
`
<citedRange unit="appendix">A/1935-1936<note>List of copper-plates examined during the year 1935-36.</note></citedRange>`

@ajaniak What is your opinion, notably concerning?
* "1904-1905" instead of "1904-05"
* the `<note>` in `<citedRange unit="appendix">` (regarding the complexity of the transformation, if we want to display it)

**Comment by danbalogh** [comment]
Has anybody read my comment above?
> 
> 
> I think option 1 does not work, because as per the current EG, instead of year as the @Unit of citedRange, we need a `<date>` element. I don't want to waste time trying to look up our previous discussion on that, but there was a discussion, and the proposal to use was not mine. I am not repeating it here because I want it, but because I have accepted it and it is in the EG. At any rate, option 1, if you need it, should look like this:
> 
> ```
> <bibl>
>   <ptr target="bib:ARIE"/>
>   <date>1904-05</date>
>   <citedRange unit="page">32</citedRange>
>   <citedRange unit="appendix">B-1905</citedRange>
>   <citedRange unit="item">50</citedRange>
> </bibl>
> ```
> 
> compare Example 5 in EG §10.4/Bibliographic citations.

**Comment by danbalogh** [comment]
I've now looked up the old discussion about this. The last word on it was Arlo, comment in the EG, 20 January, quoted below:

> after discussion with Axelle, we propose to use `<date>` for the year. examples:
> `<bibl><ptr target="bib:NBG"/> <citedRange unit="volume">8</citedRange> <date>1870</date> <citedRange unit="page">72, 78</citedRange></bibl>`
> this would be displayed something like
> NBG 8, 1870: 72, 78
> `<bibl><ptr target="bib:OV"/> <date>1918</date> <citedRange unit="appendix">Q</citedRange><citedRange unit="page">169</citedRange></bibl>`
> this would be displayed something like
> OV 1918: Q, 169
> Dan: Please integrate the examples into the EG.
> Axelle: Please add information in ZG about how to create Zotero entries for Journal abbreviations that need to be cited in XML files.

To this, I replied on 21 January:

> @Arlo and @Axelle, I assume that you have discussed and rejected the option of recording separate Zotero entries for each year of these publications, as well as the option of <citedRange unit="date"> or "year" for this case. If you have, all good. If you have not considered the latter, how about it? If a genuine <date> element is not required here for processing reasons, it may be simpler and more intuitive to treat the year as part of the specification of the cited range.
> At any rate, I've done the necessary changes, so if you reject <citedRange> and @unit, then this thread can be resolved.

Having received no reply, I closed the comment thread on 10 February.
But now everybody seems to be saying we should use `<citedRange unit="year">`.

Is there a particular reason why you are proposing something different from what I was explicitly instructed to write in the EG and ignoring me when I point out that this proposal is contradictory to the EG (and incidentally agrees with what I mentioned as a possibility in January, but which was ignored then)?

**Comment by manufrancis** [comment]
Dear Dan, thanks for finding the earlier discussion.
The reason I was proposing something different is that I was influenced by and probably willing to comply to Arlo and his obsession with bibliographical accuracy.
I have in the meanwhile exchanged with Axelle.
From these exchanges I conclude that:

(1) the best and more accurate option would be 1 zotero notice per ARIE.
(2) the solution with several `<citedRange>` is problematic because the date is recorded in a `<citedRange>` (this is not forbidden by TEI, but not done in actual practice)
(3) the solution with one `<citedRange>` only complies with two desiderata, that is, uncomplexity of encoding and legibility for human-reader (as we do not need machine-actionability here).

THUS
```
<bibl>
  <ptr target="bib:ARIE"/>
  <citedRange>1904-1905: 32, Appendix B/1905, no. 50</citedRange>
</bibl>
```
@arlogriffiths @AnneSchmiedchen Do you, PIs, agree?

**Comment by arlogriffiths** [comment]
I repeat my words: :In our discussions about the EG, I have been resisting @danbalogh 's arguments in favor of less structured use of `<bibl>`, because I fear that less structure will mean more inconsistency between encoders or even on the part of a single encoder."

If we don't mind inconsistently in the way ARIE references are presented, then Manu's latest proposals is fine. If, as I think we should, we do mind, then 

- let us accept Axelle's methodological opinion and the preference voiced by more than one of you to create 1 zotero item per ARIE volume (and per volume of other relevant "journals" — NBG, OV, etc.).
- and let us adopt the following scheme, already proposed above, or some equivalent but equally structured alternative:

```
<bibl>
  <ptr target="bib:ARIE1904-05"/>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B-1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```

**Comment by manufrancis** [comment]
OK ;-)

I am in favour of Arlo's final proposition.

EXCEPT: 1904-1905 instead of 1904-05. (If I am not wrong, ZG requires full years).

And will, as earlier suggested, take the brunt of zoterise the full ARIE collection.
NB1: This might take some time, but it is easy even without zotero entry to coin the <bib:>.
NB2: For the very early ARIEs, e.g. ARIE 1887-88 to 1890-91, we will have have several tags, e.g. ARIE1887-1888_01, ARIE1887-1888_02, ... I will zoterise those ASAP.

**Comment by manufrancis** [comment]
To sum up 
* after checking ZG @ short title / date block (4.10.2: "This block may be either a single four-digit year, or, for intervals of years, the first and last year separated by a hyphen. So, e.g., 1997-1998, 1982-1993, 1999-2003) and 
* advocating for "/" instead of "-" in `<citedRange unit="appendix">` because we will need sometimes "C/1945-1946" (nicer than "C-1945-1946").

```
<bibl>
  <ptr target="bib:ARIE1904-1905"/>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B/1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```

```
<bibl>
  <ptr target="bib:ARIE1962-1963"/>
  <citedRange unit="page">157</citedRange>
  <citedRange unit="appendix">C/1945-1946</citedRange>
  <citedRange unit="item">1</citedRange>
</bibl>
```

**Comment by manufrancis** [comment]
Sorry!
Closed by mistake.

**Comment by arlogriffiths** [comment]
I am fine with this proposal.

**Comment by AnneSchmiedchen** [comment]
I am also fine with this proposal.

**Comment by danbalogh** [comment]
Great. I've added an Example 8 to the EG (end of §10.4/Bibliographic citations).

**Comment by arlogriffiths** [comment]
May I now propose introduction of a new letter code J (for Journal) in our Zotero Group, rename E-ARIE to become J-ARIE, and created J-NBG next to it? For any other 'journals' that need to be zoterised, parallel collections can be added.

@ajaniak : could you draft the necessary rewrite in the gdoc for the ZG?

**Comment by ajaniak** [comment]
Done

**Comment by manufrancis** [comment]
Thanks all of you!
I now close this issue.
