### ISSUE TITLE
Suggested reorganisation of dharmalekha menu

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#265]
After discussion with @AnneSchmiedchen and @manufrancis , I would like to recommend some changes to the front-end appearance of dharmalekha.info. I think it is important that that pages meant for project members and contributors should be separated from pages meant for a wider audience, and be made less visible and accessible. A less critical issue is that several of the items in the horizontal main menu are misleading. At the moment, an outsider who visits the page is likely to click on "Texts" - where they will not see a list of our texts, but a list of our errors (as implied by the bug icon next to this item), and on "Documentation" where they will see insider notes on how the site works rather than documentation meant for the public.

So:
For the project-internal stuff, implementing access control would probably be too much work and we don't need to keep things secret, but I think that "Texts" and "Documentation" should not be on the main menu, but accessible only from a subpage called "Members only" or "Project internal" or suchlike on the main menu. "Texts" should be called "Bugs" or "Errors" or suchlike and "Documentation" should perhaps be renamed "Site documentation" or "Technical documentation".

The bibliography page, as it stands at the moment, is not useful for the public, since it can only list our complete Zotero database, including the incomplete and wrong records, in alphabetical order. Until and unless this changes (and I don't think it is a priority to change it), this page should also be hidden from the public eye. (As a side note to this: in the displayed editions, clicking a bibliographic reference currently takes to the bibliography division and puts a highlight on the cited item. BUT the files can also contain citations that are NOT in the bibliography div; clicking one of these does nothing at the moment, since the link points to a non-existent bookmark in the HTML. I assume this is a work-in-progress thing and at a later point, these links will be clickable and take us to the details of the bibliographic item, and/or display those details in a tooltip. This is not urgent as far as I am concerned.)

As for the items most visible to the public, the menu item/page "Catalog" should be called Search (there's no need to rename the URL component, just the menu item and the page). It is already indicated by a magnifying glass icon and what it does is search the collection (displaying the list of all texts without a search parameter is not useful - it's OK to have it there by default, but no end user will be interested in that). There should also be a prominently visible page that explains the brackets etc. of our editorial conventions. This can, for the time being, be simply a copy of https://erc-dharma.github.io/editorial.

**Comment by michaelnmmeyer** [comment]
I concur with everything, except that I would rather rename "Catalog" with "Texts" instead of "Search", because we have several search interfaces and will likely have more in the future (for the bibliography, etc.). Accordingly, I would like to relocate the current catalog interface from https://dharmalekha.info/catalog to https://dharmalekha.info/texts. 

Likewise, I plan to relocate displayed texts from https://dharmalekha.info/display/DHARMA_INSVengiCalukya00003, etc. to https://dharmalekha.info/texts/DHARMA_INSVengiCalukya00003, etc. These new URLs will be definitive. This answers your question in #263.

For the bibliography, the feature you are talking about is already implemented. See for instance https://dharmalekha.info/display/DHARMA_INSIDENKAlasantan, and click on the reference Zoetmulder 1982. This brings you to [the appropriate location](https://dharmalekha.info/bibliography/page/179#bib-key-KLAFLPWV) in the global bibliography.

When the tooltip of a bibliographic reference says that the entry is not found, this means that the entry is not found in our global Zotero bibliography. Entries are looked up by short title, so this field must be present.

**Comment by danbalogh** [comment]
Thanks. I have no objection to using "Texts" for the current Catalog page (but perhaps then change the icon from a magnifying glass to something else? Or call it "Text search"/"Search texts"? Not important, though.)
Glad to hear about the bibliography working. The reason I thought it did not work was that it does not work when a third-party translation is referred to in the title of a translation. E.g. https://dharmalekha.info/display/DHARMA_INSVengiCalukya00010 - if you go to the Translation into French by [Estienne-Monod 2008](https://dharmalekha.info/display/DHARMA_INSVengiCalukya00010#bib-key-ZX6D3292), it will try to take you to a HTML bookmark on the same page that does not exist.

**Comment by michaelnmmeyer** [comment]
Indeed, this is a bug. Thank you for noticing!

**Comment by michaelnmmeyer** [comment]
New menu organization done in https://github.com/michaelnmmeyer/dharma/commit/86562e72e9efc1ad6c4582828d4e48329c6b0513. It still remains to fix the bibliography-related bug.

**Comment by arlogriffiths** [comment]
At this time, the search box is not operational. E.g., typing "Alasantan" yields no result.

<img width="750" alt="Capture d’écran 2024-03-26 à 06 31 28" src="https://github.com/erc-dharma/project-documentation/assets/835603/e3ce2b52-95e5-447e-85f9-fe0101785003">

**Comment by michaelnmmeyer** [comment]
Thank you, corrected.

**Comment by arlogriffiths** [comment]
great, thanks
