### ISSUE TITLE
Link to full XML edition from inscription display on dharmalekha

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#266]
Another suggestion/request has occurred to me. I notice that when an inscription is displayed on dharmalekha.info, e.g. https://dharmalekha.info/texts/DHARMA_INSDk00029, then the XML tab shows only the contents of the `<body>` element. I'm OK with that, since our TEI headers aren't very well populated, but I think it would be best to also offer a link to the actual XML file here. The "Identifier" displayed above the edition could perhaps be a link to the same file on GitHub? Simultaneously, the "Repository" shown here could also link to the repository on GitHub.

**Comment by michaelnmmeyer** [comment]
OK, noted.

**Comment by arlogriffiths** [comment]
I agree with hyperlink to github repo for the information behind the category Repository.

However, adding a hyperlink to the xml file through Identifier then seems a bit redundant to me, and also partly wrong because inscription identifier is not the same thing as xml file.

However, it may not be superfluous to include the teiHeader in what is shown behind the XML button...

**Comment by danbalogh** [comment]
I don't understand the objection. What is the purpose of the identifier if not identifying the XML file? Are you saying that the identifier identifies the text as an abstract entity, and only with the .xml extension does it become the identifier of the file? I think that's a needless sophism.
Also, if we aren't linking directly to the XML file on github, then showing the TEI header is imo not sufficient; we need to offer a download of the XML file.

**Comment by arlogriffiths** [comment]
can this be closed now?

**Comment by michaelnmmeyer** [comment]
We have a button for downloading the XML file in the sidebar, so I guess this is OK.
