### ISSUE TITLE
display of <g type="squiggleVertical">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#268]
@michaelnmmeyer —

I had a look at https://github.com/erc-dharma/project-documentation/commit/194e2efe21b8ccee532ff0e8b054c058c204d572. I am not sure but I have the impression that your gaiji file mentions but proposes no display for @type"squiggleVertical".

There is a long record of discussion in the gdoc https://docs.google.com/document/d/1glfyQnFqPrbVOYzegfjKIOVrc-vMgznEQ1iNsFf7DE8/edit that I have no time to look into thoroughly now. But can we use § in the display instead of the space-consuming display we have at the moment? See screenshot from https://dharmalekha.info/texts/DHARMA_INSIDENKAirKali.

<img width="289" alt="Capture d’écran 2024-03-28 à 09 24 45" src="https://github.com/erc-dharma/project-documentation/assets/835603/e642c8ad-22d0-46de-8ea5-2686ce4cb07a">

Please wait for @danbalogh to react before implementing anything.

**Comment by danbalogh** [comment]
I would suggest avoiding §, which is the "code" for space fillers. I believe space fillers are displayed with symbols determined by the `@type` of the g element, and not with § marks, but I would still find it somewhat confusing if § in display were an indication of something else. I have had just a quick look at the discussion in the taxonomy, and note on the one hand that it is very old (2020) and on the other that § was raised there as encoding shorthand, not as display for squiggleVertical.
I also abide by my opinion that displaying dozens of different symbols with dozens of different Unicode characters 1) has very little practical value; 2) is bound to be inaccurate and potentially confusing; and 3) takes time and effort away from tasks many times more important.
That said, if a specific character is now easy to associate with the type squiggleVertical and Arlo needs a display different from the space-consuming label display (which I find completely acceptable, but we can agree to disagree about that without any bad feelings), then I would rather see a character not used for any other purpose, such as ⌇ U+2307 Wavy Line, but can also accept the § sign.

**Comment by michaelnmmeyer** [comment]
OK, I just added ⌇.

**Comment by danbalogh** [comment]
Thanks, but let's also see if that's acceptable to Arlo.

**Comment by arlogriffiths** [comment]
That is acceptable for me, though before proposing § I had actually had in mind to propose ¦ which I'd prefer above ⌇ if I am free to make a choice. (But I fear Dan will have the same objection as the one he has against §.)

**Comment by danbalogh** [comment]
As far as I know we aren't using ¦ for any purpose. The same discussion with § has some symbols in something from Ryosuke that look almost exactly like ¦, so if those are ever to be displayed as ¦, then ⌇ would be better for the squiggle.
On the other hand, in keeping with my feelings against the proliferation of display symbols, if you are reasonably sure that you will not at a later stage want to use both ¦ and ⌇ in display, I'm quite happy with ¦ (which I think is also much more widely supported in fonts). That is, ¦ U+00A6 Broken Bar.

**Comment by arlogriffiths** [comment]
OK, but may I again argue for §? The fact that this is used in tfc-nusantara-epigraphy as shorthand for 'squiggleVertical' does not mean that it looks like a vertical squiggle. What I like to bring across in display is the fact that there is a space filler, rather than its concrete shape. So why not § in display with mouse over recording what actual shape is used?

**Comment by danbalogh** [comment]
Now hang on a moment.
First, the idea is that the `@type` of a `<g>` element encodes its appearance and determines the display. The contents of the `<g>` element encode its function: it's a full stop for all symbols interpreted as punctuation, regardless of what they look like; and one or more § marks for all symbols interpreted as space fillers, regardless of what they look like. Empty element for symbols not explicitly interpreted as one of these two, and no other content is permitted (apart from numeral `<g>`s, which are not relevant here). I assume that all the vertical squiggles in your texts (so far) are also space fillers, but this is irrelevant. We have made a decision early on to make a distinction between the form and the function of symbols, and I stand by that decision. There are certainly space fillers that are not vertical squiggles, and there may well be vertical squiggles that are not space fillers. 

So when you say "What I like to bring across in display is the fact that there is a space filler, rather than its concrete shape", this means one of the following things:

A, you want to break this system and in the case of space fillers, you want display to be determined by the function of the symbol rather than its appearance (so that e.g. the gomutra space fillers in example 4.2.5.b would also be displayed as § signs); or
B, you want to hack this system by displaying all `<g type="squiggleVertical"/>` elements, regardless of content, as §, creating the misleading impression that all such symbols are space fillers, even when some of them may not be; or
C, you want to add a single very specific exception to the otherwise simple rules, namely that only in the case of space fillers encoded as `<g type="squiggleVertical">§</g>` (with both the type and the content), you want the display to be § (but want a different kind of display for `<g type="squiggleVertical"/>` and type-dependent display for other kinds of <g type="whatever">§</g>), which in my opinion opens a gate to chaos, because if next time someone asks for another exception for bull piss patterns used as punctuation or seven-pointed stars used at the boundary between prose and verse, we'd have to cater for that by the same logic.

So, before we make a decision about what seemed at the start to be a trivial detail, let's first be clear what it is you want to achieve. I believe (and hope) it is neither alternative B nor C, because both would be bad, bad practice. Is it then A? I could live with displaying all space fillers, regardless of shape, with § signs, but this would also be less than good practice, since it would mean that display is driven by content for some g elements and by type for others.

I think I've gone on long enough. For you to decide:
1. Do you want us to revise the overall approach to displaying symbols? My preference is not to, but if you want to go along with alternative A, the matter is not important enough for me to insist otherwise, and it does not affect our encoding practice, so we can reconsider at any time. Provided that it is technically feasible to do this (i.e. IF the content of a g element is nothing but one or more § characters, then display the content; ELSE display a character determined by the type, as before), I can accept it.
2. If the answer to 1 is no, then what Unicode character do you want to use to display `<g type="squiggleVertical"/>` (regardless of content)? You've heard my argument against § and my argument against ¦, but none of those are decisive, and I frankly couldn't care less, so please just put down your final vote on one of the three candidates.

**Comment by arlogriffiths** [comment]
Dear @danbalogh !

Thanks for exposing everything with your usual clarity. I withdraw my request to use § in display of `<g type="...">§</g>`.

Dear @michaelnmmeyer,

In case of `<g type="squiggleVertical">§</g>`, display is currently as in the following two examples to which I add a third for another category:

1. <img width="426" alt="Capture d’écran 2024-03-30 à 09 25 01" src="https://github.com/erc-dharma/project-documentation/assets/835603/47348021-48fa-49b9-a00f-b9578a78c0ba">

2. <img width="566" alt="Capture d’écran 2024-03-30 à 09 29 38" src="https://github.com/erc-dharma/project-documentation/assets/835603/aae8511d-1ee1-4c4d-b687-2c15ff5284d0">

3. <img width="762" alt="Capture d’écran 2024-03-30 à 09 19 16" src="https://github.com/erc-dharma/project-documentation/assets/835603/05514d02-d9d4-4e92-a8b7-7247d33f5ae1">


I feel it might be a bit more logical if the information in the mouseover were structured as follows

1.  Symbol of category space-filler: no description available
2. Unclear text | Symbol of category space-filler: no description available
3. Symbol of category punctuation: a short, curved vertical stroke at median height

What description do you need in order to be able to replace "No description available"?

**Comment by danbalogh** [comment]
Thanks, @Arlo. To me,  "Symbol of category x" seems a bit too verbose without being very informative. I would instead suggest either "X symbol", which to me conveys the same information but is simpler and easier on the reader; or, if your intent was to avoid stating in absolute terms that the symbol is an X, then "Symbol interpreted as x", which would then tell the reader more explicitly that the function of the symbol is an editorial interpretation.
But as above, none of these are important for my peace of mind, so if you are sure you prefer "Symbol of category x", then fine by me.

For a description, I suppose what we need is a few descriptive words in the [gaiji file](https://github.com/erc-dharma/project-documentation/blob/ff144d7151ac1d9fe0621c713636721ffd51c4b5/gaiji/DHARMA_gaiji.tsv). I have now provisionally written "a wavy or zigzag vertical line" for this; feel free to revise as you prefer.

**Comment by michaelnmmeyer** [comment]
We have four type of `<g>` for now:

**Comment by danbalogh** [comment]
The first three seem OK to me. I don't understand the fourth. If this is for `<unclear><g/></unclear>`, then any of the three types of symbol may be wrapped in `<unclear>`, so this is not a fourth category but an additional switch. The previous "Unclear text | " shown before the type-dependent tooltip should work fine; or it could be "Unclear punctuation symbol: $description" / "Unclear space-filler symbol: $description" / "Unclear symbol: $description".
Note that whatever the tooltip for unclear symbols, there may also be text within the same `<unclear>` element that is the parent of `<g/>`. This text should still get the usual tooltip for unclear text.

**Comment by michaelnmmeyer** [comment]
The fourth category is meant for this use case (EGD §4.2.1):

> - as an empty element <g/> to represent a glyph about whose function our encoding
> makes no assertions, i.e. all glyphs not covered by these three specific cases, such as
> auspicious symbols at the beginning or end of an inscription

It is also used as a fallback for `<g>` elements that are not properly encoded.

The name "unclear" is misleading, though; I should have called it "other" or something like that.

**Comment by danbalogh** [comment]
Thanks, I see now. If you need terminology for this kind of symbol, I suggest "uninterpreted". The tooltip "Symbol: $description" is fine.

**Comment by arlogriffiths** [comment]
I agree with everything you two have just proposed.

**Comment by arlogriffiths** [comment]
can this be closed yet?

**Comment by danbalogh** [comment]
I think we should wait for @michaelnmmeyer to confirm that the final decisions have been implemented, and then he could close it.

**Comment by michaelnmmeyer** [comment]
Done
