### ISSUE TITLE
display of <supplied reason="subaudible"> in edition

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#272]
@danbalogh —

in https://dharmalekha.info/texts/DHARMA_INSVengiCalukya00079 you have

`tato <supplied reason="subaudible">’</supplied>rjunā<lb n="15" break="no"/>d abhimanyuḥ<g type="comma">.</g>`

and it is displayed like this

<img width="786" alt="Capture d’écran 2024-03-30 à 09 13 32" src="https://github.com/erc-dharma/project-documentation/assets/835603/ba2521a8-caf6-4977-bb38-a90cb55b9627">

I have not myself been using ` <supplied reason="subaudible">` for unwritten avagrahas. Anyhow, I imagine that the display of a message mentioning the "translation" needs to be modified a bit. Please instruct @michaelnmmeyer on what to do.

**Comment by danbalogh** [comment]
Yes, the tooltip message is correct for the translation. But for instances of `<supplied reason="subaudible">` within the edition division (as well as in places where edition bits can be cited, such as apparatus lemmas and readings, and items in `<foreign>` tags in notes, commentary and translation), the tooltip should say something else.
Is it possible to display a different tooltip depending on contents of the `<supplied reason="subaudible">` element? There are two things it can in principle contain:

- either a ’ character [and perhaps other apostrophe-like characters, which encoders should not use here, but might have used them instead of the right one, and which should all be converted to ’ either in the XML files themselves or in display at least], for which the ideal tooltip would be "Avagraha added by the editor to clarify the interpretation";
- or a . character, for which the ideal tooltip would be "Punctuation added by the editor at semantic break"

If it is complicated or impossible to make this content-dependent, I suggest "Editorial addition to clarify interpretation" for both.

**Comment by manufrancis** [comment]
@danbalogh 
Is it required to tag unwritten avagrahas as
`<supplied reason="subaudible">’</supplied>`?
OR
typing `’` is just OK for the moment, and will be automatically replaced 
by 
`<supplied reason="subaudible">’</supplied>`?

**Comment by danbalogh** [comment]
@manufrancis See EGD §6.3.7 and TG §2.6.3. Typing just ’ is all right and the idea is that it will be automatically replaced with the correct markup. That said, in my own editions I always use `<supplied reason="subaudible">’</supplied>` because I do not know when and with what accuracy the automated replacement will take place.

**Comment by manufrancis** [comment]
Noted. Thanks!

**Comment by arlogriffiths** [comment]
Thanks to @michaelnmmeyer, display is now correct, except that here, as in other tooltips, we should have 

1. either the pattern initial capital + full-stop at end
2. initial lower case and no final punctuation

<img width="462" alt="Capture d’écran 2024-04-17 à 05 32 54" src="https://github.com/erc-dharma/project-documentation/assets/835603/3aa0927a-20f5-4f48-a045-65042705d3d3">

@michaelnmmeyer : I think I prefer option 2, but there may be long/complicated items that force presenting tooltips as sentences. Please see what solution works best globally, implement the small stylistic harmonization in all tooltips, and close this when done.

**Comment by michaelnmmeyer** [comment]
The display we have now follows traditional user interface conventions (initial capital, no final period). Your solution 1 feels much more natural than your solution 2, but having a final period looks a bit weird for short phrases like

> Unclear text.

> Lost text.

and when stacking nested tooltips:

> Unclear text. | Grantha text.

>

**Comment by danbalogh** [comment]
I have no objection to initial capital and no full stop, given that these tooltips are typically not complete sentences, only (sometimes complex) noun phrases. If @arlogriffiths is willing to come around, then I think we should keep them that way. If not, then I agree that initial lowercase and no full stop would be better, but whatever you two can agree on will be fine for me.

**Comment by arlogriffiths** [comment]
happy to come around. your can forget about my raising this minor detail.
