### ISSUE TITLE
use of <supplied reason="explanation"> in translation

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#283]
The content of the mouse-over box does not match with the use that I often make of `<supplied reason="explanation">` to insert into the translation the original word that has just been represented.

Example:

` <supplied reason="subaudible">When</supplied> this one <supplied reason="explanation"><foreign>dunan</foreign></supplied> took the kingship, ..`

<img width="476" alt="Capture d’écran 2024-04-14 à 11 43 52" src="https://github.com/erc-dharma/project-documentation/assets/835603/d656c0c2-ecf6-4c76-b386-de899449aabd">

@danbalogh: should I encode such cases differently? if my encoding is correct, then can we funish to @michaelnmmeyer a text to use in mouse-over that better captures the range of usage of `<supplied reason="explanation">`? Suggestion:

"Explanation of any sort inserted into the translation in order to help the reader."

Minor detail: I'd like to see proper final punctuation in such cases.

**Comment by danbalogh** [comment]
That's right, this tooltip is OK for `<supplied reason="explanation">` on its own, but not when its content is `<foreign>`. If we want to go for a generic tooltip for all instances, then I'm essentially OK with Arlo's suggestion, but if I want to be finicky (and I do), then on the one hand I find it a little verbose (both "of any sort" and "in order to help the reader" being somewhat unnecessary), and on the other hand it's probably too different from the tooltip for other kinds of supplied (dharman.in is down right now so I cannot check to be sure). My suggestion is "Text inserted into the translation as explanation or disambiguation". But I'm OK with anything.

Alternatively, we might want to go for a special tooltip associated only with `<supplied reason="explanation"><foreign/></supplied>`, but this may be problematic, since in some cases translators might also use `<supplied reason="explanation">text<foreign/>text</supplied>`, in which case we'd need different tooltips for the direct text content and that in foreign. So probably stick to the generic tooltip.

**Comment by michaelnmmeyer** [comment]
OK, corrected.

**Comment by arlogriffiths** [comment]
Thanks. So now we have this.

<img width="456" alt="Capture d’écran 2024-04-15 à 18 08 09" src="https://github.com/erc-dharma/project-documentation/assets/835603/d1249f74-8dbc-4f99-9410-59696e02aae8">

If it's intentional and consistent throughout the database, then fine to have no final punctuation, and in that case I'd prefer not to start with initial capital. Conversely, if we have an initial capital I'd like to see a final full-stop.
