### ISSUE TITLE
IAR in Zotero

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#290]
@arlogriffiths 

How should we zoterise IAR?
There are issues with known editor and issues without.
And there is also a generic Zotero entry for the journal.

See here the different short titles.
![Capture d'écran 2024-04-21 105415](https://github.com/erc-dharma/project-documentation/assets/905870/b6f78b8e-732a-4271-b5a4-0287d54181bc)

**Comment by arlogriffiths** [comment]
I would probably never cite IAR by the editor, even if known. So I would recommend we first systematize all ZSTs with the pattern "IAR1953-54", "IAR1954-55", etc. (I suspect existing ZSTs not following that pattern have hardly been cited in our XML files so far, but it would be best if @michaelnmmeyer could confirm this.) This will allow citing specific volumes without using the generic entry. Next I would cite by page, e.g. `<bibl><ptr target="bib:IAR1965-66"/><citedRange unit="page">114</citedRange></bibl>`. This is basically how I proceed for analogous publications like NBG and the anonymous Chronique parts of old BEFEO volumes.

<img width="1098" alt="Capture d’écran 2024-04-21 à 18 49 12" src="https://github.com/erc-dharma/project-documentation/assets/835603/7172c416-8f59-45d1-8b09-80f84d11d229">

The "no name" items are generated by 

`<bibl><ptr target="bib:NBG14_1876"/><citedRange unit="page">98-100, 106</citedRange></bibl>`
and
`<bibl><ptr target="bib:NBG25_1887"/><citedRange unit="page">67</citedRange></bibl>`

@michaelnmmeyer: can a rule be formulated whereby in such cases the display shows the abbreviation for the journal in place of "no name"? Since the zotero entries in question do no have an "journal abbreviation" field, some work-around would be necessary. Maybe @manufrancis and @danbalogh have other aesthetically more pleasing solutions to propose.

**Comment by arlogriffiths** [comment]
@michaelnmmeyer : by the way, in the screenshot just shared, I notice that "bookAuthor" is not adequately represented yet in our display. The Zotero item in question is Brandes1887_01, which exports correctly if I use the personalized CSL:

Brandes, Jan Laurens Andries. 1887. “Beschreven steenen.” In Catalogus der archaeologische verzameling van het Bataviaasch Genootschap van Kunsten en Wetenschappen, by Willem Pieter Groeneveldt, 351–91. Batavia: Albrecht & Co.

**Comment by michaelnmmeyer** [comment]
(1) We have about 200 citations of the IAR in our texts.

(2) When no author or editor name is available, I propose to fall back to the short title. So we would have e.g.

> See NBG14 1876, p. 30.

> NBG14 1876. Notulen van de Algemeene en Bestuurs-vergaderingen van het Bataviaasch Genootschap van Kunsten en Wetenschappen: Deel XIV — 1876. Batavia: Bruining, 1877, pp. 98–100, 106.

(3) OK for the display of `bookAuthor`. We now have:

> Brandes, Jan Laurens Andries. 1887. “Beschreven steenen.” In: Catalogus der archaeologische verzameling van het Bataviaasch Genootschap van Kunsten en Wetenschappen. By Willem Pieter Groeneveldt. Batavia: Albrecht & Co., p. 361.

**Comment by danbalogh** [comment]
I have no constructive suggestions but would like to note that ARIE is also analogous and is a source of annoyance, giving rise to displays like this (all three items of the secondary bibliography are ARIE volumes):
![image](https://github.com/erc-dharma/project-documentation/assets/31253927/c264975f-357d-455b-b922-83742f12be4c)
from the code:

```
<div type="bibliography">
   <p>First reported in <bibl><ptr target="bib:ARIE1907-1908"/><citedRange unit="page">10</citedRange><citedRange unit="appendix">A/1907-1908</citedRange><citedRange unit="item">2</citedRange></bibl> with a description at <bibl><ptr target="bib:ARIE1907-1908"/><citedRange>48-49</citedRange></bibl>.<!--CHECK: According to bib:Gai1986_01 (Dynastic List), p 33 item 170, these plates were also reported as Copper Plate 60 of 1957. There is no Number 60 among the copper plates in ARIE 1957-58, and there seems to be no ARIE volume for 1956-57, or if there is one, perhaps it was omitted from the reprint.--> Edited from inked impressions by E. Hultzsch (<bibl rend="omitname"><ptr target="bib:Hultzsch1907-1908_07"/></bibl>) with partial estampages<note>Only estampages of 1v and 2r are included in the 1981 reprint of <title>Epigraphia Indica</title>; there is no image of 2v, nor of the seal.</note> and translation. Re-reported in <bibl><ptr target="bib:ARIE1956-1957"/><citedRange unit="page">33</citedRange><citedRange unit="appendix">A/1956-57</citedRange><citedRange unit="item">60</citedRange></bibl>. The present edition by Dániel Balogh is based on photographs taken by myself in February 2023 at the Government Museum, Chennai, collated with Hultzsch's edition and his estampages where available. 
   </p>
    <listBibl type="primary">
    <bibl n="EH"><ptr target="bib:Hultzsch1907-1908_07"/></bibl><!-- one <bibl/> per item of primary bibliography -->
  </listBibl>
   <listBibl type="secondary">
      <bibl><ptr target="bib:ARIE1907-1908"/><citedRange unit="page">10</citedRange><citedRange unit="appendix">A/1907-1908</citedRange><citedRange unit="item">2</citedRange></bibl>
      <bibl><ptr target="bib:ARIE1907-1908"/><citedRange>48-49</citedRange></bibl>
      <bibl><ptr target="bib:ARIE1956-1957"/><citedRange unit="page">33</citedRange><citedRange unit="appendix">A/1956-57</citedRange><citedRange unit="item">60</citedRange></bibl>
<!-- one <bibl/> per item of secondary bibliography -->
   </listBibl>
</div>
```

* Incidentally, I notice that code such as `<citedRange unit="appendix">A/1907-1908</citedRange>` is incorrectly displayed as "appendices": this should be "appendix". I don't know how this could be circumvented, since I believe we have formulated a rule to use the plural form if the content includes a hyphen.

Back to the topic at hand, publications of this sort are not journals in my opinion, since they often [though not always] have individual editors and publishing places while typically [but not always] lacking articles by named authors. If it is possible to implement without requiring us to revise too many of our existing Zotero entries, I think it would be nice to display such items (e.g. `<ptr target="bib:ARIE1907-1908"/>` or `<ptr target="bib:IAR1965-66"/>`) as follows:

- in a citation: "ARIE 1907−1908" / "IAR 1965−66"
- in the bibliography: "ARIE 1907−1908. _G.O. No. 574, 17th July 1908. Epigraphy. Recording the progress report of the Assistant Archaeological Superintendent for Epigraphy, Southern Circle, for the year 1907−1908. Edited by V. Venkayya._" / "IAR 1965−66. _Indian Archaeology 1965−66, A Review_" Edited by A. Ghosh."

That is to say, I would always show the abbreviation instead of using it just as a fallback option when there is no author or editor available. Author and/or editor, when present, would be shown only in the full bibliography, after the title. (I also think this is what Arlo had in mind above when he said he would never cite IAR with the editor's name.) Place, publisher and publication date may not need to be shown at all, but they could also be added to the full bibliography when available. I would want a space after the journal abbreviation and prefer en dashes instead of hyphens. However, I have no idea how this could be systematised in Zotero to get the desired display. I wonder if the Zotero item type "Report" might not be more suitable for these publications than Book.

**Comment by manufrancis** [comment]
Thanks both of you!

So I note taht ZST for IAR should be of the type `"IAR1965-66"`.

@arlogriffiths 
I can update the wrong existing ones (IAR1954-01, Ghosh1995_01, etc.) on Zotero.
This ZST for IAR should be explained in the next version of the Zotero guide.

@michaelnmmeyer 
As some `target="bib:..."` for IAR will have to be updated accordingly to my cleaning of ZST, could you tell me, about the about 200 IAR citations, in which repos they are? And maybe, if easy collected, by which encoders?

**Comment by manufrancis** [comment]
ARIE is indeed a pain in the ass.

I deal as follows when I need to refer for the same ARIE to a N° in the appendix table and to a § in the detailed notes that follow the appendix tables
(see https://dharmalekha.info/texts/INSPallava00518):

```
<bibl>
		<ptr target="bib:ARIE1938-1939"/>
		<citedRange unit="page">38</citedRange>
		<citedRange unit="appendix">B/1938-1939</citedRange>
		<citedRange unit="item">271</citedRange>
		<citedRange unit="page">91</citedRange>
		<citedRange unit="section">59</citedRange>
</bibl>
```

Which in display presently gives:
![image](https://github.com/erc-dharma/project-documentation/assets/905870/46911f90-26b2-4c39-b2e7-679b0f229d76)

@michaelnmmeyer 

1. In such a display would it be possible to add something (&, +, or a diamond, ...), rather than a comma, between 
"p. 38, appendices B/1938-1939, № 271"
and
"p. 91, § 59"

2. "appendices" should indeed be "appendix".
(which, by the way works fine for another `<bibl>` in this file in primary bibliography).

3. Note that after "Government of India" we expect full stop rather than comma.


As for Daniel's suggestions for display of IAR and ARIE in bibliography, it is fine for me if indeed `it is possible to implement without requiring us to revise too many of our existing Zotero entries.`

**Comment by michaelnmmeyer** [comment]
@manufrancis 

For the IAR, I propose you just modify the Zotero entries in the screenshot. I will update inscriptions accordingly.

For points 1 and 2 of your latest post, I do not see a nice solution. In practice, references vary too much to be expressed in a clear, structured way. In cases like these, it would probably be simpler to use free text.

For point 3 of your latest post, I am not sure why you want a full stop after the publisher name. Is it because, in this case, page numbers, etc. are given in `<citedRange>` instead of in the zotero entry? In other words, is it to distinguish page numbers given in the zotero entry (if any) from the ones given with `<citedRange>`?

@manufrancis @arlogriffiths @danbalogh 

For citing entries with an abbreviation instead of the usual author+date scheme, I propose we define a `Shorthand` field that, when given, would be used in references instead of the usual author+date. This is more-or-less what biblatex does. For the entry `Ghosh1961_01`, which refers to IAR 1960-61, you would add in the `Extra` field:

> Shorthand: IAR 1960-61

References would look like this:

> See IAR 1960-61, p. 10.

And entries would look like this:

> IAR 1960-61. *Indian Archaeology 1960-61, A Review*. Edited by A. Ghosh. New Delhi: Archaeological Survey of India, 1961.

Note that the shorthand includes a date; the date of publication is not automatically pulled from the relevant entry field. This way, it is possible to use a different numbering scheme (series number, etc.), or to use no scheme at all (abbreviations for referencing canonical editions of certain texts, like `MBh`, etc.).

**Comment by michaelnmmeyer** [comment]
@danbalogh *A priori*, the shorthand would be used by default if present. That said, we can make this opt-in or opt-out if needed. The `Extra` field in Zotero can store arbitrary key-value pairs, so we could add display options there.

**Comment by manufrancis** [comment]
@danbalogh 
1. Ok. noted for EGD§10.4.5.
2. I my use of "item" and "section", I am not sure I get your point. I use "item" for an item in a numbered list of inscriptions and the display "N°" fits that. I use "section" for a numbered paragraph and the display "§" fits that.
3. As for shorthand "ARIE 1938-39" (analogous to the IAR examples above) rather than "ARIE 1938-1939", fine to me. Just to be clear you mean only shorthand, not Zotero Short title.

@michaelnmmeyer 
1. I will update the Zotero Short titles for IAR.
2. As for the full stop after the publisher name. Yes, this is because, in this case, page numbers, etc. are given in <citedRange> instead of in the zotero entry. And yes this is it to distinguish page numbers given in the zotero entry (if any) from the ones given with `<citedRange>`.
See what Axelle had for a `<citedRange>`
![image](https://github.com/erc-dharma/project-documentation/assets/905870/ce2acb4e-2dc0-4b8d-85df-a4118a8f17df)

And here two displays of the same Zotero reference, the first with a `<citedRange>`
![image](https://github.com/erc-dharma/project-documentation/assets/905870/6d2f7449-8c5f-4fcc-b755-5dba565248e2)

Note that your actual display does not show the page quotations of the said article.

**Comment by manufrancis** [comment]
I have now updated the existing IAR entries in Zotero

![Capture d'écran 2024-04-23 091839](https://github.com/erc-dharma/project-documentation/assets/905870/6332d9a1-1459-4a2b-b847-609b68d72743)

I have followed for the ZST the current model for ARIE (ARIE0000-0000), thus IAR0000-0000.
Should we decide to change this model to IAR0000-00, the ZST should thus be updated in Zotero and in the edition XMLs.

**Comment by danbalogh** [comment]
@manufrancis , thanks for cleaning up the Zotero entries. On your above points,

2: I have no objection to your use of "item" and "section" for these things, but in my own editions I use "item" for both (entries in the appendix and items of discussion). The numbered parts of the ARIE text descriptions don't really look like sections to me. But as I said above, I don't mind changing to "section" if that's your strong preference. The point is that it would be best if you and I used the same unit when referring to the ARIA, and even better if everyone in the project did that. So if you are sure you want to keep using section for the discussion, let me know, and I'll change to section in my editions.

3: Yes, I meant only the shorthand; I would not want to change the ZST.

**Comment by manufrancis** [comment]
**To your point 2**

In secondary literature I find as a kind of traditional reference "part n, para. n"

![Capture d'écran 2024-04-23 094607](https://github.com/erc-dharma/project-documentation/assets/905870/0cd43626-d459-46ff-b902-938e6da75f2a)
[note: 272 is the page number]

In my oxygen I find:

![Capture d'écran 2024-04-23 094744](https://github.com/erc-dharma/project-documentation/assets/905870/745da7a8-f957-4707-ae8b-62b20ef2d23d)

and

![Capture d'écran 2024-04-23 094809](https://github.com/erc-dharma/project-documentation/assets/905870/3f66ba87-d9cb-460a-b192-0e13b51d706b)

For the moment, relying on EGD§10.4.5 I would encode a complex ARIE ref as follows:

```
<bibl>
		<ptr target="bib:ARIE1938-1939"/>
		<citedRange unit="page">38, 91 (§59)</citedRange>
		<citedRange unit="appendix">B/1938-1939</citedRange>
		<citedRange unit="item">271</citedRange>
</bibl>
```

But would I adopt double <bibl>, yes I would use "item" for a number in appendix tables and "section" for paragraph in detailed discussion

**To your point 3**

If we thus agree on using shorthand, am I right that it means, e.g. for ARIE 1955-1956, of which the ZST is "ARIE1955-1956", we should add on Zotero "ARIE1955-56" in the field "Extra" ???

@michaelnmmeyer 

If we adopt Daniel' encoding

   
```
   <listBibl type="secondary">
      <bibl><ptr target="bib:ARIE1907-1908"/><citedRange unit="page">10</citedRange><citedRange unit="appendix">A/1907-1908</citedRange><citedRange unit="item">2</citedRange></bibl>
      <bibl><ptr target="bib:ARIE1907-1908"/><citedRange>48-49</citedRange></bibl>
      <bibl><ptr target="bib:ARIE1956-1957"/><citedRange unit="page">33</citedRange><citedRange unit="appendix">A/1956-57</citedRange><citedRange unit="item">60</citedRange></bibl>
   </listBibl>
```

would you easily be able to have a display where both `<ptr target="bib:ARIE1907-1908"/>` result in only one bibliographical Venkayya, followed by two pages quotations, one to p. 2 and one to pp. 48-49?

**Comment by danbalogh** [comment]
@manufrancis Re point 2: I understand your reasons for preferring "section" and was not asking for further details of why. I just want our practice to be homogeneous. Since my practice so far has been to use "item" for those numbered bits of prose, my question was simply whether you are certain you want to keep using "section" for the same. I'll take this as a yes and change my practice to follow suit; I'll also make a note for myself to recommend this explicitly in the next EGD.

On the complex EGD reference, I repeat with emphasis that the encoding you show is **wrong**, as its meaning is ONE locus which is simultaneously on page 38 AND on page 91 AND in section 59 AND in Appendix B/1938-1939 AND in item 271 - which is impossible. To create a single reference to two items, one specified as (page 38, Appendix B/1938-1938, No. 271) and the other specified as (page 91, section 59), you can only use the non-rigorous free-text mode of referring for which I cited the EGD above: `<citedRange>p. 38, Appendix B/1938-1938, No. 271; p. 91, §59</citedRange>` - where you can write anything in the contents of citedRange and it's up to you to make sure that it will be interpretable for readers and if possible, consistent across your editions.

I generally do not think it desirable to start adding idiosyncratic display solutions for specific combinations of bibl elements. But if Michaël says it is indeed easy to create a merged display for the structured bibliographies, so that if two consecutive `<bibl>` elements contain a `<ptr>` with the same `@target`, then the bibliodata of the second are not shown, but instead the citation details are appended to the first, separated, say with a semicolon, instead of a line break (or indented, if a line break is inevitable), then fine by me.

But what I was speaking about above when I noted that two separate bibl elements can do the job, I meant the kind of unstructured context in my own encoding cited above:

`First reported in <bibl><ptr target="bib:ARIE1907-1908"/><citedRange unit="page">10</citedRange><citedRange unit="appendix">A/1907-1908</citedRange><citedRange unit="item">2</citedRange></bibl> with a description at <bibl><ptr target="bib:ARIE1907-1908"/><citedRange>48-49</citedRange></bibl>.`

In the (structured) secondary bibliography, these would still have to be listed as two separate references.

**Comment by manufrancis** [comment]
* Yes, please, take it as a yes for "item" and "section", and sorry for the extra work of changing your practice and thanks for adding that to the EGD.
* Thanks for the clarification on complex EGD reference. I let you judge whether an example such as `<citedRange>p. 38, Appendix B/1938-1938, No. 271; p. 91, §59</citedRange>` should be given as `Example 10.4.5.H`. It is much easier for me to grasp it (while I have so many emails and requests to address ;-) in this form rather than `use <citedRange> without any attributes, containing a non-rigorous but unambiguous conventional indication of the target of your citation (e.g. "p. 291 nn. 9, 10; p. 320", "p. 15, App. A" or “part I, pp. 216–217; part II, pl. XI”)`
* As for ARIE refernce, I will reflect on which option I will take between non machine actionable complex EGD reference and machine actionable reference as you have it in your encoding. The latter may indeed be very useful for future (maybe very distant future) developments, such as linking the ARIE reference to the scan of the ARIE page.

**Comment by michaelnmmeyer** [comment]
@manufrancis It is feasible, but I agree with Dániel that a free text reference would be preferable. If you have several cases like this, we can find a solution together.

**Comment by danbalogh** [comment]
@manufrancis: I must correct myself on one detail. It had escaped my memory that for this kind of non-rigorous reference, we have agreed to no longer use `<citedRange>` without any attribute; instead, it has to involve `<citedRange unit="mixed">`. This way, the computer can know that if there are no attributes, then a page number is meant. So if you use the free-text format, please make it `<citedRange unit="mixed">p. 38, Appendix B/1938-1938, No. 271; p. 91, §59</citedRange>`. I can add it as an Example to the next EGD.

**Comment by manufrancis** [comment]
@danbalogh 
Noted. And yes, please, an example in next EGD would be useful.

@michaelnmmeyer 
Yes, I have several cases of double ref pointers in the same ARIE. Nothing urgent though.

**Comment by arlogriffiths** [comment]
I didn't have time to follow all of this discussion, but I did see that @danbalogh requested an addition to ZG. Since Axelle's departure, I no longer know whom I am supposed to be collaborating with for maintenance of the ZG. 

@manufrancis : this is a subject for our next AG.
@danbalogh : could you kindly insert a comment at a relevant place in the ZG gdoc?

**Comment by arlogriffiths** [comment]
The shorthand solution doesn't work yet, right? I have just made Zotero entry [JA1908_01](https://www.zotero.org/groups/1633743/erc-dharma/items/RSXJEIXS) and encoded a bibliography entry as follows:

`<bibl><ptr target="bib:JA1908_01"/><citedRange unit="page">331</citedRange></bibl>`

with "Shorthand: JA 1908" in Extra.

display:

<img width="1036" alt="Capture d’écran 2024-04-25 à 07 41 11" src="https://github.com/erc-dharma/project-documentation/assets/835603/13c980c8-1a24-4c18-a2f2-c6fbd3ef1a81">

**Comment by danbalogh** [comment]
I've added a comment in the ZG with reference to this thread. I cannot suggest even a draft of what should be added, because this Shorthand will need integration with the present ZG recommendation/rule of including the short title in the extra field (to be deprecated, I guess), and because this discussion does not seem to be finished.

**Comment by michaelnmmeyer** [comment]
@arlogriffiths The "shorthand" thing is not implemented yet. I will annotate the Zotero guide, but I need some time.

**Comment by michaelnmmeyer** [comment]
I added support for shorthands and modified the IAR entries accordingly. Now we have e.g.:

![image](https://github.com/erc-dharma/project-documentation/assets/11620332/a863a7ed-2178-477a-9b09-3a6744bd5c98)

![image](https://github.com/erc-dharma/project-documentation/assets/11620332/c1fde6c7-dcad-4559-908e-55381ab86410)

In the second case, I find it undesirable to have the editor name at the beginning of the field. The following looks more natural:

> [IAR] IAR 1957-58. *Indian Archaeology 1957-58: A Review*. Ed. by A. Ghosh. New Delhi: Department of Archaeology, Government of India, 1958. Page 56, plate 19. 

But it is not possible to determine automatically which editors/authors names should be pushed forward in the entry, we would need an extra option for this.

**Comment by danbalogh** [comment]
It was not "my solution" but quoted from what you had proposed earlier on. In my opinion, shorthand should definitely not be applicable to journal articles, and to books only for a given definition of "book". I thought the shorthand was introduced to handle journal-like serial publications. I have no idea what RAC means, but I am strongly against using any kind of shorthand for an article in EI. If this is the explicit wish of a PI, then I wash my hands of it. It's all the same to me.

**Comment by arlogriffiths** [comment]
I may have muddied the waters with my attempt to use Shorthand to handle an authorless item from the Journal asiatique:

“Chronique : XVe Congrès international des Orientalistes. — IIIe Congrès de l’histoire des religions. — Varia.” 1908. Journal Asiatique 10e série, 12: 312–38. [https://gallica.bnf.fr/ark:/12148/bpt6k932739].

But I don't think Shorthand should come into question for any itemType:journalArticle item that has an explicitly identified author and date, as is the case in Michaël's examples

    RAC. Nilakanta Sastri, K. A. and M. Venkataramayya. “Telugu Chola records from Anantapur and Cuddapah.” EI 27, (1947-1948), pp. 220–251.

    RAC. “Telugu Chola records from Anantapur and Cuddapah.” By K. A.Nilakanta Sastri and M. Venkataramayya. EI 27 (1947-1948), pp. 220–251.

**Comment by michaelnmmeyer** [comment]
This is implemented now. See e.g. http://dharmalekha.info/texts/INSPallava00402. There is no documentation yet.

**Comment by arlogriffiths** [comment]
I see there:

<img width="878" alt="Capture d’écran 2024-05-17 à 18 24 19" src="https://github.com/erc-dharma/project-documentation/assets/835603/29484640-2fe8-4064-9bd1-c9a104fdfde8">

To my mind the display (with "By Anonymous") is not yet satisfactory. Now I see that it must be due to "anonymous" having been entered in the Zotero entry itself:

<img width="380" alt="Capture d’écran 2024-05-17 à 18 28 21" src="https://github.com/erc-dharma/project-documentation/assets/835603/ea1dea5f-608c-4c84-80fa-7d27f6219381">

There is nothing in ZG to sanction this use of "anonymous". 

Do I have everyone's permission to remove any such cases from our Zotero groub library?

@michaelnmmeyer : will the bit with "By ..." disappear in display if there is no author/editor etc. field with any contents?

**Comment by michaelnmmeyer** [comment]
@arlogriffiths Yes, the "By ..." will disappear.

Generally speaking, the "Author" field should be empty whenever none is given. It is the job of the bibliography processor to add "Anonymous" or "No author", etc.

**Comment by michaelnmmeyer** [comment]
The shorthand feature is now documented, under ZG §4.15 Extra.

**Comment by arlogriffiths** [comment]
Thanks a lot Michael.

I have searched for "anonymous" in our Zotero Group library and cleaned up a number of cases.

@danbalogh and @manufrancis : can I leave it to you to make any necessary modifications in the following three items?

Anonymous. 1847. “Translation of the Inscription in the Nagarjuni Cave, given in Plate X. of the Present Volume.” Journal of the Asiatic Society of Bengal 16: 594–96. 
= Siddham_Anonymous_1847

———. 1894. “Obituary Notices: Major-General Sir Alexander Cunningham.” Journal of the Royal Asiatic Society, New Series, , 166–77.
= Anonymous1894_01, apparently not from Siddham but maybe Dan can deal with it anyhow

Rajavelu, S. 2008. “Recent Discoveries near Mamallapuram.” In Airāvati: Felicitation Volume in Honour of Iravatham Mahadevan, edited by anonymous, 177–90. Chennai: Varalaaru.com.
= Rajavelu2008_01

**Comment by manufrancis** [comment]
Done for Rajavelu, S. 2008.

**Comment by danbalogh** [comment]
Done for Nagarjuni Cave and the Cunningham Obituary.

**Comment by arlogriffiths** [comment]
Thanks. So I presume this can now be closed. Feel free to reopen if I am wrong.
