### ISSUE TITLE
language stuff

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#293]
@michaelnmmeyer — I had a quick look at https://github.com/erc-dharma/project-documentation/commit/5900bc5ffa5d5d98b99842275e3f65b70d211d6b.

Before you spend a whole lot more time on unnecessarily, has anyone actually asked you to offer altenative options to 3-letter ISO codes? I don't feel we need any and I'd prefer we work with a mndatory single system, that is, until it has been explained why we need something more.

At the moment, our most central language "san-Latn", when encoded as per EGD, leads to invalidation of my files.

<img width="1285" alt="Capture d’écran 2024-04-24 à 19 59 07" src="https://github.com/erc-dharma/project-documentation/assets/835603/0374d182-4891-4cdb-a1d4-4b75dfaab791">

**Comment by michaelnmmeyer** [comment]
I made a mistake in the schema commit, now reverted.

For non-ISO language codes, this has been in place for a while. We still have one language code that was present in our original table and that is not in the standard, namely `oldbalinese`. Nobody has used it so far, though.

**Comment by arlogriffiths** [comment]
We will need Old Balinese for future phases of dharmalekha development. Could you send a reminder to the ISL lady who is in charge of ISO 693-3 registration?

You write: "non-ISO language codes, this has been in place for a while." — I don't know who asked you to put such an alternative in place. I don't think that the absence of a 3-letter ISO 693-3 code for a single language means we need to have an alternative way of representing any other languages. Am I ignorant of relevant facts?

**Comment by michaelnmmeyer** [comment]
Looking at our past exchanges, it appears we did not make a formal request for Old Balinese. Requests are now made through [a Google form](https://docs.google.com/forms/d/e/1FAIpQLSeMh0ThLA64kxccJG9QXSXa2Q1-I2EPZ_gnXD7ptOuPIbfBCg/viewform). Can I go on and fill it with your info?

For non-ISO language codes, I am not suggesting we use a new classification. They are meant to be used *only* for languages that are not in the standard, like `oldbanise`.  Instead of "It is OK to invent a new language code if needed", you can read "It is OK to invent a new language code if none is available in the standard, the application will handle it correctly".

**Comment by arlogriffiths** [comment]
I'd be very grateful if you could make the submission for Old Balinese. You have the word file for the request that I initially tried to submit?

Thanks for the explanation about the scope of use of non-ISO codes.

**Comment by michaelnmmeyer** [comment]
OK, doing that.
