### ISSUE TITLE
<unclear> on placeholder or vowel or both?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#296]
@danbalogh —

At the transition between these two lines we expect po. The e-marker was probably engraved at the end of the first line, but is very unclear. Logically, the reading o on the next line is hence also unclear. Where to apply the `<unclear>` tags?

1. `bhandāra yām̃ <unclear>⌈</unclear><lb n="B9" break="no"/>po ku śrīśānabhadreśvara`
2.  `bhandāra yām̃ <unclear>⌈</unclear><lb n="B9" break="no"/>p<unclear>o</unclear> ku śrīśānabhadreśvara`
3. `bhandāra yām̃ ⌈<lb n="B9" break="no"/>p<unclear>o</unclear> ku śrīśānabhadreśvara`

<img width="1033" alt="Capture d’écran 2024-04-28 à 11 51 21" src="https://github.com/erc-dharma/project-documentation/assets/835603/4346a512-4f90-4760-b30b-e31d2022ed08">

**Comment by danbalogh** [comment]
It's number 1. 

EGD §4.1.4: 
if some of the components involved are unclear, 
[...] 
separately apply the tag to the placeholder only if the split-off component is itself affected
[...]
for example:
[...]
(ெ)<>கா would be encoded as <unclear>⌈</unclear><>k<unclear>o</unclear>

I agree that the reading of what we transliterate as o is on the whole logically unclear, but when the placeholder ceiling character is present, then the ceiling and the "o" together correspond to that o, with the ceiling standing for the left-hand component and the "o" standing for the right-hand component. If we chose any alternative other than 1, then we'd have no way of representing a case where only the marker after the consonant body was unclear.

**Comment by arlogriffiths** [comment]
Thanks. So it seems you mean alternative number 2 instead of 1. Please confirm.

**Comment by danbalogh** [comment]
Hmm, thanks for pointing out my mistake. It seems that the guide is not as unequivocal on this as it should be. Indeed, you should follow your 2 as per the example in the EGD. But that means that my reasoning above is wrong. It was based on my misconstruing of the EGD instruction as "apply the tag to the **placeholder only**" instead of "apply ... **only if** the split-off component is itself affected". This means that we do not, actually, have a way of explicitly encoding the fact that the right-hand component of the o is clear, so disregard the explanation above. The underlying rationale for preferring this solution must have been the importance of encoding the transliterated "o" as unclear. We should not change the rule, but I'll rewrite this bit in the guide to make it clearer.

**Comment by arlogriffiths** [comment]
Thanks. Feel free to close this after having made the necessary edits to EGD.
