### ISSUE TITLE
About bibliographic display

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#31]
Dear all, 

I will start soon to work on a more precise display of the bibliographical data from Zotero.
Could you start listing your wishes with their context of display when necessary? 

Thanks, 
Best,

**Comment by manufrancis** [comment]
My first thoughts:

* edition
case of an edition reproduced without revision:
`<div type="edition" source="bib:Hultzsch1895_01">`
Display: 
**Edition by Hultzsch (1895)**
OR
**Edition by Hultzsch 1895**

* apparatus, in `<note>`
`<note>We do not follow <bibl><ptr target="bib:Hultzsch1902-1903_01"/><citedRange unit="page">23</citedRange><citedRange unit="note">2</citedRange></bibl> in considering that ... </note>`
Display: 
We do not follow `H (p. 23, n. 2)` in considering that ... (that is, use siglum like in `<rdg>`)
OR
We do not follow Hultzsch `(1902-1903: 23, n. 2)` in considering that ...

* translation
case of a translation reproduced without revision:
`<div type="translation" xml:lang="eng" source="bib:Hultzsch1895_01">`
Display:
**Translation by Hultzsch (1895)** OR **Translation by Hultzsch 1895**
OR
**Translation in English by Hultzsch (1895)** OR **Translation in English by Hultzsch 1895**
Related issues: 
-some translations are published with notes that we might want to reproduce and we will sometimes add our own notes to the reproduced translation. How are we to make the distinction between original notes and our editiorial notes?
-Daniel, you also mentioned the case of incomplete translations reproduced but completed by us for the untranslated bits. How are we to make the distinction between original translation and translation supplied by us?
-What about a disclaimer below translation of the type "(Original translation standardised according to DHARMA TG and EG)"? Or shall we make this clear on the webpage presentation or our editions? I would prefer a disclaimer in each individual edition. This disclaimer might also be the place to make explicit which parts of the translation are supplied by us.

* translation
case of a translation by us:
`<div type="translation" xml:lang="fra" resp="part:dotr">`
Display: 
**Translation by Donald Trump** ("Fake news!") (with **rump** in small caps; making thus clear this a DHARMA translation)
OR
**Translation in French by Donald Trump** ("Super amazing fake news!") (with **rump** in small caps) 

* commentary
Display: 
Display: 
`Hultzsch (1902-1903: 23, n. 2)` (which I would definitively prefer here, rather than `H (p. 23, n. 2)`, which I would use only in apparatus)

* bibliography, epigraphical lemma
Display: 
`Hultzsch (1902-1903: 23, n. 2)` (which I would definitively prefer here, rather than `H (p. 23, n. 2)`)

* bibliography, primary and secondary
This is the current display:
![image](https://user-images.githubusercontent.com/905870/79694208-34f9fa80-826f-11ea-9e84-5e7e0647a9d2.png)
Maybe the full stop is not necessary after the siglum or we can put instead " ◇ " OR " • " (see apparatus).
Display for what comes after siglum:
Rice, B. Lewis. 1905. Epigraphia Carnatica: Vol. X. Inscriptions in the Kolar District. Epigraphia Carnatica, 10.1. Mangalore: Basel Mission Press (published for Government). " ◇ " OR " • " See: Text of the inscriptions in Roman characters: 152, no. 227; Translations of the inscriptions: 126, no. 227.
Further issue: what to do when (and it will be the majority of cases) the first `<citedRange>` is a page: "See: p. 2." OR "See p. 2"
I confess my wish of having full bibliographical reference here is a problem and I will be fine with the EIAD display WITH a tooltip (mouse over name and date providing the FULL bibliographical reference), thus:
Rice 1905: Text of the inscriptions in Roman characters: 152, no. 227; Translations of the inscriptions: 126, no. 227.
Trump 2020: 236.

* bibliography, ARIE
```
<bibl>
  <ptr target="bib:ARIE1904-1905"/>
  <citedRange unit="page">32</citedRange>
  <citedRange unit="appendix">B/1905</citedRange>
  <citedRange unit="item">50</citedRange>
</bibl>
```
Display: ARIE 1904-1905: 32, Appendix B/1905, no. 50.

* bibliography, Āvaṇam

```
<bibl>
  <ptr target="bib:Avanam1991"/>
  <citedRange unit="volume">1</citedRange>
  <citedRange unit="page">23</citedRange>
  <citedRange unit="item">18</citedRange>
</bibl>
```
Display: 
Avanam 1991, volume 1: 23, no. 18.
NB: diacritics are not allowed in Zotero short titles. I have already discussed the matter with Axelle. I am fine with "Avanam". (It is too complex to display diacritics if not in the short title; if we decide to allow diacritics in short titles, then some should be updated with diacritics and it is pain in the ass)
NB2: in 2035, I will make individual zotero entries for articles from Āvaṇam, if time and God permit ...  

* in `<note>`
Display: 
`Hultzsch (1902-1903: 23, n. 2)` (which I would definitively prefer here, rather than `H (p. 23, n. 2)`)

Axelle, you can already point to us the transformation that appear to be more complex or very complex compared to others.

**Comment by ajaniak** [comment]
Manu, 

The most complicated cases are related to manipulating the content extracted from the API, but I should be able to handle it to follow your wishes.  

For the translation, why don't you use the `<note type="credit">`? see EG, p. 107.

**Comment by manufrancis** [comment]
Thanks, Axelle!
Will use the `<note type="credit">` as per EG, p. 107.
I note it in the updates to be done when I will revise my files (that is, after reading the EG first release version).
Will update my files
