### ISSUE TITLE
Kannada Transliteration

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#34]
Dear Andrew,

I hope you are safe and well, and managing to get work done during these weeks of confinement. (I am accumulating backlog on all fronts, but have not forgotten our Memorial Pillars — please continue to exercise patience.)

Right now I am writing because Dan and I are trying to push our Transliteration Guide to a next version. In this connection, we’d like to know what is the status of your text on Kannada romanization, and whether there is a chance to persuade you to align yourself with our proposal to represent independent vowels with capital letters in strict transliteration. Our current version is [here](https://github.com/erc-dharma/project-documentation/blob/master/guides/transliteration/DHARMA%20Transliteration%20Guide%20v1.2%20draft.docx).

Best!

Arlo

**Comment by aso2101** [comment]
Hi, and sorry for the long delay! The Kannada romanization paper is languishing, and I would guess that it definitely won't be published before the next version of your guidelines. For the specific issue at hand, I don't have any strong objections to using uppercase for independent/word-final versions of the letter (apart from my concerns about case-sensitivity in general), apart from a mild aversion, which I find it hard to explain completely. Perhaps it's because case-sensitivity recalls transliteration formats like H-K and SLP-1, which are useful, but unsuitable for published work. So while I have no objection to writing Ondu in my own transcriptions of manuscripts, I would probably much prefer to see °ondu in a publication (if strict transliteration is observed). Sorry to be irritating! (Perhaps you can say that representations like "°ondu" are acceptable as a placeholder for a future "Ondu," like "tat* tvam" is a placeholder for "tat· tvam"?)

**Comment by arlogriffiths** [comment]
Thanks Andrew!

@danbalogh : this response means, that what we now have in our draft for TG v3 is good on all relevant point, except that we should delete the URL for the google doc of Ollett & Pierce Taylor (forthcoming), because I don't think it was intended as a public document. Could you close this when it's done?

**Comment by danbalogh** [comment]
Done.
