### ISSUE TITLE
Zotero: bug with DHARMA CSL

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#38]
I can select and use the modified CSL, but it tends to disppear from the list so that I regularly need to go through the style selection process. This is not the case with other styles. Do you see what might be the cause of the problem?

**Comment by ajaniak** [comment]
hmm... it seems to happen but Zotero team wasn't able to explain it since people rarely uses local CSL. A solution would be to declare DHARMA style in the Zotero DB styles. But at the current state, I am not sure it will be accepted since it is nearly the same as the Chicago -17th. 

Do you see other necessary changes in it? Maybe we could discuss this also for the brainstorming meeting @manufrancis ?

**Comment by arlogriffiths** [comment]
Yes, @manufrancis, please add potential further customization of Zotero CSL to agenda. (But I am not sure it is worth Axelle's and our time and effort.)

**Comment by manufrancis** [comment]
Added to agenda.
