### ISSUE TITLE
display of <gap>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#39]
This is to discuss some issues with display of <gap>, not yet for immediate action by @ajaniak .

`<lb n="1"/><unclear>sva</unclear>st<supplied reason="lost">i</supplied> <gap reason="illegible" unit="character" quantity="1"/> va <gap reason="illegible" unit="character" quantity="10"/> ra <gap reason="illegible" unit="character" quantity="1"/> kra <gap reason="illegible" unit="character" quantity="1"/> vi <gap reason="illegible" unit="character" quantity="2"/>`

presently gives this display:

<img width="423" alt="Capture d’écran 2020-05-16 à 05 51 05" src="https://user-images.githubusercontent.com/835603/82109821-6617fe80-9739-11ea-8e29-6883c15e3cfd.png">

- instead of the letter "x" after the value of `@quantity`, I suggest we use "akṣ."
- I don't understand why "ca." is inserted for `<gap reason="illegible" unit="character" quantity="10"/>` — in any case, there should be a space between "ca." and "10x" (or "10 akṣ.")
- the fact that `<supplied reason="lost">i</supplied> <gap reason="illegible" unit="character" quantity="1"/>` are fused into a single [...] isn't really satisfactory
- have we discussed and rejected the possibility of using different brackets for `<gap>` and `<supplied>`?

**Comment by ajaniak** [comment]
The fusion of brackets for `<gap/>`and `<supplied>` is a feature of Epidoc, I can switch if off for dharma if you want to.

**Comment by ajaniak** [comment]
Do you have the last version of the stylesheets ? The first `<gap/>` doesn't have the part `ca.`, when I make it run on tfbBengalCharters00065
```(1)(sva)st[i 1x] va [10x] ra [1x] kra [1x] vi [2x]```

**Comment by arlogriffiths** [comment]
@ajaniak : thanks. I now have the latest stylehseet and "ca." has disappeared.

@danbalogh @manufrancis @AnneSchmiedchen  : please express your opinions on the other issues raised above.

**Comment by danbalogh** [comment]
1. Replacing the "x" with "akṣ." - isn't the x supposed to represent the fact that the gap is illegible (and not lost)? More on this below.
2. ca. should in my opinion not be used at all; I thought we had settled on ? At any rate, neither ca. nor ? should appear unless `@precision="low"`
3. fusing supplied and lacuna into a single set of brackets: indifferent to me, but if we stick to what I had proposed for gap display (displaying numbers instead of displaying a given number of × or + signs), then I think Arlo's way is better, i.e. show them in separate brackets.
4. Possibility of using different brackets for gap and supplied: as best I can recall, this has not been raised, nor rejected. I am, however, pretty sure that I pointed out somewhere that I consider it a very good idea to use the same kind of bracket for these two items, since both are in fact lacunae, and since Leiden does the same. I still think it is a very good idea.

I'm starting now with a much longer comment on <gap> display as a whole.

**Comment by danbalogh** [comment]
Okay, so it seems to me that <gap> display has been implemented in a way that surprises me. The last I know of the original issue, #19, was that [Arlo](https://github.com/erc-dharma/project-documentation/issues/19#issuecomment-620533481) said he was in agreement with the method I had suggested, and that if Manu and Annette could agree to that, I should re-formulate the final set of instructions. [Manu](https://github.com/erc-dharma/project-documentation/issues/19#issuecomment-620538764) agreed, though reluctantly and with the clause that it is for the moment. Annette never commented, so I never started to formulate the final set. Let me point out that before then, I had once already undertaken to re-formulate all the instructions when it seemed that we had consensus - but then Arlo came and said we should go back (in certain basic details) to what I had proposed earlier. I was therefore not willing to start yet another re-formulation before I was expressly told that we had consensus.
Then, suddenly, display was implemented and the thread was closed.

I must point out that things like [ca. 10x] for `<gap reason="illegible" quantity="10" unit="character" precision="low">` is nothing like any almost-consensus we had reached before, which was [×10?]. I suppose the x (lowercase X) stands for × (multiplication sign), and in that case it should not be replaced with "akṣ", since in that case we would have no distinction between lost and illegible lacunae (the former should be represented by a + sign instead of the ×). 

So how to proceed? Do we reopen that thread and rebuild display from scratch? Do we have consensus on how display should be handled? Or if some sort of consensus has been reached without my involvement and awareness that [ca. 10x] is the preferred display, then why am I being asked to express an opinion now?

**Comment by manufrancis** [comment]
Ooops! 
Sorry, Axelle, and sorry, Dan!
It is actually our (PIs) fault, failing to come to a conclusion and failing to give proper instructions. And it may also be that certain displays are there presently "by default" from the Epidoc transformation style.

Dan, could you reopen issue #19 and formulate the final set of instructions concerning the display of <gap>?

**Comment by danbalogh** [comment]
Many thanks, Manu, for your understanding and my apologies for speaking harshly above. I'll do that asap, probably on Tuesday morning.
