### ISSUE TITLE
EGD finalisation: issues/queries/additions

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#43]
* Epigraphical glossary

Add markup for words selected for the epigraphical glossary?
Suggestion: `<rs>` for the moment. With the possibility to markup also phrases?
Tag to be updated later (when we will have our lexica in XML, with each word having its ID to encode as `@ref`), e.g. 
`<rs ref="1033" form="gumuṇadoṣa">gumunadosa</rs>`

* Unfinished inscription

That is, not an inscription with `<gap`> at the end, but an inscription left unfinished (the text stops abruptly at the end of last line). 
I as markup necessary for such a case to indicate where the inscription is left unfinished?
OR
A note in teiHeader or commentary is enough? Possibly, with also a plain-text (or with some markup) mention in the translation?
 
NB: I have also an example of an unfinished inscription, with the date at the beginning, then a large number of lines un-engraved, then the signatures at the end.
What to do in this case? Markup? Note in teiHeader or commentary?

* Chiseled away portions

The inscription tfaPallava211 is a clear case where entire portions of the inscription have been, on purpose, chiseled away.
For the moment I have used `<unclear>` or `<supplied>` for the markup of these portions.
It might be useful nonetheless to make the distinction between the portions which are `<unclear>`/`<supplied>` because the text has been chiseled away from the portions  which are `<unclear>`/`<supplied>` for other reasons.
If so, what could be the `@` to `<unclear>` and `<supplied>`?
Shall we customise an `@reason` specific for DHARMA for chiseled away portions?

**Comment by danbalogh** [comment]
Manu, I'll address your items in separate responses.
1. Epigraphical glossary
I am reluctant to add something brand new to the EGD at this stage, but I understand that you want to get started with this. We could perhaps agree that it won't be in the EGD v1, but you start experimenting and we put whatever method you agree on in the next edition of the EGD. Or we could come up with a basic structure now and add it to the EGD, and flesh it out later on.
For the basic structure, I'll need you to work with Axelle to figure out what is best. I have never used `<rs>` before and so I'm not in a position to suggest best practice. It seems to me that items like `@ref="1033"` cannot be useful unless we already have a canonical list that can tell the encoder what "1033" means. Also, it seems that `@form` is not a TEI-compliant attribute of `<rs>`, so if it is used, our files will not be valid EpiDoc and, I think, also not valid TEI. What I would suggest is `<rs key="gumuṇadoṣa">gumunadosa</rs>`, which would align well with what the EGD now says about encoding names as equivalent to better-known names, and would give us the groundwork for creating a canonical list later on, from the values of `@key` already in use in the corpus. @ajaniak - opinion?

**Comment by danbalogh** [comment]
2. Unfinished inscription
I definitely do not think any encoding is needed in the normal case, i.e. an inscription left off before it is finished. Human-readable mention of the fact in the layout description is what I would suggest as the basic way of dealing with it. If the text stops in the middle of a word, then I would probably add an apparatus note as well. And if the understanding of the extant part is problematic because the text leaves off in the middle of something, then a note in the translation may also be a good idea.
If we can agree on these, do you want me to put these guidelines in the EGD somewhere?
As for your second case, I might try to encode a `<space type="vacat"/>`, but since we have agreed not to use "line" as the `@unit` of `<space>` anywhere, we can't encode a multiline vacat. So I suggest handling the case like this:

1. encode the date as line 1 (or, if it is several lines, then lines 1 to n)
2. encode a vacat  (with approximate size in characters) after the date, to the end of the first line (or to the end of the last line of the date)
3. encode the signature as line 2 (or line n+1 if the date is more than one line)
And describe the situation in the layout description.

**Comment by danbalogh** [comment]
3. Chiselled-away portions
This is most definitely a case of `<del>` used on a massive scale. See EGD §4.4/Premodern deletion. All the deleted portions should be wrapped in `<del>`, and within that you are free to use `<unclear>`, `<supplied>` and `<gap>` depending on what you can read/reconstruct. No need for any custom attribute values.

**Comment by manufrancis** [comment]
Dear Dan,

Thanks for you detailed answer!

As for 1. Epigraphical glossary.
With Axelle, we will setup an TEI-XML file for the epigraphical glossary.
Let us keep any mention of this for the next edition of EGD.

As for 2. Unfinished inscription.
Noted and agreed.
I leave it to you whether to mention it or not in the EGD.

As for 3. Chiseled away portions.
Yes, `<del>` of course. Thanks for the reminder.
