### ISSUE TITLE
Transformation for <abbr>

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#44]
Dear all, 

The Epidoc stylesheets have a display for `<abbr>` giving ```raḥ(- - -) 3``` for ```<abbr>raḥ</abbr> <num value="3">3</num>```.
Can you let me know if you want to keep this possibility and eventually adapt it to your expectations?

Best, 
Axelle

**Comment by danbalogh** [comment]
The built-in display solution looks OK to me as a provisional solution, though I would slightly prefer using angle brackets ⟨ ⟩ instead of parentheses, since (I believe) we're tending towards the use of angle brackets for text supplied by the editor, and I think the completion of abbreviations is akin to supplying text.
However, if anyone has a specific preference for any particular display, I'm happy to accept it.

**Comment by AnneSchmiedchen** [comment]
Dear Axelle, I also would prefer the use of angle brackets instead of parentheses.

**Comment by arlogriffiths** [comment]
sorry, I don't understand the example, where `<abbr>` and `<num>` seem to have no connection.

and thus I don't understand Dan's response, because there is nothing being completed about the abbreviation in the example.

since EGD 7.3 does not allow any expansion, I would assume that our transformation should not do anything at all to the contents of for `<abbr>` elements.

**Comment by danbalogh** [comment]
Arlo, I think `<num>` is not relevant to the question and was only included for context.  (- - -) is how the pre-built EpiDoc transformation displays an `<abbr>`  that is not expanded, where () is a "tag" for an expansion and - - - is an indicator of the fact that an expansion is not present. (Compare e.g. a(bc) for an expanded abbreviation.) I seem to remember you saying that at a later stage you did want to expand abbreviations, so it seems to me like a good idea to agree on how to display them, and to display unresolved abbreviations in a way analogous to the EpiDoc standard, i.e. displaying - - - within the brackets dedicated to expansions. (But I suggest deviating from the EpiDoc/Leiden standard in using angle brackets instead of round ones for that.)
I hope this is clearer than what I said above.
Not doing anything to the contents of <abbr> at this stage is also fine for me.

**Comment by arlogriffiths** [comment]
I prefer not adding any brackets as long as we are never given expanded abbreviations. If we still have any color available, we could think of marking text enclosed in `<abbr>` with a color.

**Comment by manufrancis** [comment]
I concur with Arlo. Abbreviations are not so common that they deserve immediate action. But ... it is true there are some abbreviations used and that we could already expand them. Although I must say, speaking about Tamil epigraphy, that there are no abbreviation (maybe some very rare examples), but symbol instead.

**Comment by arlogriffiths** [comment]
let me then propose that Axelle set up the transformation to apply a color (brown?) to text enclosed in `<abbr>` but only when it appears in `<div type="edition">`

**Comment by manufrancis** [comment]
I suggest to display, in `<div type="edition">`,
`<abbr>raḥ</abbr>`
as

> ⟨raḥ⟩

 all coloured (brown?)

**Comment by danbalogh** [comment]
Manu, if angle brackets are associated with editorial intervention (correction and normalisation), as I think they already are and as I feel they should be, then I think it is not a good idea to use angle brackets around anything that is actually present in the text. Enclosing the expansion of an abbreviation (when we come to that) in angle brackets is a good idea, but enclosing the abbreviation itself is not. If you feel that colouring abbreviations (brown or whatever) is not sufficient, then I suggest adding an empty ⟨⟩ after them, meaning that "this could be expanded but it has not been".

**Comment by arlogriffiths** [comment]
Please, let us keep things simple and just apply brown.

Manu: OK?

**Comment by manufrancis** [comment]
Fine with me. OK for our provisional hybrid transfo.
