### ISSUE TITLE
Display of the label inside <lg>

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#51]
Dear all, 

Could you let me know the expected display for the following encoding:
```
<l n="a"><milestone type="pagelike" unit="item" n="S"/><label xml:lang="eng">Southern Doorjamb</label><lb n="S1"/><g type="initialGomutra"/> <g type="dDandaOrn">.</g> jejīyatāṁ vraja <seg met="-+--+-+="><gap reason="lost" extent="8" unit="character"/></seg></l>
```

currently
‡ Southern Doorjamb <sup>**(S1)**</sup> jejīyatāṁ vraja [⏑–⏑⏑–⏑–⏓]

**Comment by danbalogh** [comment]
Many of the items are still the subject discussion between Arlo and me, so the encoding itself may change.
Is ‡ intended to indicate the presence of a milestone?
I suggest that a <label> be displayed in the same way as (S1) is displayed in your sample above. Arlo and I are still discussing whether or not to include the unit and n of the milestone in a label. When no `<label>` element is present as the first item after a milestone, then an auto-generated label (showing the value of unit and the value of n) is necessary, but perhaps not when a manually created label is present.
We are at the moment working on the basic type values permitted for symbols. If you need to devise a display solution right now, I would suggest the following:

- when `<g>` contains a . (full stop), display it as a placeholder character | ; when `<g>`  contains .. (two full stops), display as ||
- when `<g>` is an empty element, display a placeholder character depending on `@type` as follows:
  - if type="filler", display §
  - if type is anything else, display @ or any other provisional placeholder

Sometime soon, we'll want to replace this with a more nuanced display depending on `@type`, but we don't have the details of that. See the working document at https://docs.google.com/document/d/1glfyQnFqPrbVOYzegfjKIOVrc-vMgznEQ1iNsFf7DE8/edit?usp=sharing for some preliminary notes. Once these are finalised (for the present), we'll want display depending on `@type` for all g elements that are not numerals, regardless of whether they are empty or contain a full stop. And in the long run, as you know, we'll replace the provisional values of `@type` with a constrained list of values, plus a set of subtypes.

**Comment by arlogriffiths** [comment]
I would like the label to be moved in front of the enclosiong block-level container, in this case `<lg>`, something like this:

‡ Southern Doorjamb 
    I. Vasantatilakā
        (S1) jejīyatāṁ vraja [⏑–⏑⏑–⏑–⏓]

@ajaniak : does the fact that we are prescribing placement of the `<milestone>` inside rather than outside of the block-level container pose any problem for such display?

**Comment by danbalogh** [comment]
If placing a milestone outside the block-level container in such cases helps with display, I don't insist on it. As I think I mentioned both in comments to the Report and recently to Arlo, the only reason I want milestones inside containers is that sometimes they will have to be inside containers (being in the middle of text), and it's simpler and more consistent to say they should always be than to add special rules for placing them outside when they can be.

**Comment by ajaniak** [comment]
For now, it is ok to keep it like that. 
The display is now: 
‡ Southern Doorjamb
I. Vasantatilakā
(S1) jejīyatāṁ vraja [⏑–⏑⏑–⏑–⏓]

It also gives when the label is absent
‡
XVII. Vasantatilakā
(N1)Agre-saraḥ

**Comment by arlogriffiths** [comment]
Thanks. 
Could you insert a blank line between the header and the rest in display?
And present the whole header in bold face?

**Comment by ajaniak** [comment]
Is the result of the new implementation what you expected?

**Comment by arlogriffiths** [comment]
Screenshot from K0266.xml:

<img width="482" alt="Capture d’écran 2020-05-28 à 06 36 59" src="https://user-images.githubusercontent.com/835603/83099455-b5511e00-a0ad-11ea-86d5-d666310d1049.png">



1. yes, I like this. it works well for cases such as this where a physical boundary corresponds to a boundary in verse. it would also work fine if the context is prose.
2. but of course it wouldn't work if the `<milestone>` fell somewhere in the middle of an `<l>`. I have just tested by moving `<milestone type="pagelike" unit="item" n="N"/><label xml:lang="eng">Northern Doorjamb</label>` to stand inside a word in the first `<l>` and it doesn't make any change in display.
3. in such a case, I believe we'd want "‡ Northern Doorjamb" to be displayed in the same manner as `<pb>`, i.e. in superscript interrupting the word wherein the milestone falls.
4. is it feasible to make the distinction based on how we are presently encoding, or not?
5. if yes, please do so
6. if not, then we may consider whether a fine-tuning of encoding is possible that would allow you to customize the xslt in the manner I am proposing, or otherwise whether it is preferable to simplify your work by applying the `<pb>`-type display in all cases.

@danbalogh @manufrancis @AnneSchmiedchen : thoughts?

**Comment by danbalogh** [comment]
My mind is rather set on a distinction of diplomatic/logical editions. Our present display is a hybrid, displaying verse in a form that's on the logical side, but displaying prose in diplomatic form. In logical editions, I would prefer to display milestones inline (i.e. in pb-style) ALL the time, and this applies also to verse displayed in our present hybrid view. That said, I have no strong objections to displaying them as a heading when they are the first thing in a stanza, if the PIs prefer that. Axelle: what Arlo proposes above basically means that when a milestone is the first item within an lg, with no text before it, then it becomes a heading; otherwise it is displayed inline. I believe that should be possible to achieve, but I second Arlo's suggestion: if fine-tuning our encoding can help with that, then we can do it. One more thing: whatever display method we settle on for `<milestone type="pagelike"/>`,  `<pb/>` should behave in exactly the same way.

**Comment by ajaniak** [comment]
The current encoding is linked to the `<lg>`ancestor, if you want to change the behaviour, you need to change the encoding itself. 
I will implement it.

**Comment by danbalogh** [comment]
Arlo, ball's in your courts. Possible ways to go ahead:
1. (my preference) - stick to what the EG says, with which you seemed to be in agreement back when we discussed it. Namely: "this title [generated from `@n`, `@unit` and `<label>`] will probably be displayed as a heading in diplomatic editions, but as an inline label (so as not to break the flow of text) in logical editions". In our current hybrid display that would mean displaying it as a heading in prose and as an inline label in verse.
2. adapt our encoding practice to your preference, namely by explicitly permitting (or mandatorily enforcing) `<milestone>` and `<pb>` to be outside block-level containers when the structural break coincides with an intrinsic break. Display of titles would then have to depend on whether a `<milestone>` or `<pb>` element is a child of a block-level container (in which case display must be inline in a logical edition [verse in our hybrid display] and as a heading in a diplomatic edition [prose in our hybrid display]), or stands outside the block-level text containers (i.e. is a child of a `<div>`, in which case display must be always as a heading regardless of display type). I sort of like this idea because of its versatility and intuitive suitability to what we would want to see. Still, I'm a bit averse to it because of its complexity - it requires the encoder to pay attention to yet one more thing, and it requires a more complex display transformation.
3. adapt the display to your preference, i.e. ask Axelle to revise the current transformation so that a `<milestone>` or `<pb>` within an `<lg>` gets a heading-style display (moved to before the stanza) only if there is no text before it. The other considerations still stand for the long term, i.e. in diplomatic editions display must still be as a heading regardless of container, and in logical editions it must still be inline except in the above circumstance.

And by the way, please add your response to our discussion in the EG about showing `@n` and `@unit` in that title.
