### ISSUE TITLE
bibliography display 1: remove parentheses around Date

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#66]
The following code:

`<app loc="1r8">
<lem>yata<pb n="1v" break="no"/><lb n="1v1" break="no"/>n</lem>
<rdg source="bib:Brandes1889_01 bib:TitiSurtiNastiti2016_01">ya tan</rdg>
<note>Brandes and Titi Surti Nastiti read two words, but only one word is intended here (<bibl><ptr target="bib:Zoetmulder1982_01"></ptr><citedRange unit="entry">yatan</citedRange></bibl>).</note>
</app>`

Leads to this display:

<img width="944" alt="Capture d’écran 2020-09-23 à 06 36 33" src="https://user-images.githubusercontent.com/835603/93967376-5c497c00-fd67-11ea-9454-7eea852f669f.png">

Please remove parentheses around Date, so that `<bibl><ptr target="bib:Zoetmulder1982_01"></ptr><citedRange unit="entry">yatan</citedRange></bibl>` gets displated as "Zoetmulder 1982, yatan".

**Comment by ajaniak** [comment]
The exact opposite have been asked several months ago. So before removing it, it could be great if you agree on this, so i don't have to add it again at a later stage.

**Comment by arlogriffiths** [comment]
I don't know who requested you to add parentheses, and I don't know if it happened via a GitHub issue. If it wasn't in a GitHub issue, then it means there hasn't been any collective discussion about the matter.

Anyhow, since we need to be able to use `<bibl>` inside parentheses, as in the example above, it seems fairly obvious that the display of `<ptr target="...."/>` should not itself include parentheses.

**Comment by arlogriffiths** [comment]
@manufrancis @AnneSchmiedchen @danbalogh : your confirmation please.

**Comment by AnneSchmiedchen** [comment]
Yes, please NO parentheses around the date (year).

**Comment by danbalogh** [comment]
I agree with Arlo. Back when we had discussed citations for the EGD, our concept was that parentheses would not be included in the display. See EGD §10.4.5, "parentheses will not be automatically produced around citations and will have to be added in the surrounding text wherever you need them". I realise that this is about not auto-producing parentheses around the citation as a whole, but this is also relevant. As for parentheses around the date, if anyone needs them, e.g. to produce text line "Zoetmulder (1980) suggested blah blah", then they must avail of the markup `@rend="omitname"` , which we invented to allow the editor to put the date (and cited range, if present) in parentheses without including the author's name.
However, now that I've had a look there, I must admit the EGD is ambiguous about this, since in example 10.4.5.F it implies that parentheses *will* be auto-displayed around the date *if* the bibl element has `@rend="omitname"`. I myself have missed this and in my bibliographies I've been adding manual parentheses around bibl with omitname.
So, even if we're all in agreement that we don't want parens around the date of a regular bibl item, we still need to be sure we are on the same page for a bibl with rend omitname. Please let me know and I'll correct/clarify in the EGD.

One more thing. As we had agreed in the EGD, Arlo's code `<citedRange unit="entry">yatan</citedRange>` should display "s.v. yatan", not just "yatan".

**Comment by manufrancis** [comment]
Dear all,
Mea culpa! It appears I am the culprit who, too quickly, instructed Axelle to implement parentheses.
So, please, Axelle, no parentheses around dates, except when `@rend="omitname"` is used.

**Comment by arlogriffiths** [comment]
Readings Dan's response, I suggest rephrasing the request to Axelle to become simply:

- display of `<bibl>` and `<ptr>` should not insert any parentheses

And, @danbalogh, I suggest you make the necessary rewrites to ensure that EGD unquivocally states that any desired  parentheses in display should always be typed by the encoder. (Like you, I myself have been presuming the same in my encoding so far, and have told my team members to do the same.)

**Comment by arlogriffiths** [comment]
@manufrancis : please confirm your agreement on both points.

**Comment by danbalogh** [comment]
OK, so it seems we do all agree about no parentheses around dates (or anywhere) for a regular `<bibl>`.

But @ajaniak , before doing anything about `<bibl rend="omitname">`, please wait until we have a confirmed consensus here.

**Comment by AnneSchmiedchen** [comment]
Everything confirmed from my side.

**Comment by danbalogh** [comment]
It's probably simplest to implement and to keep in mind while encoding if parentheses have to be created manually whether or not `@rend="omitname"` is present. However, unless we can envisage situations where we need a biblio reference to appear without a name **and** without parentheses (I cannot), it may still be best to agree to auto-produce parentheses in that case. I'm not saying this to contradict Arlo, only to make it clear that I'm OK with either way and I want everyone to make an informed decision.
Situations where I **can** envisage using `<bibl rend="omitname">` are the following, with the text generated from the bibl element emphasised in bold.
1. "First edited by John Faithfull Fleet **(1884)**"
2. "I disagree with Fleet who claims **(1884: 128)** that blah blah"

**Comment by arlogriffiths** [comment]
@ajaniak: Daniel's last message has prevented the following message coming across clearly

- I consider it simplest to implement (and to keep in mind while encoding) if we postulate that parentheses have to be created manually
- therefore, display of `<bibl>` and `<ptr>` should not insert any parentheses, not even if @rend="omitname" is used

Since many of us have already been encoding based on the assumption that all desired parentheses need to be typed, I would like to insist for now on sticking to this practise. @AnneSchmiedchen @manufrancis : please confirm (again!) that you agree.

If you could change display on this point, then we following example will come out without double ((...)):

<img width="984" alt="Capture d’écran 2020-10-06 à 14 37 52" src="https://user-images.githubusercontent.com/835603/95202493-adcf1d80-07e1-11eb-8ffc-06d0519af818.png">

**Comment by AnneSchmiedchen** [comment]
Yes, I confirm that I agree.

**Comment by manufrancis** [comment]
Fine with me

**Comment by ajaniak** [comment]
Done
