### ISSUE TITLE
display: heading of English translation

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#70]
If we have code like this `<div type="translation" xml:lang="eng" resp="part:argr">`, it currently leads to display like this:

<img width="499" alt="Capture d’écran 2020-09-23 à 07 14 20" src="https://user-images.githubusercontent.com/835603/93969559-6e79e900-fd6c-11ea-8648-1a16895b3f3e.png">

I think the fact that the translation is into a given language should only displayed if that language is not "eng" and the author of the translation should only be displayed if s/he is different from the `part:`(s) claiming `<resp>intellectual authorship of edition</resp>`. In other cases, the heading should simply be "Translation".

@manufrancis @AnneSchmiedchen @danbalogh : agreed?

@ajaniak: is such a rule easily implemented?

**Comment by danbalogh** [comment]
I have no strong views on this, so OK by me if it is not too much trouble to implement. That said, I see no harm in specifying "English", and have a slight preference for making the name of the translator explicit even when identical to the editor. But whatever you agree on, I'll live with.

**Comment by manufrancis** [comment]
I am fine, as it is, and find it is just a detail worth bothering if easy to implement. Furthermore, as time flies, there are certainly much more important things to implement.
Making explicit the authorship does not cost nothing. I would keep it.
As for the language, OK for displaying only if the language is not "eng".

**Comment by arlogriffiths** [comment]
Thanks @danbalogh and @manufrancis for your responses. I see that I should have explained why I think the proposed rule would be worth implementing.

It is  because in the epigraphic lemma, we often need to say something about the history of translation. Example:

`<p>First transcribed by W. F. Stutterheim (<bibl rend="omitname"><ptr target="bib:Stutterheim1925_04"/></bibl>, with extensive corrigenda on p. 187); a corrected and partly normalized edition was then brought out, with Dutch translation, by the same scholar (<bibl><ptr target="bib:Stutterheim1935_01"/></bibl>), and these were reused by H. B. Sarkar for his publication with English translation (<bibl rend="omitname"><ptr target="bib:Sarkar1971-1972_01"/></bibl>); the plate was transcribed again by Boechari (<bibl rend="omitname"><ptr target="bib:Boechari1985-1986_01"/></bibl>, obviously without taking Stutterheim's corrigenda into account). Re-edited here, with a new translation, by Arlo Griffiths based on B.-Ph. Groslier's photos of the plates.</p>`

It seems to me *needlessly* and *disturbingly* inconsistent, then, to specify the translator in the heading of the Translation, whereas the heading of the Edition does not specify who is the editor.

Thinking about these matters, I wonder whether it would also be a good idea to specify @resp in `<div type="edition">` and whether doing so might help us do without the problematic `<resp>intellectual authorship of edition</resp>` (see n. 54 in EGD) in the teiHeader. With or without such changes to our encoding practice, it seems to me most elegant to use *only* the epigraphic lemma for making displayed statements about who is responsible for edition and translation.

Also for reasons of elegance (avoiding redundancy), seeing as English is our lingua franca, it seems evident to me that the language of the translation ought only to be specified if it is not English. But if others don't share this aesthetic judgment, I will not insist.

**Comment by danbalogh** [comment]
No objection to not specifying the language if it is English. For the other matter, yes, it is indeed redundant and to address that properly, we may need to revise some issues from bottom up. What we have now is a result of a sort of organic development, where - as I see it - we started out with the basic assumption that the key element of each XML file is the edition, and the creator of the file is normally the editor. Whenever not, this could, as a next layer of this onion, be clarified in the respStmt of the header. On the other hand, we had assumed from the start that translations would often not be the work of the current editor, so the EGD on translations has detailed instructions for various cases of this kind. And on top of all this, we now have the epigraphic lemma, a late addition to our arsenal. I can see how it is natural to add things like "Re-edited here, with a new translation, by Arlo Griffiths based on B.-Ph. Groslier's photos of the plates." to that lemma, but strictly speaking, the place for such information is not the section we call "bibliographs". It's OK to have it here, but I don't think it's a good idea to have it only here. I also don't think there's a point to adding a `@resp` to the edition division, since the person responsible for that is encoded in the header for the document as a whole. By the same logic, we could perhaps say that the translation division too should not carry a resp when the translator is the editor - but nothing wrong in making that explicit here. Finally, could you and Axelle not come up with a way to put this last sentence of the epigraphic lemma - with verbose, human-redable information on how the current edition arose - into the respStmt itself? I have not checked if paragraph text is permitted there, but that may be the best way out of this quandary.

**Comment by ajaniak** [comment]
Could you let me know if you have been able to reach an agreement on the subject please?

**Comment by danbalogh** [comment]
I have not heard anything on the subject since the comments above. Having thought again about language specifications and redundancy, I now think this should be handled "properly", perhaps by adding `@xml:lang="en"` to the body or text element of our files (@ajaniak , which one should it be?), and then using `@xml:lang` only on divs that are in a different language - as we already do in the edition div, and as Arlo suggests for the translation div. I'm not sure it's entirely "proper" to thus have the apparatus div inherit English as a language even though lemmas and readings are in the edition's language, but I think that should be straightforward to a human reader even if it is not to a machine. For `@resp` and intellectual authorship, I would like the PIs to make a decision (informed by my thoughts on this above, or ignoring them, as they please) and tell us all what we should do.

**Comment by arlogriffiths** [comment]
Thanks for your reminder, @ajaniak, and thanks for your suggestions, @danbalogh.

I will first give some interlinear reponses to Dan's previous comments, before listing my suggestions for what to do.

>  I can see how it is natural to add things like "Re-edited here, with a new translation, by Arlo Griffiths based on B.-Ph. Groslier's photos of the plates." to that lemma, but strictly speaking, the place for such information is not the section we call "bibliograph[y]". It's OK to have it here, but I don't think it's a good idea to have it only here. 

I disagree with this view. In my view (formed by contact with specialists of Greek epigraphy here in Lyon and no doubt influenced by Tom Elliott), the very raison d'être of an "epigraphic lemma" is to formulate such sentences about the genesis of the edition (and, by extension, of the translation). Although it isn't made clear in the EpiDoc Guidelines, I believe this is also the expectation of the EpiDoc community. See, e.g., the example in the following message sent to MARKUP by Tom Elliott, nearly 20 years ago (!): [https://lsv.uky.edu/scripts/wa.exe?A2=ind0108&L=MARKUP&D=0&P=10635](https://lsv.uky.edu/scripts/wa.exe?A2=ind0108&L=MARKUP&D=0&P=10635).

>  I also don't think there's a point to adding a @resp to the edition division, since the person responsible for that is encoded in the header for the document as a whole.  

Alright. By analogy, I will therefore suggest below that we cease using @resp also for translations.

>  By the same logic, we could perhaps say that the translation division too should not carry a resp when the translator is the editor - but nothing wrong in making that explicit here.

Not sure what "here" refers to. Anyhow, see my suggestions below.

>  Finally, could you and Axelle not come up with a way to put this last sentence of the epigraphic lemma - with verbose, human-redable information on how the current edition arose - into the respStmt itself? I have not checked if paragraph text is permitted there, but that may be the best way out of this quandary.

As I have explained above, I am convinced that we should use free-text `<p>` in `<div type="bibliography">` for such sentences.

>  I now think this should be handled "properly", perhaps by adding `@xml:lang="en"` to the body or text element of our files (@ajaniak , which one should it be?), and then using `@xml:lang` only on divs that are in a different language – as we already do in the edition div, and as Arlo suggests for the translation div. I'm not sure it's entirely "proper" to thus have the apparatus div inherit English as a language even though lemmas and readings are in the edition's language, but I think that should be straightforward to a human reader even if it is not to a machine. For @resp and intellectual authorship, I would like the PIs to make a decision (informed by my thoughts on this above, or ignoring them, as they please) and tell us all what we should do.

I agree with all of this.

So here are my suggestions (not all of them pertaining to translation) to be implemented by Dan and Axelle if @AnneSchmiedchen and @manufrancis agree:

- add to EGD and Template the rule that `<resp>translation</resp>` must be encoded inside `<respStmt>` 
- add to EGD the recommendation, for when it is felt that the present edition makes only marginal progress, or no progress at all, vis-à-vis a predecessor, to encode both the predecessor in question and your own role in `<respStmt>`, following this model:
`<resp>intellectual authorship of edition</resp>
               <persName ref="http://viaf.org/viaf/66465311">
                  <forename>George</forename>
                  <surname>Cœdès</surname>
               </persName>
               <persName ref="part:kuch">
                  <forename>Kunthea</forename>
                  <surname>Chhom</surname>
               </persName>`
- make explicit in EGD that the responsibilities for edition and translation encoded in teiHeader should find a human-readable counterpart towards the end of the epigraphic lemma, and that there should be no obvious discrepancy between the responsibilities encoded in teiHeader and those formulated in the epigraphic lemma
- change the guidance given in Template `<!-- replace year and name, use format "Forename1 Surname1 & Forename2 Surname2" or "Forename1 Surname1, Forename2 Surname2 & Forename3 Surname3"  if necessary — the copyright is that of the encoder(s) -->` to become `<!-- ... — the copyright is normally that of the scholars listed under respStmt as holding  intellectual authorship of edition -->`
- add `@xml:lang="en"` to the body or text element of our files, depending on Axelle's advice on what is best
- rewrite EGD to contain the rule that @xml:lang should be encoded in `<div type="translation">` only for those translations a file may contain which are not in English
- rewrite EGD removing the rule that encoders must use @resp "if the translation is by you and/or another project member", but rather allow use of @resp only if there are translations into more than one language and they have been made by different team members identified under `<resp>translation</resp>`  in teiHeader
- consequently, in display, the heading of a translation shall only contain "into LANGUAGE" if @xml:lang is found in the code for this div and shall be formulated (1) as "Translation into LANGUAGE from AUTHOR YEAR" if both @xml:lang and @source are encoded, (2) as "Translation into LANGUAGE by FORENAME SURNAME" if both @xml:lang and @resp are encoded, (3) as "Translation from SURNAME YEAR" if @source is encoded but not @xml:lang,  (4) as "Translation by FORENAME SURNAME" if @resp is encoded but not @xml:lang
- in case the @source corresponds to more than one AUTHOR or in case more than one @resp is encoded, the above formulations would become "... from AUTHOR & AUTHOR YEAR" (for two authors), "... from AUTHOR, AUTHOR & AUTHOR YEAR" (for three authors), "... from AUTHOR _et al._ YEAR" (for more than two authors), or "by FORENAME SURNAME & FORENAME SURNAME" (for two team members)
- finally, I suggest we do not use small caps for authors' names in the headings for translation, or indeed anywhere for authors' names in our display, as such usage belongs more to the German/French typographic traditions than to the English tradition(s)

I hope the above is clear and error-free...

**Comment by danbalogh** [comment]
I'm fine with most of what Arlo suggests; here follow some comments. 
> > I can see how it is natural to add things like "Re-edited here, with a new translation, by Arlo Griffiths based on B.-Ph. Groslier's photos of the plates." to that lemma, but strictly speaking, the place for such information is not the section we call "bibliograph[y]". It's OK to have it here, but I don't think it's a good idea to have it only here.
> I disagree with this view. In my view (formed by contact with specialists of Greek epigraphy here in Lyon and no doubt influenced by Tom Elliott), the very raison d'être of an "epigraphic lemma" is to formulate such sentences about the genesis of the edition (and, by extension, of the translation). Although it isn't made clear in the EpiDoc Guidelines, I believe this is also the expectation of the EpiDoc community. See, e.g., the example in the following message sent to MARKUP by Tom Elliott, nearly 20 years ago (!): https://lsv.uky.edu/scripts/wa.exe?A2=ind0108&L=MARKUP&D=0&P=10635.
In Tom's message that you link, I see nothing about giving the credits of the present digital edition in the bibliography division. Actually, more like the opposite: implicitly, in his suggested titles "bibliography", "works cited" and "sources cited", and quite explicitly in how he describes the bibliography division as "a simple list of every work and unpublished item cited anywhere else in the electronic text". For the lemma, his sample code has a whole `<div type="lemma">` of its own. Given all this, I still think that the best place for information about the current edition is not in the bibliography, but in the TEI header. However, in spite of having this private opinion, I'm OK with having it in the bibliography if that's where you (Arlo) want it, especially so if you've gathered in private communication with Tom and/or with epigraphists in Lyon that this is good practice. So, long story short, let's keep the sentence about the current edition in the epigraphic lemma, and let's keep the epigraphic lemma in the bibliograpy div.

> > By the same logic, we could perhaps say that the translation division too should not carry a resp when the translator is the editor - but nothing wrong in making that explicit here.
> Not sure what "here" refers to. Anyhow, see my suggestions below.
By "here" I meant "in the translation division". But the point is that we are in agreement, so no need to carry this further her.

>     * add to EGD and Template the rule that `<resp>translation</resp>` must be encoded inside `<respStmt>`
I find this redundant but I have no objection if everyone thinks it is necessary.

>     * add to EGD the recommendation, for when it is felt that the present edition makes only marginal progress, or no progress at all, vis-à-vis a predecessor, to encode both the predecessor in question and your own role in `<respStmt>`, following this model:
>       `<resp>intellectual authorship of edition</resp> <persName ref="http://viaf.org/viaf/66465311"> <forename>George</forename> <surname>Cœdès</surname> </persName> <persName ref="part:kuch"> <forename>Kunthea</forename> <surname>Chhom</surname> </persName>`
This `@ref` on the `<persName>` is not mentioned anywhere in the EGD. If you want to adopt this as our recommended/mandatory practice, I'll need you to add instructions about it to the guide. For the rest, I agree and welcome this.

>     * make explicit in EGD that the responsibilities for edition and translation encoded in teiHeader should find a human-readable counterpart towards the end of the epigraphic lemma, and that there should be no obvious discrepancy between the responsibilities encoded in teiHeader and those formulated in the epigraphic lemma
Sounds good to me, with my above reservations about redundantly mentioning the translation.

>     * change the guidance given in Template `<!-- replace year and name, use format "Forename1 Surname1 & Forename2 Surname2" or "Forename1 Surname1, Forename2 Surname2 & Forename3 Surname3"  if necessary — the copyright is that of the encoder(s) -->` to become `<!-- ... — the copyright is normally that of the scholars listed under respStmt as holding  intellectual authorship of edition -->`
Sounds good.

>     * add `@xml:lang="en"` to the body or text element of our files, depending on Axelle's advice on what is best
Axelle, please advise.

>     * rewrite EGD to contain the rule that @xml:lang should be encoded in `<div type="translation">` only for those translations a file may contain which are not in English
Good.

>     * rewrite EGD removing the rule that encoders must use @resp "if the translation is by you and/or another project member", but rather allow use of @resp only if there are translations into more than one language and they have been made by different team members identified under `<resp>translation</resp>`  in teiHeader
I'm not sure I have followed through all implications of this in all possible cases, but essentially, I'm fine with this.

>     * consequently, in display, the heading of a translation shall only contain "into LANGUAGE" if @xml:lang is found in the code for this div and shall be formulated (1) as "Translation into LANGUAGE from AUTHOR YEAR" if both @xml:lang and @source are encoded, (2) as "Translation into LANGUAGE by FORENAME SURNAME" if both @xml:lang and @resp are encoded, (3) as "Translation from SURNAME YEAR" if @source is encoded but not @xml:lang,  (4) as "Translation by FORENAME SURNAME" if @resp is encoded but not @xml:lang
Sounds good to me. To phrase this differently, the heading of the translation should always show "Translation", followed by 1) "into LANGUAGE" if `@xml:lang` is present; 2) "by FORENAME SURNAME" if `@resp` is present; and 3) "from AUTHOR YEAR" if `@source` is present.

>     * in case the @source corresponds to more than one AUTHOR or in case more than one @resp is encoded, the above formulations would become "... from AUTHOR & AUTHOR YEAR" (for two authors), "... from AUTHOR, AUTHOR & AUTHOR YEAR" (for three authors), "... from AUTHOR _et al._ YEAR" (for more than two authors), or "by FORENAME SURNAME & FORENAME SURNAME" (for two team members)
Fine, if such situations do occur. For more than one author, are you thinking of cases where the same translation verbatim is included in several publications? Does this occur? If yes, wouldn't it be sufficient to use the first of these as `@source`? For more than one team member, we should indeed do this, and make it explicit in the EGD that multiple participants may be shown in the `@resp` of a translation.

>     * finally, I suggest we do not use small caps for authors' names in the headings for translation, or indeed anywhere for authors' names in our display, as such usage belongs more to the German/French typographic traditions than to the English tradition(s)
I second that.

One more final suggestion by me. If we're set on including a statement on the authorship of a translation in the epigraphic lemma, then we should dispense with the "credit note" of translations (EGD §9.2.2), and the contents of this should instead be right there in the epigraphic lemma.

**Comment by arlogriffiths** [comment]
- about encoding translators in respStmt: it seems most elegant to me to have both a properly encoded record of responsibility and a human readable expression of the same, just as we do for editors. I don't see why encoding translators of an inscription would be more redundant than encoding editors of the same
- @ajaniak may please advise us on whether or not it is a good idea  to use @ref with VIAF ID in `<persName>` for people listed in respStmt who are not participants of DHARMA
- I meant cases where a @source points to a publication signed by more than one author, e.g. "Francis & Schmiedchen 2014", and how the various possible remifications of multi-author publications are to be displayed
- I have so far never used the "credit note" offered by EGD 9.2.2 and have no objection to implementation of Dan's suggestion

@manufrancis @AnneSchmiedchen : your opinions please. When we have them, and if they don't raise new complications, perhaps @danbalogh could summarize all of the above in a list of tasks for himself and for @ajaniak .

**Comment by danbalogh** [comment]
I find the double record of translators redundant to the same degree as the double record of editors, not more redundant. But I'm OK with both. I understand the multi-author issue now.
Agreed on all points. When we have agreement from Annette and Manu, I'll summarise - and if in that process it turns out we have more details to clarify, I'll specify those.

**Comment by manufrancis** [comment]
After discussion with Axelle, here are some thoughts:
(1) we need to distinguish between encoding the information and displaying the information
(2) `<respStmt>` does not seem the be the place to properly encode the information because (1) this is meant for the responsibility of encoding the file and (2) it complicates or even impedes machine-action.
(3) the proper place seems to be in the translation div, with an `@xml:lang` +`<resp>` (for a translation by a project member) OR `<source>` (for a reproduced translation).

Please, Axelle, correct me if I am wrong.

I am more concerned by encoding the information than by the display issue.
As for displaying the information I am in favour of being the most explicit, even at the risk of redundancy. I find it more straightforward and user-friendly to immediately see who is responsible for the translation, when he did translate, and in which language (rather than having to go the epigraphical lemma).
So for the display, I am afraid I have not much time to ponder about it now and leave you the hand on this, but I feel free to come back to these later on and suggest another display (and change in the transformation code).

**Comment by arlogriffiths** [comment]
1. of course we need to distinguish between encoding the information and displaying the information
2. what you say about respStmt is a bit surprising to me, and I am not sure that we need much machine-actionability on respStmt, but if we do need such machine-actionability, and especially it is true that respStmt should be reserved for listing people involved with encoding the file, then we need in any case to change our present encoding practice and EGD, which prescribes use of ` <resp>intellectual authorship of edition</resp>`
3. I can certainly live with encoding such information only in the `<text>` node of the files, using @resp and @source — but if we do it for `<div type="translation">`, it will raise the question whether we should or shouldn't also do the same for `<div type="edition">`, `<div type="apparatus">`, `<div type="commentary">` and `<div type="bibliography">`. **Does anyone have opinions on this question?**

Since the TEI seems on the whole to condone or even promote various forms of redundancy, I still wonder whether an argument should/could be made for doing all three: (1) distinguishing responsibilities in respStmt in a manner somewhat more detailed than we are currently doing (i.e., covering at least "encoding", "editing" and "translating"), (2) using @resp and @source in the `<text>` node where it serves purposes of machine actionability, and (3) recording the scholarly responsibilities ("editing" and "translating") in human readable form in the epigraphic lemma.


people as experienced with TEI as Tom Elliott and Emmanuelle Morlock have advised me

**Comment by ajaniak** [comment]
2. `<respStmt>` is used for people involved in the project. If you are reusing a translation without changing it, I wouldn't not declare it in a `<respStmt>`, the same could be said for reusing an edition made initially by Georges Coedes for instance. But we can keep the current `<respStmt>` pattern, if you are more confortable with it and against adding a new layer for the origin of the data itself as we have add it for Campa and EIAD. @alevivier can you give us your opinion on the subject as well and regarding the technically dealing of the metadata please? 

3. The @resp might be necessary for the reviewing process, if you want to add a layer in the apparatus or whatever, and should be used only if the content (of the translation in this case) is not from the same intellectual authorship as the rest of the text or if a shared responsability has to be clarified. It works as the @source but with the internal perspective of the project so to speak. As Daniel has already stated above, the current pattern has been inherit from previous version. 

Regarding the `@xml:lang`, we put it at the <teiHeader> level because if it was disagree to  have to repeat @xml:lang each time the language wasn't english. So the current state is in fact that some part of the files have language declared while others don't. If you want to change it, I would recommend putting the @xml:lang on the root and add @xml:lang each time it isn't english.

**Comment by alevivier** [comment]
2. About using `<respStmt>`, it seems to me that it describes the editors involved in the project. In the metadata model, reusing data from a previous edition/project is described in the 'Management of digital resource' with a Dublin Core tag `<dcterms:source>`, so in the xml file it could be described in a `<sourceDesc>`.

**Comment by danbalogh** [comment]
I am no longer able to keep in mind all the ramifications of this issue. I have offered above to summarise the opinions given by others, but can only do so for the smaller issue at the original core of the thread, namely the language of a translation and, by extension, anywhere else. I think we are close consensus there, to wit:
1. In future, we shall specify `@xml:lang="en"` on the `<TEI>` element (unless I misunderstand Axelle's comment above, that she recommends doing so "on the root")
* If consensus is confirmed for this, then
  * I shall mention and explain this at an appropriate place in the EGD
  * Axelle should incorporate it in the template (i.e. add `@xml:lang="en"` to `<TEI>` _and remove_ `@xml:lang="en"` from `<teiHeader>`) and, if possible, do the same in all already existing XML files or, if this is not feasible, assist encoders who need it to do it in all their files
2. Other than the above, `@xml:lang` shall only be used on elements whose language is _not_ English, since all descendants of the root element will be understood to inherit `@xml:lang="en"` unless otherwise specified. Thus, explicitly, `@xml:lang="en"` shall _not_ be used on translations into English.
* If consensus is confirmed for this, then
  * I shall make the appropriate changes to the EGD.
  * Axelle should, if possible, remove any instances of `@xml:lang="en"` on any `<div type="translation">` in all previously existing XML files, or assist people who need assistance in doing so for their own files.
  * To make our code nicer and leaner, we should perhaps also remove instances of `@xml:lang="en"` on any `<head>` that is a descendant of a `<div type="translation">` that does not have a non-English language explicitly specified. Retaining those is not a problem, only redundant. If we do want to remove them, then I'll need to say that in the EGD and Axelle will need to handle it in existing files.
* we do have one murky detail here: what is the language of an apparatus criticus? I believe we don't need to bother with every nicety and we can consider the apparatus to be in English. If that is the case, we can simply keep the apparatus div as it is, as it inherits "En" as its language from the root element. We would thus implicitly assume that all `<lem>` and `<rdg>` elements are in the language of the edition and do not need to be tagged explicitly for language even though in principle they inherit "En". If consensus is confirmed for this subpoint, then we have nothing further to do, except that perhaps any `<head>`  elements in the apparatus should also have their existing `@xml:lang` attributes removed and the EGD should mention that these shall not be used in the apparatus - though there is no harm in retaining them, as above.

For the above, could we have an explicit confirmation from @arlogriffiths , @manufrancis  and @AnneSchmiedchen , along with an opinion on 1) whether to retain any redundant `@xml:lang` on `<head>` elements or remove it; and 2) whether they agree with what I say above about the language of an apparatus? (Unless someone objects, my preference is the path of least resistance and least effort, namely to permit the redundant `@xml:lang` and to keep the apparatus as it is.)

As for the rest of this thread, I think the PIs should come to a consensus informed by @ajaniak and @alevivier . I'll be happy to accept whatever resolution they reach and make the necessary changes to the EGD.

**Comment by manufrancis** [comment]
Fine with me, if validated by Axelle and Adeline

**Comment by manufrancis** [comment]
One afterthought = argument in favour of displaying systematically the translator's name.
I will have Pallava inscriptions editions with a translation in English (by myself) and a translation in French (by Sylvain Brocquet).
But the edition will be by both of us DHARMA members.
The respective responsibilities will be mentioned in the epigraphical lemma, but I find, for the user, more straightforward and user-friendly to immediately see who is responsible for the translation.

**Comment by arlogriffiths** [comment]
- I confirm my agreement with points 1 and 2 formulated by Dan.
- I vote for removing redundant @xml:lang on `<head>` elements.
- I agree with what Daniels says about apparatus

I think that Manu's afterthought cannot be dealt with until we have decided how to use the teiHeader for recording responsibilities. 

If there is any chance we revert to my suggestions in [https://github.com/erc-dharma/project-documentation/issues/70#issuecomment-703108499](https://github.com/erc-dharma/project-documentation/issues/70#issuecomment-703108499), which I still find the best proposal on the table, then I would say that Manu's example is a case where @resp should be encoded on the respective translations, but that the need to encode and display responsibility _in some cases_ is not an argument for _always encoding and always displaying_ @resp on translations.

**Comment by danbalogh** [comment]
Thanks, Arlo. I think we should get the xml:lang issue I summarised above out of the way quickly, so that you can then come to a more leisurely decision about responsibility and authorship. On that matter, I can accept everything Arlo suggests in the comment he cites above and would like to leave the final decision in the PIs' hands.
On the quicker matter, @AnneSchmiedchen , please let us know if what I say in https://github.com/erc-dharma/project-documentation/issues/70#issuecomment-704366208 above is acceptable. @ajaniak , please confirm that you meant we should add `@xml:lang` to `<TEI>`. @manufrancis was there anything else in that matter that you think needs express approval from Axelle or Adeline?

**Comment by ajaniak** [comment]
The `@xml:lang` on the `<teiHeader>` have been moved to the `<TEI>` root and the `@xml:lang` on `div[@type='translation']` have been deleted on all the XML files.

**Comment by danbalogh** [comment]
Thanks. I assume then that we have consensus on this, so I've made the corresponding changes in the EGD (for the time being, in the GDoc only; I'll make the same changes in the DOCX master version in due course).

There was one more thing that needed to be dealt with: `<head>` elements in translation divisions. You have not changed those yet, so I'm not rewriting the EGD in that respect. But I think we should go ahead with it. Arlo above has agreed to my suggestion that we should remove `@xml:lang="en"` from these unless the parent translation division has a (different) `@xml:lang` on it, and nobody has objected.

Thus, in my Cālukya files where there is routinely a seal and a main textpart, the corresponding textpart divs have been created in all translations as we agreed a long time ago (though I never actually translate the seals, since they contain only a name). And in most of these, I have an English translation by me and a French one by Perrine Estienne-Monod. So, at present the code is:

```
<div type="translation" resp="part:daba">
  <div type="textpart" n="A"><head xml:lang="eng">Seal</head>
  </div>
  <div type="textpart" n="B"><head xml:lang="eng">Plates</head>
    <p>blah blah</p>
  </div>  
</div>

<div type="translation" xml:lang="fra" source="bib:Estienne-Monod2008_01">
  <div type="textpart" n="A"><head xml:lang="eng">Seal</head>
  </div>
  <div type="textpart" n="B"><head xml:lang="eng">Plates</head>
    <p>blah blah</p>
  </div>  
</div>
```

In the above, the `<head>` elements in the English translation should lose their `@xml:lang`  since it is English, like the translation; but those in the French translation should retain it, since the translation is in French, but the heads are in English.

@ajaniak : can you do this too in all existing files? Or was there some reason why we should not do this? Let me know, and if we're all agreed that this is the way to go, then I'll change that in the EGD too.
