### ISSUE TITLE
hyphen inside compound at line break

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#76]
@danbalogh : In TG 2.6.2 we formulate these rules —

"if you use hyphens for editorial compound analysis, and a physical line break coincides with such a hyphen, then first encode the physical line break as one inside a word (as per EGD §3.2.4 [...])" and "then put the editorial hyphen at the beginning of the new line".

I am not sure I have ever understood why the hyphen needs to be placed after the `<lb/>` but in any case I have been following these rules. Now I see that the following bit of code  

`soA<supplied reason="lost">ṁ</supplied><lb n="2r4" break="no"/>-soAṁ,`

leads to two hyphens in display. See the transition from 2r3 to 2r4 in this clipping:

<img width="809" alt="Capture d’écran 2020-09-24 à 18 38 06" src="https://user-images.githubusercontent.com/835603/94174102-21ddfd00-fe95-11ea-87ff-44dc65e747a3.png">

Does this mean our rules need to be reformulated or do we need to formulate a rule for Axelle to integrate into her transformation patterns?

**Comment by danbalogh** [comment]
To me, this seems fine as it is. A hyphen is displayed at the end of the line is `@break="no"`. As a consequence of this, we cannot put a compound-segmentation hyphen at the end of the line (because it would be indistinguishable in display from a word-break-hyphen). Ergo we have to put the segmentation hyphen after the `<lb/>`. Thus, when an `<lb break="no"/>` meets a segmentation hyphen, we get two hyphens, one at the end of the line telling the reader that a word is broken by the line break, and one at the beginning of the next line, telling the reader that the break is between members of a compound.
What would you do differently? Possibilities I see are:

1. forget about displaying a hyphen when `@break="no"`, in which case any segmentation hyphen can be moved to the end of the line. This is what I did in Siddham, but tou don't want to do this.
2. forget about using segmentation hyphens. I could live with that if you insisted, but I think you've come around to my viewpoint that they are useful, so we don't want to do this.
3. introduce a custom value, e.g. `@break="cpd"` for line breaks at in-compound boundaries, and not add an actual hyphen at such points. This is not regular TEI, but it validates. We could then display a different kind of hyphen at the end of the line (or whatever display solution you have in mind). I'm against this because it's a custom method and because it would make our encoding strategy much messier, since we would have to keep in mind not to add a hyphen for compounds when a line break is involved.
4. if the appearance of a hyphen at both the line end and the next line beginning bothers you, I'm sure Axelle could, sooner or later, come up with a solution to display a special hyphen at the line end (and nothing at the line beginning) when a line break is followed by a hyphen.

My suggestion is to keep everything as it is. If this is really unacceptable to you, we could try 4, as you suggest above.

**Comment by arlogriffiths** [comment]
Thanks. I had simply assumed that our intention was to merge word-breaking hyphen and text-segmentation hyphen in display and that only the word-breaking hyphen, due to `<lb break="no">`, would be shown, at the end of the line. _This is a 5th possible scenario that you do not list._ If that was not your intention, and if @AnneSchmiedchen and @manufrancis are also fine with displaying two hyphens as in the example above, then we can close this issue.

**Comment by danbalogh** [comment]
Indeed, hiding the segmentation hyphen when a word-breaking hyphen is present was **not** my intention and I explicitly think it would be a bad idea to do that. I think a hyphen at line-end and another at line-beginning is fine. Let's see what the others think.

**Comment by AnneSchmiedchen** [comment]
I have no problem with a hyphen at the end of a line and another one at the beginning of the next line. As far as I remember, compound-segmentation has not been made compulsory. Correct?

**Comment by danbalogh** [comment]
Correct, the use of hyphens for compound segmentation is optional.
