### ISSUE TITLE
Cheatsheet/Transformation scenario

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#8]
Difference of display between (1) physical/diplomatic and (2) logical.

NB1: could not assign Annette (as not yet registered on github?)
NB2: Arlo, please validate and refine instructions given below. Notably display of 

(1) physical/diplomatic
`<p>`, `<lg>`, `<l>` not to be displayed. 
`<lb>` to be displayed as the beginning of paragraph/line

(2) logical
`<p>`, `<lg>`, `<l>` to be displayed.
Chariot return after each `<l>` for Tamil verse.
Chariot return after `<l n="b">` and `<l n="d">` for Sanskrit/Prakrit verse (when 4 `<l>` per `<lg>`).
Chariot return after `<l n="ab">` and `<l n="cd">` for Sanskrit/Prakrit verse (when 2 `<l>` per `<lg>`).
`<lb>` displayed inside paragraph.

See for instance EIAD 160.

**Comment by arlogriffiths** [comment]
But we had decided yesterday that we are asking Axelle to create a hybrid display.

I believe the rules for display of `<l>` and `<lg>` need to be reformulated, taking into account our use of `@enjamb`. I think @danbalogh will most easily be able to formulate the rules we need, and @ajaniak can study what is done in Tom Elliott's stylesheet for Campa (where we did not use `@enjamb`) and make the necessary adjustments.

**Comment by manufrancis** [comment]
My understanding was:

Instead of 2 separate XSLT, one for physical and one for logical, 1 hybrid XSLT from which we derive the two displays.

**Comment by danbalogh** [comment]
My understanding was that of Arlo's, i.e. that we want just one hybrid display, and separate physical and logical displays will be created later on for the website (using ODD), but not for our personal use in Oxygen (using XSLT).
I have no particular suggestions or desires concerning the hybrid display. I guessed that it would follow physical structure (thus, @enjamb would be irrelevant to it, along with <lg>, <l> and <p> and<ab> in general), but display something about editorial intervention.
It would be best if we could have the XSL used to create the HTML Manu showed us yesterday, along with some instructions for setting it up in Oxygen, and then start playing around with it. Having tested it on some of our inscriptions, each of us could come up with suggestions on what could or should be rendered differently.

**Comment by arlogriffiths** [comment]
I suggest that we avoid reinventing the wheel and stick as closely as possible/desirable to the Campa stylesheet made by Tom Elliott. This means displaying verse text as verse and prose text as prose. For that purpose, @danbalogh, please formulate the presentation rules for Sanskrit/Prakrit verse. (This will anyhow be necessary also in the longer term for the ODD).

**Comment by arlogriffiths** [comment]
Manu: in response to you message, (I believe) only one display can be made with one XSLT. So having Dan's and my understanding was one XLST for a hybrid diplomatic/logical display. Take a look at the Campa website to see what this means.

**Comment by danbalogh** [comment]
One XSLT can produce two or more displays if there are parameters involved. But we agreed, as I understood it, that creating more than one display would complicate Axelle's work and it is not essential for us to have two at this stage.
I'll think a bit about presentation rules and will summarise here what I think should be done. I can't express that in XSL terms and I'm not sure exactly what happens in the Campa transformation, but if anything is amiss in my summary to come, I'll count on you others to let me know.

**Comment by danbalogh** [comment]
Having had a look at the HTML of verses displayed on the Campa site, I think most of what is there can stay, i.e.
for each `<lg>` create a `<div>` containing
a `<span>` with the @n of the `<lg>`
a `<span>` with the @met of the `<lg>`
a `<div>` for each `<l>`, containing the content of that <l>
Each of these elements should have a particular class so they can be styled in CSS.
I see that in Campa, the first `<l>` of an `<lg>` has a different class. Exactly how stanzas are rendered on screen does not really matter to me, but I think it would be best if we gave them different classes based on the @n of each `<l>` rather than on their position. This way, we could style the lines depending on whether those @n-s are:
1. "ab", "cd" (possibly add "ef", "gh" just in case) - give them a class "matravritta" or something; such lines would, I believe, be displayed without indentation.
2. "a", "c" (and, just in case, "e" and "g") - class "varnavritta-odd", display without indentation
3. "b", "d" (and "f" and "h") - class "varnavritta-even", display with indent
4. [any numeral] - class "verse-line" or whatever; display as we see fit (at present, the EG prescribes numeral @n for `<l>` in Tamil verse and nowhere else)

Within an `<lg>`, all content should be displayed in the same way as elsewhere (in prose), EXCEPT the following:
1. `<lb>`, `<pb>` and `<milestone>` (and `<cb>` if we reintroduce that instead of `<milestone type="pagelike">`) must never start a new line; instead, they will have to be displayed as inline labels.
I'm not sure if we need hyphenation before inline versions of these elements with @break="no": I guess that elsewhere, where we start new lines for these, we'll display hyphens at the end of the previous line. But in verse, this is perhaps not necessary; instead, it may be better to put no space before or after these labels if @break="no", but add a space before the label if @break is not present.

2. if any `<label>` elements are present (after a `<milestone>` or `<cb>` if applicable), then these too will have to be displayed inline


Additional considerations:
1. a hyphen will need to be generated in display at the end of the `<div>` corresponding to each `<l>` that has @enjamb="yes"

2. if the @met of an `<lg>` contains no alphabetic characters (or figure out some other way that can filter for @met with a prosodic formula instead of a metre name), then we need to search and replace the characters + - = to conventional prosodic code (as in Appendix B of the EG), so e.g.
`<lg n="1" met="-+---++-++-+-++-=">` gets a label with proper prosodic symbols instead of pluses and minuses.

I can't think of anything else now; if possible, I'd like to see the above implemented, and then test it on a couple of texts. If anything above is not clear, ask away.

**Comment by ajaniak** [comment]
I have set up the [folder](https://github.com/erc-dharma/project-documentation/tree/master/stylesheets)  with the Campa's Stylesheets. The set up details are briefly explained in the readme.

**Comment by danbalogh** [comment]
Thanks for the instructions. I've managed to set this up and it runs.

**Comment by ajaniak** [comment]
A few remarks while implementing 
- About the `@n` of the `<lg>`: a lot a files don't have a `@n`, so I made an error message. I convert the Arabic number into a Roman, let me know if i shouldn't have done so. 
- About the `@met` of the `<lg>`:  I added an upper-case to the first letter of the `@met` and I created an error message as well but I couldn't find if this attribute was mandatory within the EG.
 
For now they are displayed on their own line together before the rest of the `<lg>`. Let me know, if you want something else.

**Comment by danbalogh** [comment]
- @n is indeed mandatory, so the error message is good to have.
- The PIs will have to decide about conversion to Roman; in the EG, Arlo and I had agreed to write only "when it comes to displaying editions, we may choose to auto-convert stanza numbers into Roman numerals throughout our corpus or for specific subcorpora".
- @met is mandatory as stated in EG §2.2/Overview, but Manu and I have discussed making it optional for Tamil texts. Unfortunately I don't remember what we finally settled on, and there is no comment attached in the EG. I'll clear that with Manu; I think the error message can stay for the time being.
- I would prefer not to use an uppercase initial for metre names, which are not proper names to my mind but technical terms (I would also not use uppercase for Western terminology like sonnet or hexameter). But let's wait on what the PIs say to that - I can live with uppercase if it is deemed preferable.

**Comment by manufrancis** [comment]
Understood for mandatory @n with `<lg>`.
For Tamil texts, where there is often only one `<lg>`, would it be easy not to have display of the @n of `<lg>`?

As for @n of <lg> auto-converted to Roman numeral, I think it makes sense with scholarly practice for Sanskrit/Prakrit verse. 

As for the @met, let us keep it mandatory also for Tamil verse. (I think this was the outcome of my discussion with Dan).

As for the diplay of metre names, why not lowercase initial and italics? (with italics as marker that this is not written in the record)

**Comment by danbalogh** [comment]
I agree with lowercase and italics for the metre.
Thanks, Manu, for confirming mandatory @met before I even got in touch directly :)
Roman numerals for @n may be a SE Asian convention; I've never seen it done with Indian texts and I'm not fond of the idea, but can live with it if it gets voted in.
As for mandatory @n: if you (Manu) prefer, I can also make it optional, to be used on a Task Force level. Let me know if you would prefer that. Since we no longer want to refer in apparatus @loc to stanzas, it is not essential to have a number. I do think though that it's tidier if we always do, and we may still decide later on that we need to refer to a specific stanza in some way. So if Axelle can handle not displaying the @n if there is only one stanza, and I guess she can without much trouble, then that may be the best way to go.

**Comment by arlogriffiths** [comment]
my preferences:

- roman numerals for value of `@n`
- I consider meter names to be 'names', so for me display with initial capital would make best sense; displaying them in italics is fine with me
- I would like to see layout of `<lg>`s after the model in the screenshot attached
 -- special indentation
 -- stanza number in left margin, meter name at the same height

<img width="694" alt="Capture d’écran 2020-03-26 à 15 52 10" src="https://user-images.githubusercontent.com/835603/77660624-dc8a5280-6f79-11ea-8f43-adc400e32c18.png">

**Comment by ajaniak** [comment]
@manufrancis, I have implement the exception of the display for `@n`. The conditions are based on the `@xml:lang` with value  "tam" and "tam-Latn" on any `<div>`. 
But you would rather I display the `@n` if there is more than one `<lg>`?

**Comment by ajaniak** [comment]
So far, I have only added the italic for `@met`, since you don't seem to agree. I guess I could display Roman or Arabic depending on the languages of the edition...

**Comment by arlogriffiths** [comment]
yes, the constraint is not language-bound but bound by the value of  `@n`.

- if n > 1, then value is to be displayed
- if n = 1, then no value is to be displayed

Le 27 mars 2020 à 10:03, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



@manufrancis<https://github.com/manufrancis>, I have implement the exception of the display for @n. The conditions are based on the @xml:lang with value "tam" and "tam-Latn" on any <div>.
But you would rather I display the @n if there is more than one <lg>?

**Comment by danbalogh** [comment]
I suppose Arlo means that if n=1, that value should still be displayed if the document as a whole includes stanzas with n > 1
Arlo, can you confirm?

**Comment by manufrancis** [comment]
I understand Arlo's statement as Dan, and it is fine with me.
I would display @n of `<lg>`, only if there is more than one `<lg>`.
The constraint is thus not language-bound, as the others align on what was designed first for Tamil inscriptions.

**Comment by ajaniak** [comment]
Dear all, 

The main features of this issue have been implemented. Though I still have some features to stabilize.
 
Have you taken a decision regarding the display of `@n` for `<lg>`? Roman or Arabic ? about a possible identation? and the display of the the `@met`? 

Thanks

**Comment by danbalogh** [comment]
To summarise my opinion:

1. in the `@n` of `<lg>` I prefer Arabic, but since Arlo is strongly for Roman (I believe), that is OK unless PIs decide otherwise.
2. for indentation, see these comments: [mine](https://github.com/erc-dharma/project-documentation/issues/8#issuecomment-601048693) and [Arlo's](https://github.com/erc-dharma/project-documentation/issues/8#issuecomment-604476097)above. If there has been an objection that I've forgotten about, then I don't insist on any of this.
3. for display of `@met`, anything is fine by me, but I again have a definite preference for a lowercase initial as these are not proper names to my mind but technical terms like sonnet and pentameter. Here again, Arlo seems to have a strong opinion to the contrary, so if no one else puts down a vote, then let's go Arlo's way.

**Comment by manufrancis** [comment]
Concurring with Daniel's opinion:
* Arabic or Roman is fine with me. Thus Roman, followed by full stop. (so as to mark the difference between Arabic numbers for lines and Roman numbers for verses)
* Indentation is fine with me.
* lowercase or uppercase for @met is fine with me. Thus uppercase, as Roman number is followed by full stop. Non-italics.

Dear Axelle, please implement these for our proof-reading display.
Let us live with that for the moment and come back to the issue when we will discuss the display on the website.

**Comment by arlogriffiths** [comment]
Of course I agree with Manu's decision.

Maybe the following will help Daniel live more serenely with treating "meter names" as names:

Velankar in his Jayadāman speaks repeatedly of "names of meters" and prints them with iniytiual capitals. I haven't yet found whether speaking of "names" corresponds to śāstric application of the word "nāma" or its synonyms to Sanskrit meters, but I suspect it does, because from or with regard to Vedic tradition I find such sentences as 


Jaiminīyabrāhmaṇa 1.120:
tad eva br̥hatyai br̥hatītvaṁ | na tataḥ purā **br̥hatī nāma cchanda** āsa

Brahmasūtrabhāṣya 1.1.25
**chando 'bhidhānān** neti cen na tathā cetorpaṇanigadāt tathā hi darśanam  | atha yad uktaṁ pūrvasminn api vākye na brahmābhihitam iti, 'gāyatrī vā idaṁ sarvaṁ bhūtaṁ yad idaṁ kiñ ca' (ChUp. 3.12.1) iti **gāyatryākhyasya chandaso** 'bhihitatvād iti, tat parihartavyam |
kathaṁ punaś chandobhidhānānna brahmābhihitam iti śakyate vaktum, yāvatā 'tāvānasya mahimā' ity etasyām r̥ci catuṣpād brahma darśitam |

**Comment by danbalogh** [comment]
Thanks for the research, but - purely as an academic aside - I don't think the use of these words has anything to do with something being a proper name. The claim that I have a problem with "treating "meter names" as names" is based on the fallacy of equivocation. "Name" in these contexts is equivalent to "designation", as I think is implied by the use of abhidhāna and -ākhya in your second example, and as is clear in English contexts such as "[the names of SI units](https://en.wikipedia.org/wiki/International_System_of_Units)" such as "second", "metre", "gram" etc. Or as in four of the ten most common searches offered to me by Google if I start typing "names of" in the search field: names of stars, of allah, of god, **of colors**, of cities in germany, **of flowers**, of planets, of angels, **of fingers**, **of generations**. 
I have no problem treating meter names as _names_, but I still hold the opinion that they are not _proper names_ and I have not seen an argument to the contrary. Of course I don't think there exists a universally accepted definition of a proper name, and the convention of using uppercase initials varies by language/country. I do maintain that the names(!) of European metrical forms are not considered proper names in English (unless they are derived from a proper name, e.g. Aeolic) and they are not normally written with an uppercase initial.

All that aside, I can with undiminished serenity accept displaying an uppercase initial if the rest of you want it.
