### ISSUE TITLE
treatment of small parts of Ducth names in zotero and display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#80]
- we have asked in ZG App. 3.1 that small elements of Dutch names "de, den, en, ter, van, van den, van der" be placed in the forename field, which is helpful for attaining proper alphabetical arrangement of the surnames
- but consequently, in display we see only the contents of surname fields displayed, whereas in such a contexts (i.e., outside of alphabetical arrangement) it would be desirable to see the small elements reappear before the surnames

example from current display:

<img width="990" alt="Capture d’écran 2020-09-25 à 08 23 02" src="https://user-images.githubusercontent.com/835603/94233554-5b038500-ff08-11ea-969a-634c4934fade.png">

Here, it will be nicer if we could see **Van Naerssen** and **De Casparis** or even **van Naerssen** and **de Casparis**.

Do you see any way we could change our representation of such names in zotero that would allow us to obtain the desired display and still remain able to arrange the relevant bibliography entries in desired alphabetical order?

For this issue, as well as #62, I am wondering if we could introduce a special category of short titles (e.g. with a prefix "!") that would still be usable by the system as identifier while also containing sufficient information for the system to overrtide default display. 

Examples

- default display: Naerssen1941_01 to be displayed as [Naerssen 1941](url)
- special display for author with complex name: !van_Naerssen_1941_01 to be displayed as [van Naerssen 1941](url)
- special display for journal abbreviation: !NBG_15_(1877) to be displayed as [NBG 15 (1877)](url)

See #66 for my proposal to remove parentheses around date in default display if AUTHOR DATE items.

**Comment by ajaniak** [comment]
Such a rendering is possible but we will need to change the way data is enter currently in Zotero. 
For instance with Casparis, I need de Casparis in the surname to reach the following result in bibliography display (example of display done with Zotero style editor)

<img width="999" alt="Capture d’écran 2020-10-02 à 17 40 57" src="https://user-images.githubusercontent.com/33328906/94942398-883acf00-04d6-11eb-93cf-6958a271107b.png">

But it means changing the Zotero rules of the project and also Casparis will appear in the standalone at the letter D rather than C. But in the final bibliography, de Casparis will be at C thanks to the demote-non-dropping-particle="display-and-sort" possibility of the CSL. 

The solutions with default and special displays will be not as stable on a long term than using the CSL and imply manipulating strings which is always less rigorous than using formated data (and of course, I can't be sure I always be able to reach the perfect rendering since I will be depending on the string itself with less possibilities to retrieve data from the API Zotero). However, if changing the Zotero rules don't seem fitting to @manufrancis, @AnneSchmiedchen and you, I will work on the string transformation.

**Comment by arlogriffiths** [comment]
Thanks a lot. I have not been able to understand all your technical explanations, and I am not sure I understand what you mean with "the standalone". Maybe it will be easier to discuss this issue live one day.

if the choice comes down to whether it seems acceptable, or not,
- to change the zotero guide and to write that "de Casparis" in surname rather than only "Casparis" in surname and "de" at the end of the forename"
- to work with such a name being ordered under D in the version of the zotero library on our own computers

then I see no objection.

I wonder how zotero will know that it should apply the `demote-non-dropping-particle="display-and-sort"` possibility of the CSL to "de"  in "de Casparis" but not to "De" in "De Simini".

**Comment by ajaniak** [comment]
The standalone is the Zotero on your computer. 

<img width="1000" alt="Capture d’écran 2020-10-05 à 14 14 37" src="https://user-images.githubusercontent.com/33328906/95078370-52cff480-0715-11eb-94f8-372091bbfa76.png">

**Comment by arlogriffiths** [comment]
Thanks for reminding me what "standalone" means. For the rest, could your please respond to the following:

1. Have I correctly understood that the choice comes down to whether it seems acceptable, or not, (a) to change the rule in the ZG so that we will henceforward require typing "de Casparis" in surname rather than only "Casparis" in surname and "de" at the end of the forename, and (b) to work with such a name being ordered under D in the version of the zotero library on our own computers?

2. Have I correctly understood that applying the demote-non-dropping-particle="display-and-sort" possibility of the CSL would result in a SURNAME "de Casparis" getting arranged under C in alphabetical order?

3. If our Group Libary contains items with SURNAME "de Casparis" and items with SURNAME "De Simini", how will the system know that it should apply the demote-non-dropping-particle="display-and-sort" possibility of the CSL to "de" in "de Casparis" but not to "De" in "De Simini"?

**Comment by ajaniak** [comment]
1. Yes, for both. 
2. Yes again. Of course, we choose to keep this value of `display-and-sort`. Several possibilities are offered. 
3. Technically, all is handled by a patch inside the citeproc-js - the CSL processor used by zotero. So a mapping is done what to do with the name depending the language identified in the filed title, language and special forms of names. Of course, nothing is never up to 100%. But all the test I have ran were satisfiying (at least in my opinion). Do you want me to make a test on a Zotero collection level to see a general output result ? (By the way the subject is opened since 2015, and seems to reach a stability for most the user.) You can read the CSL documentation, if you are interested, which is the citing standard https://docs.citationstyles.org/en/stable/specification.html#name-part-order

**Comment by arlogriffiths** [comment]
Thanks a lot Axelle. I will try to take a look at that link soon.

It seems we are moving toward a conclusion, namely that the small parts of names should be entered in the SURNAME field and that we should leave it to the machine (CSL in this case) to organize the data for us.

Before we make that decision, and make the necessary edits to ZG and in our Group Library, it would indeed be nice if you could carry out such a test at the Zotero collection level and show us the result.

I am adding Annette and Dan to this discussion, as it is starting to concern them too.

**Comment by ajaniak** [comment]
Do you have a preference on the Zotero collection to test or you don't care?

**Comment by arlogriffiths** [comment]
Shall we try E-IDENK and E-Deccan-EIAD — if testing with two isn't much extra work?

**Comment by ajaniak** [comment]
OK. I will let you now when it is done. Just so you known I will not work on the Dharma Zotero itself to avoid conflict and dirty data.

**Comment by arlogriffiths** [comment]
@ajaniak: sorry for the delay. I will answer separately to your email with test material. in my view, the approach discussed is ready for adoption, and you can make proposals for the necessary changes in the gdoc for the ZG.

Are you able to make the necessary changes in our Zotero entries by automated means?

**Comment by ajaniak** [comment]
I have seen you mail. 

Yes I should be able to move it with a python script either with the names concerned by the changes or with a list of particules you expect to be moved, it depends on your level of satisfaction regarding the output tests.

**Comment by arlogriffiths** [comment]
Encourage by @manufrancis , I have once again read through this entire issue.

I conclude:

1. Let us proceed to a change in the ZG App. 3.1, at least for Dutch and German names at least, namely
- record cases involving "de, den, en, ter, van, van den, van der" according to the model [surname] van der Molen [forename] Willem
- record cases involving "an, auf, von, von der, zu, van" according to the model [surname] von Hinüber, [forename] Oskar
- record cases involving "Am, Aus’m, Im, Vom, Zum, Zur" or elements like "Le, La, Du" according to the model Ex: [surname] Aus’m Weerth, [forename] Ernst

2. I am unable to judge from the test results whether we have a sufficiently satisfactory result for French names, and the test material did not include any Italian, Portuguese, Spanish or other exotic names, but nevertheless it is perhaps most simple to implement changes analogous to the Dutch/German cases also for those languages.

3. We need to explain at relevant places in the ZG 
- how our system will work including, perhaps in footnote, some of the technical explanations regarding use of the demote-non-dropping-particle="display-and-sort" possibility of the CSL
- that the chosen approach will allow us to display "van Naerssen" etc. inside our epigraphic and other editions while still allowing us to keep such names in their proper alphabetic order in bibliography
- and has as downsides (a) that the names will appear out of alphabetical order in zotero standalone and (b) that the CSL system is not perfect so that some names may be displayed in unconventional manners

@ajaniak : 
1. can you suggest the necessary rewrites in ZG?
2. can you apply the python script to modify all existing zotero entries?

I hope that all is clear and that I haven't forgotten anything.

**Comment by ajaniak** [comment]
I have made the changes inside Zotero last week. Please be careful with particles like le, la, du et de used in several languages. The automation was harder than for those cases. Note also that noises in entries might have prevented the changes to be made by the script. I have checked of the results, but some cases might have gone trough and will need to be corrected manually. 

I have also changes the Appendix 3.1 containing easy examples. However, take a look at the App 3.4 where more complex one are provided, I didn't change some of them since I wasn't sure of the expected display. Can you check all this cases and make sure they are right and add the missing one, please?

I added a first version of the non-dropping-particle system inside the 4.3 part of the guide. Please have a look when you have some time. It wasn't so easy to explain, I hope it will be clear enough. 
I added a new subdivision. I though it would made the content clearer, update it or delete it, if you find it confusing.

**Comment by manufrancis** [comment]
Feedback on implementation requested.
