### ISSUE TITLE
bibliography display 5: short titles for journal volumes

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#81]
Some modifications are necessary for display of bibliographic data in the case of short titles for journals. 

Code example:

`<bibl>Brandes in 
              	<ptr target="bib:NBG34_1896"/>
              	<citedRange unit="page">53</citedRange>
              	<citedRange unit="item">3</citedRange>
  </bibl>`

Current display:

<img width="921" alt="Capture d’écran 2020-09-25 à 15 11 25" src="https://user-images.githubusercontent.com/835603/94271076-66bf6d80-ff41-11ea-813d-e05efd560609.png">

Desired display would be something like this:

- Brandes in [NBG 34 (1896)](url), 53 no. 3

See also #62 and my tentative proposal in #80.

**Comment by ajaniak** [comment]
I have implemented it and tested for most of the journal shortTitle. To encode it, `<bibl rend="journal">` . Please note, it will work only for the section if the bibliography.

<img width="398" alt="Capture d’écran 2020-10-06 à 12 22 00" src="https://user-images.githubusercontent.com/33328906/95189766-93d80f80-07ce-11eb-87ee-879731f5a5db.png">

**Comment by arlogriffiths** [comment]
looks nice to me.

so @danbalogh : I think we need to add this `<bibl rend="journal">` in the EGD.

**Comment by arlogriffiths** [comment]
@ajaniak : can you display the journal abbreviations in italics?

once that is done, and @danbalogh has confiomed that `<bibl rend="journal">` has been added to EGD, I can close this issue.

**Comment by ajaniak** [comment]
Done

**Comment by arlogriffiths** [comment]
Thanks. But something is going wrong.

1. code:

`<listBibl type="primary">
		<bibl n="H" rend="journal">
			<ptr target="bib:Holle1880_02"/>
			<citedRange unit="page">1-2</citedRange>
			<citedRange unit="part">I A</citedRange>
		</bibl>
		<bibl n="B" rend="journal"><ptr target="bib:Brandes1889_01"/></bibl>	
		<bibl n="S"><ptr target="bib:Sarkar1971-1972_01"/><citedRange unit="volume">2</citedRange><citedRange unit="page">99-101</citedRange><citedRange unit="item">73</citedRange></bibl>	
		<bibl n="TSN"><ptr target="bib:TitiSurtiNastiti2016_01"/><citedRange unit="page">412-413</citedRange></bibl>
</listBibl>`

2. display:

<img width="1013" alt="Capture d’écran 2020-10-06 à 14 45 07" src="https://user-images.githubusercontent.com/835603/95203095-8f1d5680-07e2-11eb-9353-ad84728dc38c.png">

**Comment by ajaniak** [comment]
Well the Holle entry is handled in Zotero as a singular one. The @rend="journal" is made to deal with the one you have handled as journal at collection levels. 
I will see what I can do for your Holle and the rest af the data type journa. But since it will required changing the interaction with the API, so not sure when you will have it.

**Comment by arlogriffiths** [comment]
I am sorry, but I haven't understood your reponse. 

You mention only Holle, but what about the fact that `<bibl n="B" rend="journal"><ptr target="bib:Brandes1889_01"/></bibl>` disappears, in the above example, except for the @n=B?

And what does "the Holle entry is handled in Zotero as a singular one" mean? I don't see what is exceptional about Holle1880_02, except that it has no pagination.

**Comment by danbalogh** [comment]
I'll be happy to update the EGD on this, but to be honest, I don't really grasp the details. @arlogriffiths , could you add stubs or comments to the EGD where you want this, containing a draft of how you want the murky details handled. Here's what I do understand:
- bibliographic citations will be displayed by default with a full title; if you want a journal abbreviation to appear in place of a full title, then use `<bibl rend="journal">`

What I do **not** understand is:
1. in what situations is this desirable and when is it not? Arlo's comment (the second above) implies that it is desirable in the structured bibliography. Axelle's remark "it will work only for the section if the bibliography" seems to say that it will not even work anywhere outside the bibliography. If I understand that correctly, then why does this have to be so? Do we want full titles appearing in similar citations within a commentary?
- If that is what you want, OK by me, I'll live with it.
- But if it is not, then are there _any_ situations in which we want the full title to be displayed? If yes, what are they? If not, could not the display of abbreviation instead of full title be somehow handled on a global level instead of having to add `@rend="journal"` to each and every citation of such items?
2. the sample code in Arlo's opening comment has text within a bibl element, `<bibl>Brandes in <ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>`  - This is new to me. Is this even permitted/sanctioned by TEI? If yes, do we really want to use it? If yes, the EGD should tell encoders when to do so, otherwise only people directly instructed by Arlo to do it will do it.
- I gather from the above that Arlo may have used this in the structured bibliography, where there was no TEI-sanctioned way to add the text "Brandes in" _outside_ the bibl element. If I get this correctly, then couldn't this be avoided by having _only_ `<bibl><ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>`  in the structured bibliography? The fact that the item cited is by Brandes would, I believe, be communicated anyway in the epigraphic lemma, where you would use `Brandes in <bibl><ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>` , i.e. put the non-structured text outside the bibl element.
3. how does the practice recommended for `@rend="journal"` tie in with the practice recommended for `@rend="siglum"`? What, anyway, _is_ the practice recommended  for `@rend="siglum"`, another thing I first heard of today, in issue #82 .

**Comment by ajaniak** [comment]
- part answering @arlogriffiths about the difference of data structuration: 
Since not all the data are structured on the same model in Zotero, it means handling each with a different parsing. 
So in the case for NBG and equivalent – journal entered as book – I can't format them using the CSL neither the API, so it has to be done in the XSLT itself using some intel from the shortTitle. 
The data like Holle1880_02 are entered with a type JournalArticle provide another set of information and structured differently, but from which I can retrieve author name, journal abbreviation and date. In this case, I could handle the display through the CSL processor, but it is not recommended since it will impact all the bibliographical data of the project and not only the html display. (Unlike we decided to sustain several CSL of the same base style for the project... which unlike it is really necessary I would rather prefer to avoid since it leads to confusion). So Holle1880_02 is currently handled both through the parsing of the API and XSLT transformation to provide the same result. 
This distinction of dealing with the data means that I need an anchor in the XML to identify the data you consider like journal. The collection anchor from the Zotero API isn't stable enough to compensate the item type book provided. 


Some encoders have been using the reference in commentary, lemma or even in the apparatus is full length and not just with `@rend='omitname'`, one of the reason for provided the `@rend="siglum"` was to be able to shorten the reference. The value of the attribute will probably evolved since at the beginning we reused the siglum content. @manufrancis will provide more details of his needs. 

`<bibl>Brandes in <ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>` doing so isn't prohibited by TEI. It is not good practice though, you don't half structured - half prosed content of an element. If it can work on some element, it is prone to error especially in cases where it is not just a question of copying the data but work the data to render it as you expect it. I added an <apply-template> as high as possible in the transformation processing to copy the content but I can' t promise it won't mess up other display at some point. I would be more confortable with 
`<bibl><author>Brandes</author> <ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>`. But I understood from previous discussion that you wanted to reduce the structuration of the `<bibl>`element for a prose content.

**Comment by arlogriffiths** [comment]
Thanks Dan and Axelle for your most recent messages. Clearly, we are runnning into confusions because we each have different expectations, we don't always explain with sufficient clarity what we expect, and Axelle is getting (or in any case sometimes thinks she is getting) conflicting instructions from her various interlocutors. **I apologize for being one of the most guilty parties!**

I am not sure what is the best road ahead now that we are in this chaotic situatiin. Take a break and return to these matters later, or try to push towards closure of this issue?

Let me say just the following now:

1. I think it is helpful if we can specify specify the identity of a scholar inside the structure bibliography, in cases where (a) the zotero short title we are using does not itself contain data in its "author" field, and where (b) there is no other reason to mention the reference in the `<p>` of epigraphic lemma — the Brandes example corresponds to both criteria. 

2. I have no trouble with Axelle's proposal to encode `<bibl><author>Brandes</author> <ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>`.

3. I do not see why we would ever want to show full journal titles in our display, because they will always distract from other data that we cannot abbreviate while we are already defining abbreviated journal titles in zotero (see also the appendix in the ZG), and it will presumably be easy to make the full titles visible by mouse-over over any abbreviation, and/or by offering an old-fashioned list of abbreviations.

4. This whole discussion started because I wasn't getting the display I was hoping to get in structured bibliography, where citing a full journal title seems to me to distract too much from other bibliographic data. Depending on whether or not I use @rend="journal" in the relevant `<bibl>`s, I can now produce the following two displays:

- with @rend="journal" 

<img width="968" alt="Capture d’écran 2020-10-07 à 12 53 30" src="https://user-images.githubusercontent.com/835603/95322008-24305600-089c-11eb-9ca7-3485efa3224a.png">

- without @rend="journal" 

<img width="998" alt="Capture d’écran 2020-10-07 à 12 53 37" src="https://user-images.githubusercontent.com/835603/95322025-2a263700-089c-11eb-8198-a33e53e10a9b.png">

My objections to these two presentations are that the first shows too little bibliographic information while the second comes with needless clutter and we have an easy way to declutter (see point 3 above).

5. The display I was actually hoping to get would look like this:

<img width="762" alt="Capture d’écran 2020-10-07 à 12 54 50" src="https://user-images.githubusercontent.com/835603/95322195-69ed1e80-089c-11eb-950c-f54386393f65.png">

@danbalogh @AnneSchmiedchen @manufrancis : do you like this last display suggestion?
@ajaniak : do you see any problems with it? I believe implementing it may remove the need to ever use @rend="journal" (but there may be other context where that attribute is needed that I am unaware of).

**Comment by danbalogh** [comment]
**I do like the last display suggestion** and would prefer to avoid introducing the complication of `@rend="journal"` if possible.

My private preference is still for full journal titles in the structured bibliography and, reversing Arlo's number 3 above, I do not see why anyone would ever want to show an abbreviation instead of a full title when there is no need to economise on paper or ink and the presence of a full title does not disrupt the surrounding text. But this is not important enough to argue over, so if everyone else can agree on showing abbreviations there, then no problem on my part.

**I am also OK with `<bibl><author>Brandes</author> <ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>` in cases where it is essential to add such information in the structured bibliography,** and if this gets endorsed, I would like Arlo to add a stub to the EGD saying when encoders should resort to this. (Does Axelle still need to work out a way for this to display with an added "in", or is it acceptable without?)

**Comment by ajaniak** [comment]
If you agree on the display 5, I might have a technical solution to handle it. But please be aware it will required an intervention at the CSL level, so it means the journal name will always be displayed abbreviated. I won't be able in special case to revert back. 
Please be also aware that this solution fits only for the case like Holle = > journal data with a journal type officially declared as such in Zotero. The cases of journal entries declared as book, if you don't want to use the `@rend="journal"`as shortcut, we will need to revert to a more complex code and we will need to find a way to discriminate the data to avoid noise in the display. I will figure something out with @manufrancis to make sure we take all  bibliographical data into account. 

`<bibl><author>Brandes</author> <ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>`. I do not need the `in` inside the citedRange. I can display it though when an element `<author>` is used. I will need to know before adding it into the code where you plan to need it: in all the bibliographical data or only in the `<listBibl>` element.

**Comment by manufrancis** [comment]
I concur with Daniel in prefering full journal titles in the structured bibliography. Like Daniel "I do not see why anyone would ever want to show an abbreviation instead of a full title when there is no need to economise on paper or ink and the presence of a full title does not disrupt the surrounding text."
The abreviation could be displayed and handled with siglum as per my proposal in issue #90.

**Comment by arlogriffiths** [comment]
I do not insist any longer on being able to have abbreviated titles in the structured bibliography.

In apparatus, Manu's suggestion in issue #90 will indeed make it possible, when necessary, to use journal abbreviations. This also answers an unspoken question I had, namely for what good we are defining abbreviated journal titles at all in zotero and in the ZG, if we never plan to use them. **@ajaniak: Are then any other contexts where we'll be usingh them?**

Could @danbalogh perhaps summarize where we have ended up with this discussion?

**Comment by danbalogh** [comment]
I may be missing out on some things, but it seems to me that the gist is the following:

1. We forget about `@rend="journal"` and keep the display of bibliographic items as they are now, as Arlo has gracefully conceded to full journal titles being shown.
2. In certain specific situations (which are still not entirely clear to me, but seem to be when a/ the reference is to an authorless publication, **and** b/ you do know who the author is and you want to show this in your bibliography, **and** c/ you cannot do this in the epigraphic lemma because the item belongs to the secondary bibliography), Arlo wants to permit the syntax `<bibl><author>Brandes</author> <ptr target="bib:NBG34_1896"/> <citedRange unit="page">53</citedRange> <citedRange unit="item">3</citedRange> </bibl>`, i.e. the inclusion of an `<author>` element in the reference, as the first item before `<ptr>`.

If my understanding of 2 above is correct, and it really is desirable to create special rules for such a complex special case, then Axelle and Arlo should work out how such items would be displayed (e.g. using "Brandes in" etc.), and Arlo will need to add a stub to the EGD at the point where he wants to discuss this (perhaps the end of §10.4.5 right before the examples? I may then need to split up 10.4.5 into several subsections because it is already a bit unwieldy, and if `@rend="siglum"` becomes standard, it will get even more complex), and in this stub he should list the exact conditions in which this kind of encoding is recommended (or mandatory). I will then finish up the stub, discuss any outstanding details with Arlo, and possibly do some restructuring in the EGD, pending the resolution on `@rend="siglum"`.

**Comment by manufrancis** [comment]
I am fine with Dan's approach on this.

**Comment by manufrancis** [comment]
Following the DHARMA brainstorming (2020/12/17), I have re-considered the issue.
Pleasing, I hope, our Dutch PI, I do not care if Journal titles are displayed as abbreviations.
So please, Axelle, do implement, if necessary, as required, and implement a tooltip showing full title of journal at mouse over.

**Comment by ajaniak** [comment]
Dear all, 

You seem to have settle in favor of a publication title displayed with an abbreviated form and its full expression only in tooltip. 

For now, I have created a new CSL to add the abbreviation feature inside the Chicago author-date model. It allows me to export two versions for a bibliographic citation. Let’s take this journal article 
->  `Venkayya, V. 1896–1897. “Jain Rock-Inscriptions at Panchapandavamalai.” EI 4.14: 136–40.` Is displayed in the html a the main text while `Venkayya, V. 1896–1897. “Jain Rock-Inscriptions at Panchapandavamalai.” Epigraphia Indica 4.14: 136–40.` is provided as a tooltip. 

I can’t structure more precisely the data with the current system. Indeed, the citation is constructed through Zotero API so I don’t have enough anchor inside the result to apply the tooltip only on the journal title. 

Another downside of this system is that only items recorded with the type Article Journal in Zotero can be exported as such. All the items you have filled in as book requires to set another system. Initially, that’s was the purposes for the attribute `@rend="journal"`. So instead of using the attributes to discriminate, I set the new system on search for the content of `@target` starting with the string "bib:" and followed by 2 upper-case letters. 

`<bibl><ptr target="bib:NBG15_1877"/><citedRange unit="page">136-137</citedRange></bibl>` will have `NBG 15 (1877)` as a main text and `Notulen van de Algemeene en Bestuurs-vergaderingen van het Bataviaasch Genootschap van Kunsten en Wetenschappen: Deel XV — 1877. 1878. Batavia: Bruining.` as the content of its tooltip. 

If you wishes to provide an author
`<bibl><author>Brandes</author><ptr target="bib:NBG24_1886"/></bibl>` to obtain `Brandes in NBG 24 (1886)` as main text, the tooltip will contain `Notulen van de Algemeene en Bestuurs-vergaderingen van het Bataviaasch Genootschap van Kunsten en Wetenschappen: Deel XXIV — 1886. 1887. Batavia: Albrecht &amp; Co.`

Regarding the epigraphical lemma and notes for journal entries as book. See #62
It will be given as `BEFEO 36 (1936)` with the link toward the Zotero entry online. 

Please check the outputs and let me know if you are satisfied with it. 

Best,

**Comment by manufrancis** [comment]
Dear Axelle,
Thanks! I will test on my Pallava files.
Let us discuss this together this Thursday at the office.
