### ISSUE TITLE
Display <citedRange> 

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#82]
Dear all,
Axelle has started to implement the display of `<citedRange>` for the bibliographical references.
Please, have a look at this display when transforming your XMLs and note in this thread your remarks and suggestions.

**Comment by danbalogh** [comment]
Not sure if this is directly related to citedRange, but I just noticed the following the other day. I've rechecked and it still happens. I like the new colours by the way. So, I have the following code, within an `<app>` element. This is from the file CalE40-Sripundi-Tala2.xml in vengicalukya-epigraphy.

`<note>Lakshmana Rao takes Guṇakkenallāta as the name used here, and if this form occurs elsewhere that I am not aware of, then he may be correct. K. A. Nilakanta Sastri and N. Venkataramanayya (in <bibl><ref target="bib:Yazdani1960_01"/><citedRange>476</citedRange></bibl>) mention the form Guṇake-nallāṭa, said to mean “the lover of excellence or virtue,” without citing a source. The spelling is definitely with <foreign>t</foreign> here. In my opinion it is more likely that the text is erroneous, for <foreign>°lleti</foreign>, <foreign>°llākhya-</foreign> or <foreign>°llāṁka-</foreign>.</note>`

The transformed HTML has

`K. A. Nilakanta Sastri and N. Venkataramanayya (in <a href="https://github.com/erc-dharma/epigraphy/blob/master/xml-provisional/bib:Yazdani1960_01">476) mention the form Guṇake-nallāṭa,`

i.e. only the page number is shown, "(in 476) ", instead of the reference, but more conspicuously, there is no `</a>` tag in the HTML, so the text from here to the end of the page is displayed as a hyperlink.

In the same file, other biblio items also seem to be displayed as the contents of citedRange alone, without anything else. Thus, in the epigraphic lemma,
`Reported in <bibl><ptr target="bib:ARIE1908-1909"/><citedRange unit="page">10</citedRange><citedRange unit="appendix">A/1908-1909</citedRange><citedRange unit="item">5</citedRange></bibl> with discussion in <bibl><ptr target="bib:ARIE1908-1909"/><citedRange>104, 108-109</citedRange></bibl>.`
is displayed as follows:
Reported in 10A/1908-19095 with discussion in 104, 108-109.

**Comment by arlogriffiths** [comment]
I haven't seen the same happening yet on my side.

Here is some feedback of my own, based on the following example:

<img width="1024" alt="Capture d’écran 2020-10-03 à 16 10 20" src="https://user-images.githubusercontent.com/835603/94993706-2d1ae200-0593-11eb-8e3d-b6ee3b4ef9b2.png">

1. I would recommend that full titles of periodicals be replaced by journal abbreviations as recorded in the "Journal Abbr" field of the Zotero entries in question. Thus, we could here get _VBG_ for Holle 1880 and _TBG_ for Brandes 1889. It might be nice to allow viewers to see the corresponding ful title with mouse over.
2. I am not yet sure what is the best solution for displaying items that contain a `<citedRange>` when they occur, as here, in a `<listBibl>`, but I tentatively suggest that cases like Holle 1880, Sarkar 1971–1972 and Titii Surti Nastiti 2016 be displayed as follows:
 -- Holle, K. F. 1880. “Kawi-oorkonden, no. 2: Transcriptie van koperen platen.” _VBG_ 39. Here, pages 1–2, part I A.
 -- Sarkar, Himansu Bhusan. 1971–1972. _Corpus of the Inscriptions of Java (Corpus Inscriptionum Javanicarum), up to 928 A. D._ Calcutta: K.L. Mukhopadhyay. Here, volume 2, pages 99–101, no. 73.
-- Titi Surti Nastiti. 2016. _Perempuan Jawa: kedudukan dan peranannya dalam masyarakat abad VIII-XV_. Bandung: Pustaka Jaya. Here, pages 412–413. 
 -- NB (a) use of "Here, ..." means that all words corresponding to @unit ("pages", "part", etc.) can always be shown with lower-case initial; (b) French-style "n°" should become "no."; (c) we need an en-dash in page ranges (1–2, 99–101  and 412–413 in the above examples)
 -- possibly, the indications of `<citedRange>` could also be displayed in bold, to set them off from the basic bibliographic entry that they follow

**Comment by danbalogh** [comment]
I am not familiar with the practice of using "Here" and it strikes me as strange.

**Comment by ajaniak** [comment]
@danbalogh there is indeed a bug in the `<note>` regarding the implementation of the <bibl>. I am going to handle it. But regarding the rest I have the expected display as well.

**Comment by arlogriffiths** [comment]
> I am not familiar with the practice of using "Here" and it strikes me as strange. I would prefer to avoid it and I believe it should not be technically difficult to first generate a string for any and all citedRange items, e.g. "volume 2, pages 99-101", and then to transform only the first letter in that string to uppercase. If this is correct (Axelle?) then there is no technical need for us to use "Here," just because we can then use lowercase throughout the citedRange string.
> As for "Number", I would actually prefer the proper Unicode character №.

I am sure I have seen scholars use "where" or even "_ubi_" in similar contexts, and my "Here, ..." was an attempt to emulate this. I think some transition is needed between the principal bibliographic entry and the contents of `<citedRange>`, and will be happy to accept better (more commonly recognized) solutions, but I don't agree with having nothing at all.

I have never use № but I am not against using it.

**Comment by danbalogh** [comment]
@arlogriffiths - whatever you finally settle on regarding these points will be acceptable to me.


@ajaniak I'm using the transformation at project-documentation/stylesheets/inscriptions/start-edition.xsl. Is there a later version that I should be using? I've just checked and I still get this strange output. If the above is the correct XSL to use, then could you check one of my files in vengicalukya-epigraphy to see if perhaps I'm doing something wrong? 

Thus, e.g. in CalE39-Arumbaka-Badapa.xml, from the code
```
<div type="bibliography">
  <p>Reported in <bibl><ptr target="bib:ARIE1920-1921"/><citedRange unit="page">17</citedRange><citedRange unit="appendix">A/1920-1921</citedRange><citedRange unit="item">16</citedRange></bibl> with discussion in <bibl><ptr target="bib:ARIE1920-1921"/><citedRange>90-91</citedRange></bibl>. Edited from inked impressions (made by G. Venkoba Rao) and from the original plates by K. V. Lakshmana Rao (<bibl rend="omitname"><ptr target="bib:LakshmanaRao1927-1928_02"/><citedRange unit="page">137-148</citedRange><citedRange unit="item">1</citedRange></bibl>), with translation and facsimile (and photo of the seal). The present edition by Dániel Balogh is based on a collation of Lakshmana Rao's edition with his facsimiles.<note>The facsimiles, as scanned, are illegible in many places. I rely primarily on Lakshmana Rao's readings, and generally mark up unclear only where he did so, assuming that the originals were much better legible. However, he seems not to distinguish unclear readings from restorations in his editions, so it is quite possible that all or most of the "unclear" readings are in fact restorations, and many of the "clear" readings are unclear even in the original. Consulting the printed facsimile may also help.</note></p>
  <listBibl type="primary">
    <bibl n="KVL"><ptr target="bib:LakshmanaRao1927-1928_02"/><citedRange unit="page">137-148</citedRange><citedRange unit="item">1</citedRange></bibl>
<!-- one <bibl/> per item of primary bibliography -->
  </listBibl>
  <listBibl type="secondary">
    <bibl><ptr target="bib:ARIE1920-1921"/><citedRange unit="page">17</citedRange><citedRange unit="appendix">A/1920-1921</citedRange><citedRange unit="item">16</citedRange></bibl>
    <bibl><ptr target="bib:ARIE1920-1921"/><citedRange>90-91</citedRange></bibl>
  </listBibl>
</div>
```

I get the following HTML,
`<h2>Bibliography</h2>  <p>Reported in 17A/1920-192116 with discussion in 90-91. Edited from inked impressions (made by G. Venkoba Rao) and from the original plates by K. V. Lakshmana Rao (137-1481), with translation and facsimile (and photo of the seal). The present edition by Dániel Balogh is based on a collation of Lakshmana Rao's edition with his facsimiles.<i>The facsimiles, as scanned, are illegible in many places. I rely primarily on Lakshmana Rao's readings, and generally mark up unclear only where he did so, assuming that the originals were much better legible. However, he seems not to distinguish unclear readings from restorations in his editions, so it is quite possible that all or most of the "unclear" readings are in fact restorations, and many of the "clear" readings are unclear even in the original. Consulting the printed facsimile may also help.</i></p>  <h3>Primary</h3> 137-1481 <h3>Secondary</h3> 17A/1920-192116 90-91`

**Comment by ajaniak** [comment]
Yes, there is 2 two launching files since the bibliographic data when not well formatted refused to rend a html and because of the parameters I can't handle it a more friendly way for now (still trying to figure something that still allows all the content to still perform). If you want the bibliography, you can use the start-edition-with-bibl.xsl. 
Sorry I thought you knew.

**Comment by danbalogh** [comment]
Thanks, I didn't know, or I may have forgotten. The above problems do not appear with that xsl, but there are some others.
The following code
```
<div type="bibliography">
  <p>Reported in <bibl><ptr target="bib:ARIE1920-1921"/><citedRange unit="page">17</citedRange><citedRange unit="appendix">A/1920-1921</citedRange><citedRange unit="item">16</citedRange></bibl> with discussion in <bibl><ptr target="bib:ARIE1920-1921"/><citedRange>90-91</citedRange></bibl>. Edited from inked impressions (made by G. Venkoba Rao) and from the original plates by K. V. Lakshmana Rao (<bibl rend="omitname"><ptr target="bib:LakshmanaRao1927-1928_02"/><citedRange unit="page">137-148</citedRange><citedRange unit="item">1</citedRange></bibl>), with translation and facsimile (and photo of the seal). The present edition by Dániel Balogh is based on a collation of Lakshmana Rao's edition with his facsimiles.<note>The facsimiles, as scanned, are illegible in many places. I rely primarily on Lakshmana Rao's readings, and generally mark up unclear only where he did so, assuming that the originals were much better legible. However, he seems not to distinguish unclear readings from restorations in his editions, so it is quite possible that all or most of the "unclear" readings are in fact restorations, and many of the "clear" readings are unclear even in the original. Consulting the printed facsimile may also help.</note></p>
  <listBibl type="primary">
    <bibl n="KVL"><ptr target="bib:LakshmanaRao1927-1928_02"/><citedRange unit="page">137-148</citedRange><citedRange unit="item">1</citedRange></bibl>
```
gives this display:
![Clip](https://user-images.githubusercontent.com/31253927/95180510-5cfbfc80-07c2-11eb-8185-ae0d0df396d0.jpg)

issues:
- what should be an `<i>` tag is instead `&lt;i&gt;` in the HTML
- ARIE reference displayed with full title in the text, where it should, I think, just be ARIE 1920-21 etc.
- year (1927) bracketed - as per the issue brought up by Arlo, no need for separate attention here
- funny placement around the siglum of the primary biblio item

**Comment by ajaniak** [comment]
Ah sorry I deleted too much code yesterday while removing the parentheses around date and I only tested it on Manu's. 

- the <i> are inherit from Zotero. Why would you expect a html tag to be displayed `&lt;i&gt;`? The italic isn't applied because of the parent element `<a>`
- You need to declare the `@rend` at the level of the <bibl> element when you don't want the by default displayed from Zotero. In this case, `@rend='siglum'` if you want to fetched the siglum or `@rend='journal'` if you want the journal abbreviation display. 
-  The parentheses are still displayed because it is a case with `@rend='omitname'` and as far as I understood the issue @manufrancis has asked to keep them here and no consensus was reached yet. 
- caused by the fact I am working currently on the code and it can cause the block to be disturbed the block. It is already resolve.

**Comment by danbalogh** [comment]
> - the `<i>` are inherit from Zotero. Why would you expect a html tag to be displayed `&lt;i&gt;`? The italic isn't applied because of the parent element `<a>`
I don't expect to display as `&lt;i&gt;`. Quite the opposite. It is rendered that way by the current xsl, and so it is displayed as `<i>` instead of being rendered as italics.
> - You need to declare the `@rend` at the level of the <bibl> element when you don't want the by default displayed from Zotero. In this case, `@rend='siglum'` if you want to fetched the siglum or `@rend='journal'` if you want the journal abbreviation display. 
Fine by me if this is how Manu wants this. I thought ARIE items would be displayed as ARIE, but if not, OK. As for `@rend='siglum'`, this is the first I hear about it. If this is something settled (though `@rend` should not really be used here, for the same reason you discourage it on `<citedRange>`), then someone please add a comment to the EGD about when and how to use this.

> -  The parentheses are still displayed because it is a case with `@rend='omitname'` and as far as I understood the issue @manufrancis has asked to keep them here and no consensus was reached yet. 
I thought we had consensus: no parentheses anywhere regardless of rend. But do wait for Manu's agreement before changing this.

> - caused by the fact I am working currently on the code and it can cause the block to be disturbed the block. It is already resolve. 
OK, thanks.

**Comment by danbalogh** [comment]
> - the `<i>` are inherit from Zotero. Why would you expect a html tag to be displayed `&lt;i&gt;`? The italic isn't applied because of the parent element `<a>`
I don't expect to display as `&lt;i&gt;`. Quite the opposite. It is rendered that way by the current xsl, and so it is displayed as `<i>` instead of being rendered as italics.
> - You need to declare the `@rend` at the level of the <bibl> element when you don't want the by default displayed from Zotero. In this case, `@rend='siglum'` if you want to fetched the siglum or `@rend='journal'` if you want the journal abbreviation display. 
Fine by me if this is how Manu wants this. I thought ARIE items would be displayed as ARIE, but if not, OK. As for `@rend='siglum'`, this is the first I hear about it. If this is something settled (though `@rend` should not really be used here, for the same reason you discourage it on `<citedRange>`), then someone please add a comment to the EGD about when and how to use this.

> -  The parentheses are still displayed because it is a case with `@rend='omitname'` and as far as I understood the issue @manufrancis has asked to keep them here and no consensus was reached yet. 
I thought we had consensus: no parentheses anywhere regardless of rend. But do wait for Manu's agreement before changing this.

> - caused by the fact I am working currently on the code and it can cause the block to be disturbed the block. It is already resolve. 
OK, thanks.

**Comment by arlogriffiths** [comment]
> > I am not familiar with the practice of using "Here" and it strikes me as strange. I would prefer to avoid it and I believe it should not be technically difficult to first generate a string for any and all citedRange items, e.g. "volume 2, pages 99-101", and then to transform only the first letter in that string to uppercase. If this is correct (Axelle?) then there is no technical need for us to use "Here," just because we can then use lowercase throughout the citedRange string.
> > As for "Number", I would actually prefer the proper Unicode character №.
> 
> I am sure I have seen scholars use "where" or even "_ubi_" in similar contexts, and my "Here, ..." was an attempt to emulate this. I think some transition is needed between the principal bibliographic entry and the contents of `<citedRange>`, and will be happy to accept better (more commonly recognized) solutions, but I don't agree with having nothing at all.
> 
> I have never use № but I am not against using it.

@ajaniak : I have seen your example in #81. It looks close to acceptable for me. Could you try to apply bold to the `<citedRange>` and show us in response to the comment what the result looks like?

**Comment by ajaniak** [comment]
@danbalogh we have kept the `@rend` on `<bibl>`because the EGD has chosen it for omitname; so for consistency sake, we have kept the @rend. 

@arlogriffiths is this what you wanted by applying bold on citedRange? 
<img width="1030" alt="Capture d’écran 2020-10-06 à 14 00 34" src="https://user-images.githubusercontent.com/33328906/95198993-685c2180-07dc-11eb-8938-a104a4297a66.png">

**Comment by arlogriffiths** [comment]
@ajaniak : yes, this is exactly what I had in mind, thanks! to me it looks good, with only one small improvement to be made:

- the hyphen in citedRange must be displayed as en-dash

@danbalogh @manufrancis @AnneSchmiedchen : please confirm that you are alright, _for the time being_, to see the contents of citedRange displayed in this manner, i.e., only in our _structured bibliographies_.

**Comment by ajaniak** [comment]
@arlogriffiths for the en-dash: do I apply it in all the bibliographic data or only in the bibliography part?

**Comment by arlogriffiths** [comment]
all bibliographic data


Le 6 oct. 2020 à 14:16, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



@arlogriffiths<https://github.com/arlogriffiths> for the en-dash: do I apply it in all the bibliographic data or only in the bibliography part?

**Comment by ajaniak** [comment]
Done (I have pushed so you have all the little stuffs I have just done and will delete the bold if necessary later)

**Comment by arlogriffiths** [comment]
Thanks. Here's another small point to be improved.

If @unit="page" or if no @unit is present (meaning by default that we're dealing with pages as unit), a distinction should be made between behavior of `<citedRange>` in `<listBibl>` and in other contexts.

Behavior in `<listBibl>` is now satisfactory for me, **with the bold**.

But in other contexts, we do not expect any "page" or "pages" to be inserted in the display. Rather, we wish to see the usual AUTHOR DATE: NUMBER format. Thus, in the following example

<img width="1021" alt="Capture d’écran 2020-10-06 à 16 15 51" src="https://user-images.githubusercontent.com/835603/95214358-1e7d3680-07f0-11eb-9757-c51c274ebe1c.png">

we should see "[Casparis 1950](url): 151–160" instead of "[Casparis 1950](url), pages 151–160".    

@manufrancis @AnneSchmiedchen @danbalogh : your votes please.

**Comment by AnneSchmiedchen** [comment]
Yes, no "page" or "pages" in these contexts, please.

**Comment by danbalogh** [comment]
I agree.

**Comment by manufrancis** [comment]
Fine with me.
