### ISSUE TITLE
sharing our html displays beyond members of erc-dharma on GitHub

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#83]
@ajaniak : I have been discussing with Marine and Manu ways in which we can share our html displays with non project members (e.g., the participants of my EPHE seminar).

Marine proposed this:

> [https://htmlpreview.github.io/?https://github.com/m-schoettel/docs/blob/master/inscriptions/Kabhagavanan2020-08-30.html](https://htmlpreview.github.io/?https://github.com/m-schoettel/docs/blob/master/inscriptions/Kabhagavanan2020-08-30.html)
> 
> Si on prend ce lien, on voit qu'il est fait de deux parties :
> - une première URL qui sert de "préfixe" et qui permet d'interpréter une ressource en html : [https://htmlpreview.github.io/?](https://htmlpreview.github.io/?)
> - une deuxième URL qui est simplement l'adresse du fichier html sur le repo github :
> [https://github.com/m-schoettel/docs/blob/master/inscriptions/Kabhagavanan2020-08-30.html](https://github.com/m-schoettel/docs/blob/master/inscriptions/Kabhagavanan2020-08-30.html)
> 
> Il suffit donc de préfixer les URL hébergeant tes éditions par [https://htmlpreview.github.io/?](https://htmlpreview.github.io/?) pour obtenir le lien vers l'édition visualisée. Il faut aussi veiller à ce que le fichier css mentionné dans le html (ici `<link rel="stylesheet" type="text/css" href="./../inscriptions/global.css"/>`) soit bien accessible sur le repos git. J'espère que cela marchera bien, n'hésite pas à tester et à revenir vers moi pour davantage de précisions. Tu peux aussi trouver plus de détails sur le repository git du projet : [https://github.com/htmlpreview/htmlpreview.github.com](https://github.com/htmlpreview/htmlpreview.github.com) 

I tried to use this approach by moving global.css and an .html file from my (untracked) local version of [https://github.com/erc-dharma/project-documentation/tree/master/stylesheets/output](https://github.com/erc-dharma/project-documentation/tree/master/stylesheets/output) into a newly created folder [https://github.com/erc-dharma/tfc-nusantara-epigraphy/tree/master/output](https://github.com/erc-dharma/tfc-nusantara-epigraphy/tree/master/output) which I did push to github. But clicking on the URL [https://github.com/erc-dharma/tfc-nusantara-epigraphy/blob/master/output/WuruduKidul2020-10-01.html](https://github.com/erc-dharma/tfc-nusantara-epigraphy/blob/master/output/WuruduKidul2020-10-01.html) just shows the code — it doesn't display the html in my browser. 

Manu has proposed some other tricks, like pushing the button "Open this file in GitHub Desktop", but they haven't worked for me either.

Can you propose a solution? Thanks!

**Comment by ajaniak** [comment]
Considering the solution from Marine, I am not sure not only it is not really clean, we don't have the hand of this tool and I already have the following error message so on a long run I wonder if it will be sustainable for your EPHE seminar : `Error: Cannot load https://raw.githubusercontent.com/m-schoettel/docs/master/inscriptions/Kabhagavanan2020-08-30.html: 429 Too Many Requests`

I wonder why you don't ask people to download the html and open it on their web navigator? It is the easiest solution for everyone, since indeed github purposes is not to display interpreted version of htmls but to show the codes itself. You can't ask a system to do what it isn't supposed to do. 

If really, you want a cleaner way to show your htmls, I would recommend setting up a github website.

**Comment by arlogriffiths** [comment]
Thanks. If I send the html's to participants, as you suggest, then I  need to send along global.css and tell participants to store the two files in one folder, before opening the html in a browser, right?

**Comment by ajaniak** [comment]
No, you don't. 
I have changed the css calling now the css is fetched from online once Manu shared the subject with me. From now on, the htmls can be stored anywhere without fear to break the link with the CSS.  However, on the downsides, it means that the one receiving it will need an internet connexion. And since gitHub can't handled directly the content-type css, but only text/plain, I add to use a translator to make it work and I am not sure how long it is work perfectly. 
By the way, the previous system wasn't working at the folder level. That's why the css wasn't taken into account.

However, if several members of the project requires a cleaner way to display. I can set up github pages at the organization level so that one system can be used by everyone when needed. But since it will take time to set it up and maintain it, i would ask all of you to be sure you really need it before starting on this side project.

**Comment by manufrancis** [comment]
I am fine with Arlo's final stand. Let us keep this issue open, as a not-pressing one.

**Comment by ajaniak** [comment]
I realize I have forgotten to tell you that such a system will have among the downside a short memory cached. So any changes in the CSS pushed on github will always take at least to 2 hours to implement!

**Comment by arlogriffiths** [comment]
Thanks. We'll take that into account when we return to this issue, in due course.

**Comment by arlogriffiths** [comment]
Update: sending htmls seems not to be posing any trouble. So maybe this issue can be closed?
