### ISSUE TITLE
explanation of @rend="siglum" and @rend="journal"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#86]
@ajaniak: Manu has closed #82, which was indeed getting excessively long and ciomplicated.

But it seems to me that we had not yet had the chance to discuss the attributes @rend="siglum" and @rend="journal" which were mentioned yesterday for the first time and don't yet figure in EGD.

1. Regarding @rend="siglum", can you explain where this will need to be used, for what purpose? I am not sure we ever need  the siglum, as defined in EGD 9.4.4, to appear other than in `<div type="apparatus">` and at the end of a `<bibl>` entry that contains @n inside `<listBibl>`, but in those contexts we don't need @rend to make the siglum appear. _Are you perhaps talking about a different kind of siglum?_

2. Regarding @rend="journal", I am also not sure that I have understood the need to introduce this attribute. I believe the default bibliographic mode in display of our .xml files should be for journal titles to appear in abbreviated form. If that is the case (_to be confirmed by others!_), then perhaps we don't need such an attribute, or could work with an attribute only in the exceptional cases that the full journal title is desired?

**Comment by manufrancis** [comment]
I have suggestions about this and will psot them when time permits, hopefully this week ;-)

**Comment by danbalogh** [comment]
Shouldn't this discussion take place in #81 ? At any rate, my doubts concerning the topic (which I think may have prompted Arlo to open this thread) can be found at https://github.com/erc-dharma/project-documentation/issues/81#issuecomment-704338641.

Regarding Arlo's point 2 above, I would prefer to see full journal titles in the structured bibliography (primary and secondary), and journal abbreviations everywhere else. But if your preference is abbreviations in the structured bibliography too, then I have no objection to that.

**Comment by arlogriffiths** [comment]
I have given my view on full/abbreviated journal titles on #81. For the rest, I patiently await Manu's suggestions.

**Comment by manufrancis** [comment]
@rend="journal" issue is solved. Feedback on Axelle's implementation (see #81) is requested.

On @rend="siglum" see comment in EGD googledoc at 9.4.3.

**Comment by danbalogh** [comment]
To answer Arlo's original question about where rend="siglum" might be used and to what purpose: Manu and I think it may be useful to use sigla to refer to previous editors of the text in some places outside the apparatus lemmas and readings, namely the commentary, notes in the apparatus, and notes in the translation. We might also want to permit this in the hand description (or in any part of the TEI header where free text is permitted).
In such cases, my practice so far (not very nice), has been simply to use the siglum as hard text, e.g. "PVPS connects the name Voṭṭi to Sāmanta Viṣṭi" and "VR's emendation", where PVPS is the siglum for an edition by P. V. Parabrahma Sastry and VR is another edition by V. Rangacharya.
The proposal that Manu endorses, if we understand each other right, is that instead of this barefoot method, we should from now on use `<bibl rend="siglum"><ptr target="bib:Rangacharya1955-1956_01"/></bibl>` instead of just VR. The precondition of this would, of course, be that the item referred to is present in the primary bibliography, and a siglum is assigned to it there (i.e. `<bibl n="VR"><ptr target="bib:Rangacharya1955-1956_01"/></bibl>`).
The above encoding would then be simply displayed as the siglum, with a tooltip showing the bibliographic details.
The advantage is easier legibility, when you repeatedly refer to the same edition and do not need a page number or any other details.
I would thus add that a citation with rend="siglum" must never contain any further details except the `<ptr>`; if details such as a page number are needed, then we should continue encoding a generic reference.

@arlogriffiths : do you like this?
@ajaniak : is this feasible to display and do you think it's acceptable encoding practice?
@manufrancis : is this in line with your thinking?

If the answer to all the above is yes, then we'll need Axelle to implement the code, and I'll add the appropriate instructions to EGD §10.4.5 (not §9.4.3). All of us who have been using some method to refer to editions by sigla will then have to change our provisional sigla to the above encoding.

**Comment by manufrancis** [comment]
@danbalogh : yes, fully in line with my thinking.
One question: could not the item be also in the secondary bibliography?
The EGD currentlys says (9.4.3): "this applies regardless of whether the full citation is in your primary bibliography or the secondary one"

**Comment by danbalogh** [comment]
Indeed, Manu, thanks. I've now edited the above. The secondary bibliography can of course also include a siglum declaration.

**Comment by ajaniak** [comment]
I have updated the code initially written for Manu and added the tooltip possibility. However, what do you expect exactly in the tooltip? 
- the full reference, such as Mahalingam, T. V. 1988. Inscriptions of the Pallavas. New Delhi; Delhi: Indian Council of Historical Research; Agam Prakashan
- or the citation pattern, i.e. Mahalingam 1988. 

I also need a clarification regarding the siglum spelling. Manu's has used IP_22 with an underscore in another issue but the EGD states that it should be written with a space IP 22. Can you confirm me you are keeping the second solution, so I know if I keep the replace pattern for underscore in the code?

**Comment by manufrancis** [comment]
I expect in the tooltip the citation pattern, i.e. Mahalingam 1988.

As for the siglum spelling, I will change my sigla of the type "IP_22" and revert to "TVM".
I will also change my sigla of the type "ARIE 1904-1905" to just "ARIE". In that case, could the tooltip be "ARIE 1904-1905" (with space) based on the Zotero short title "ARIE1904-1905" (without space)?

**Comment by ajaniak** [comment]
It is implemented. Can you check the result of the new code and let me know it if matches your expectations?

**Comment by arlogriffiths** [comment]
No objections from my side to any of the above.

I just wonder whether a less verbose manner of calling the siglum might be imaginable? In the EGC, we are offering a shortcut for calling manuscript sigla, for which in the case of critical editions xml:id's of course need to be defined in `<listWit>`. This allows us to use the following type of shortcut when witness "C1" needs to be mentioned in free prose:

> `<p>`It is fascinating that `<ref target=”#C1”/>` is written in red ink.`</p>`

Is any such approach possible in the case at hand? I fear the answer is no, if we don't want to take recourse to using xml:id, but I ask nonetheless — also to request a reminder as to why we haven't decided to work with an authority file for sigla, in which case I suppose we could have done something like `<ref target=”sigl:VR”/>` to get the result aimed for in your example above.

**Comment by danbalogh** [comment]
I agree that a less verbose method would be very welcome. @ajaniak : would it not be possible to change our siglum use method so that
1. instead of `@n`, we use `@xml:id` in the structured bibliography to assign a siglum to an entry (e.g. `<bibl xml:id="EH">`), and
2. then use that `@xml:id` to refer to publications that have a siglum (e.g. `<ref target=”#EH”/>`), and display those references as the siglum with a tooltip?

@arlogriffiths : as far as I can tell, the idea of using an authority file for sigla has never come up before. But I don't think it's a good idea, since the sigla would then have to be unique throughout the project. But with the above approach, sigla (i.e. `@xml:id`-s) would only need to be unique within each file, and there would be no problem with using the same siglum in different XML files for different publications of the same author.

**Comment by ajaniak** [comment]
Dear all, 

I understand the will in favor of a less verbose syntax, but in that case does it mean that encoding patterns for `omitname` and `ibib` that siglum was following should be change as well? 

First, let's not use `<ref>` to do so. Indeed, if both `<ref>`and `<ptr/>` are used to link. `<ref>` should contains a textual content that will be hyperlinked, while `<ptr/>` is a self-closing element working to point or retrieve content from elsewhere. I wouldn't change the logic currently applied in the EGD regarding those 2 elements. 

I am reluctant to add `@xml:id` inside our encoding. Strictly, the Zotero short title is already used as an ID, so adding another layer isn't a good practice and could be confusing for some members and reusers after the project. We could use the attribute `@cRef` if we considere those sigla as canonical references. 
 
Wouldn't it be easier to just say that any <ptr/> used on its own, so not used with `<bibl>` as parent element, would be renderer as a siglum. Such a solution would allow to keep the current logic of the EGD since `<ptr target="bib:blabla"/>` would be fetching the content of the `@n` attribute provided in the bibliography. I still wonder if it is clear enough though. In this case why not keep an attribute `@rend="siglum"` in the `<ptr/>`, so `<ptr target="bib:blabla" @rend="siglum"/>`. 

So I guess I be in favor of `<ptr target="bib:blabla"/>` or `<ptr target="bib:blabla" @rend="siglum"/>`.

**Comment by danbalogh** [comment]
1. I think "omitname" and "ibid" should not be changed in any way, since most of the time these will be used in conjunction with `<citedRange>`.
2. Thanks for clarifying `<ref> `and `<ptr/>`; I was not conscious enough of this difference. Using `<ptr/>` would of course be perfectly fine. (And in this case, the same should, I guess, be done in the EGC for manuscript witnesses.)
3. I think this is a bit beyond me, but if I'm not mistaken, our sigla cannot be called canonical references, since their meaning changes from file to file. A siglum, e.g. JFF, may mean one publication (e.g. Fleet1865_01) in one XML file and a different publication (e.g. Fleet1888_13) in another XML file. But given 4 below, it seems we can safely forget about both `@xml:id` and `@cRef`.
4. It's never occurred to me that we could use a bibliographic pointer without an enclosing `<bibl>`. But if doing so is not frowned upon in TEI circles, then I'd be perfectly content with the method you suggest, i.e. `<ptr target="bib:blabla"/>` without `@rend="siglum"` (for simplicity's sake) if we can informally declare that this encoding is only used for sigla and let it go at that, but with `@rend="siglum"` if the former is bad practice.

Finally, one more point, concerning the contents of the tooltip. @manufrancis has said [above](https://github.com/erc-dharma/project-documentation/issues/86#issuecomment-764745797) that he wants the tooltip to show just the author-date citation. I'm OK with that if it's a definite preference, but would it not be better for the tooltip to show the full bibliographic details, just as the tooltip shown for a regular (non-siglum) bibliographic reference would?

**Comment by ajaniak** [comment]
@danbalogh, to answer the 4. using `<ptr/>` on its own isn't frowned upon. It is not the most used feature of the TEI, but it is used when there is a bibliographic DB and no textual or encoding anchor already provided. If I am not mistaken, it is used by the Digital Latin Library.
If @manufrancis, @arlogriffiths and @AnneSchmiedchen feel confortable enough with `<ptr target="bib:blabla"/>`. I am also in favor of no `@rend` attribute. 

Regarding the content of the tooltip, both are feasible technically. Not in the strict context of the html output since they don't have a backend codes to switch from one solution to the other, but we could provide the possibility to choose the content of the tooltip for the user. I honestly don't know if such a feature could be an expectation for the display.

**Comment by danbalogh** [comment]
Thanks, all this sounds good to me. Enhancing the tooltips can be left for later.

**Comment by danbalogh** [comment]
@ajaniak : Arlo, Manu and I have revised the siglum creation rules in the EGD (§9.4.3 at the moment, though I'll probably move these to a subsection of §10 when I write up the use of sigla in commentary and so on). I need your help in one point: should we restrict sigla to alphanumeric characters or is it OK to use some symbols in them? In particular, it would be good if we could use & in sigla of multi-author publications, but since this is a problematic character, I believe we could all agree on using + instead, provided that this is technically manageable. Also, while we are at it, should we avoid non-ASCII characters in sigla, or is it perfectly OK to use special accented characters such as Ś?

**Comment by ajaniak** [comment]
You don't have to restrict the sigla to alphanumeric characters. For now, I just retrieve the content, but I guess even if we need to add some work on the string itself it will be limited. And I will never use the sigla to retrieve data, or match data since I have the ZST. So I don't see technical reason to limit it. 

So regarding non-ASCII characters in sigla, as long as people provide the utf-8 character when typing, it should be ok.
For some symbols will need to provide the html entity code rather than use the utf-8 encoding. Oxygen will identity as mistake those, since the list is the same or nearly the same, for XML and HTML. & is one of them. `&` should be `&amp;` but its interpretation even in html will be `&`. So both + and `&amp;` are good for me. 

However, if some treatements of the string are expected, such as if underscore display a space instead. We will need to lead clear rules, because I will have a limited possibilities to codes rules in this case. 

Please be aware also that I haven't implement the full code yet, so it is normal if it is not working yet!

**Comment by manufrancis** [comment]
I concur with Dan's comments in 4 points above.
I am fine with `<ptr target="bib:blabla"/>`, without @rend.
As for the content of the tooltip display of "author-date citation" less cumbersome and concur again with Dan that this can be left for later.

@arlogriffiths and @AnneSchmiedchen Can we have your vote?
This will help Axelle finalizing the implementation of the DHARMA schema and also to close the issues related to @rend="siglum" and @rend="journal".

**Comment by danbalogh** [comment]
Thanks, Axelle. I don't think we'll want any manipulation of the sigla. I'll continue the discussion with Manu and Arlo in EGD comments so as not to hijack this thread.

**Comment by danbalogh** [comment]
@ajaniak I'll ask encoders in the EG not to use & in sigla (because I'm afraid people will forget to use &amp; and raise errors). We'll stick to + for multi-author sigle. But given the input from Manu and Arlo, it would be best if - in the long run - this could be replaced in display with an & character. This is the only transformation we'll want, but it would be nice to have this, so e.g. if the siglum is "S+G", then it is displayed as S&G. Does this sound feasible?

**Comment by ajaniak** [comment]
I have added a replace patter to transform + into & inside the new template for ptr. 

The code requires bibliographic data, so it will be effective only transforming your file with start-edition-with-bibl.xsl. 
I have kept start-edition.xsl running by not adding the specific template, since I know some members are still using this XSLT. But the downside of this is that `<ptr>` won't have any display, like the rest of the bibliographic data.

**Comment by danbalogh** [comment]
Thanks, this is great. I will make the necessary changes to the EGD.
I'm one of the people still using start-edition.xsl, but if we are ready to deprecate it, i.e. if the one with bibl works correctly in all details, then I don't mind changing over to with-bibl. Let me know whenever you want to take it out of circulation.

**Comment by ajaniak** [comment]
At some point, we will indeed need to deprecated it, because it limits transformation scenarios. But I would like to add a control of the Zotero ST in the Schematron to overcome the reason we had to have 2 lauching files first. So I hope in the following weeks, we should be ready to do it.
