### ISSUE TITLE
on French espaces insécables

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#91]
@ajaniak: When typing French (in translations, in quotes), is it recommended to explicitly type espaces insécables where they are expected in French typography, or is it better not to type them and to let our system insert them where they are wanted (as long as @xml:lang is duly encoded)?

Example: which of the following versions should I retain, version 1 (with spaces before : and ?) or version 2 (without)?

1. `<note>Bergaigne adds to his reading the note: <q xml:lang="fra">Pour <foreign>guptau</foreign> ? Le contexte suggérerait plutôt <foreign>gatau</foreign> : mais cette correction serait trop éloignée du texte</q>.</note>`
2. `<note>Bergaigne adds to his reading the note: <q xml:lang="fra">Pour <foreign>guptau</foreign>? Le contexte suggérerait plutôt <foreign>gatau</foreign>: mais cette correction serait trop éloignée du texte</q>.</note>`

@danbalogh: should the EGD contain any guidance on this question?

**Comment by danbalogh** [comment]
@ajaniak : would it be possible to make the display transformation insensitive to whether or not they are present, so that both Arlo's version 1 and 2 display as expected?
Whether it's possible or not, and whatever you decide on, I'll find a place to add a note on this to the EGD, though we don't really have a suitable section. Perhaps a new appendix on style issues in modern languages? That could also be the place to put some other items that I've been reluctant to add on the grounds that they concern style, not encoding.

**Comment by arlogriffiths** [comment]
Can we come to a conclusion on this point? I would like to know how I should tell my team members to encode.

**Comment by ajaniak** [comment]
I haven't answer this issue yet because I am trying to find a stable solution. 
Indeed, I am reluctant to add such feature to the HTML XSLT because I had to force several hierarchy levels already making it a little unstable. So I am exploring several possibilities : a pipeline to add a step to handle editorial features before the html or an automated launching to clean the content of the French parts linked to the repositories. I will try to have a more advanced answer for the brainstorming.

**Comment by manufrancis** [comment]
Pipeline for editorialisation setup by Axelle Janiak, following DHARMA brainstorming (2021/12/17).
